### ISSUE TITLE
GSTIN required for Overseas customers with LUT

### ISSUE THREAD

**Issue by arjoonn-s** [resilient-tech/india-compliance#1011]
### Information about bug

- I have a customer that is overseas and have submitted a LUT so that I don't need to pay GST for this income.
- While creating an invoice for this customer I still keep getting asked to add a GSTIN for this entity though I have set the category to overseas.

What I think should happen:

- For this particular customer my address and GST details + their address should be the only required fields.

### Version

ERPNext: v14.36.0
Frappe Framework: v14.46.0
India Compliance: v14.16.0

### Relevant log output / Stack trace / Full Error Message.

```shell
- ![image](https://github.com/resilient-tech/india-compliance/assets/120045237/1b6ffc1e-8d2a-4358-810b-aa8d899ed6e0)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
You probably got this wrong.

Company GSTIN comes from the Company Address. Do you have one for the company? This has nothing to do with the Customer having GST Category as Overseas.

**Comment by arjoonn-s** [comment]
Oh it worked!

I was getting confused since I had already added the gstin on the company page. I didn't realize that I need to add it to the address as well.

![image](https://github.com/resilient-tech/india-compliance/assets/120045237/0a6ef9b3-d058-45b3-8ffc-bb5a91f1bb14)

**Comment by arjoonn-s** [comment]
@vorasmit I was thinking, perhaps it would be nice to have the error message or some other part of the system inform people that they need to insert GSTIN in two places.
