### ISSUE TITLE
GSTN for export customers during e-invoicing

### ISSUE THREAD

**Issue by ADANGI83** [resilient-tech/india-compliance#1022]
### Information about bug

Hi,
When I am trying to raise an e-invoice for an export customer, the system is throwing an error that "GSTIN / UIN is missing in Address CUSTOMER NAME.-Billing. Please update it and try again."

Overseas customers dont have a GST number so what to do?

<img width="773" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/144000136/328d735d-9a2d-4e44-b52e-58f98bba6ab3">

Thanks

### Version

 Installed Apps
ERPNext: v14.36.0 (HEAD)

Frappe Framework: v14.46.0 (HEAD)

India Compliance: v14.16.0 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello,

The GSTIN for overseas customers is already handled from backend as URP (Unregistered Person). Kindly, ensure the GST category in the invoice is Overseas and try again.
To Edit the GST category you have to amend the invoice and select the correct GST category and submit it again.

Hope this helps.

Regards,
Lakshit Jain

**Comment by ADANGI83** [comment]
Thank you Lakshit for a prompt response . We were able to resolve the issues with this input.

Regards
Apurva

Regards
Apurva
________________________________
