### ISSUE TITLE
Tax Calculation on Differenctial Amount Only.

### ISSUE THREAD

**Issue by trackomatic** [resilient-tech/india-compliance#1037]
### Is your feature request related to a problem? Please describe.

We are in to the business of Used Cars i.e. Buying and Selling the Used Cars.

As per GST rule no. 32(5) of CGST Rules, 2017 and GST Notificaiton no. 9/2018 -Integrated Tax (Rate) dated 25.01.2018, We need to deposit the GST only on the Differential Amount (Sale Price of Used Car - Purchase Cost of Used Car).

To Simplify the issue, lets have an example:
1. We Buy a Second Hand/Used Car from an Unregistered person at a price of 1 lakh rupees. We create a Purchase Receipt to take the car in stock and a Purchase Invoice to pay the seller. We do  not apply any GST at this purchase invoice.

2. We spent another 20K rupees for getting it repaired and booked these expenses under expenses included in valuation of stock.

3. We create a landed cost voucher which makes the Cost of Car is 1.2 Lakhs.

4. Now We sell this second hand car to another unregistered person at a price of 1.25 Lakhs. We Create a Delivery Note to take the car our of our stock and a Sales Invoice to receive the payment from customer. We put the sale value of car i.e. 1.25 Lakhs on Sales Invoice.

5. Now to comply with Government Guidelines, we need to deposit GST @ 12% on the differential/profit amount i.e. on 5K (1.25 Lakhs - 1.20 Lakhs). In this case our tax liablity is 600 Rupees only.

6. But if we apply 12% GST on Sale Invoice, It is applied on total sales value i.e. on 1.25 Lakhs and our GST Liability goes to 15K rupees which puts us in loss due to wrongly applied GST tax.

7. Can you please advise us how to setup the GST in ERPNext so that the tax is calculated only on the Differential/Profit Amount?

We shall be thankful if someone can help us in setting up a tax template or any other method to implement the above calculation in ERPNext. 

### Describe the solution you'd like

Any Tax Template which takes the Serial Number / Part code / HSN Code in to account and calculates the GST on Differential Amount Only.

**Comment by ljain112** [comment]
Hello,

I recommend adding another item “Margin on Car,” with the applicable Tax Template. Classify the “Car” as an exempted good. When you generate an invoice, set the sale value of the car equal to its cost, and incorporate the profit or differential amount in “Margin on Car.” 

Hope this helps.

Regards,
Lakshit Jain
