### ISSUE TITLE
Not able to create e waybill against a transporter who's GST Transporter Id starts with 88

### ISSUE THREAD

**Issue by smanthprbhu** [resilient-tech/india-compliance#1044]
### Information about bug

To give the context of the issue, Transporter doesn't have a GSTIN number state-wise instead they use Transporter ID which starts with 88. In the portal user is able to generate the waybill for ID 88AAACD8017H1ZX but in ERPNext user is not able to generate the waybill for this scenario.

I'm trying to create a waybill for a Purchase return and I have followed the below-mentioned steps.
In the GST setting, I have enabled the setting for Enable e-Waybill Generation from Purchase Invoice:-
![234](https://github.com/resilient-tech/india-compliance/assets/138481313/e410a858-9b31-4a65-b16c-9f18239283e2)

In the supplier master, I have enabled the check box for the transporter (DTDC) where the GST Transporter ID was 88AAACD8017H1ZX and mentioned the GST category as unregistered (Since the system is not allowing to set the Category as GST Regular)
![3456](https://github.com/resilient-tech/india-compliance/assets/138481313/7aeb0a8f-4b8b-4258-9da6-1ca44d00f65a)

In one of the purchase returns, I considered the transporter mentioned above, and the system took the GST Transporter ID
![ewaybill screen](https://github.com/resilient-tech/india-compliance/assets/138481313/aaf2bb42-5140-4203-b39f-88c688e742b9)

On click of generate I'm getting this error:

![1234556](https://github.com/resilient-tech/india-compliance/assets/138481313/9bac6cf3-338e-4e43-ac02-89d80b85a40d)

Kindly look into this issue.

### Version

Frappe Framework: v14.45.0
ERPNext: v14.34.3 
India Compliance: v14.16.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
This issue should not have occurred in production. Are you using sandbox mode? Could you please share the Integration Request Log?

**Comment by vorasmit** [comment]
We can reopen if this is an actual issue. Closing this for now.
