### ISSUE TITLE
GST Status in Payment Entry

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#1052]
### Is your feature request related to a problem? Please describe.

Hello,

Like you added this feature of showing status of GST in Purchase Invoice and Sales invoice we also need in Payment Entry because while we are doing payment to the party then we are checking the status of the party GST.
![image](https://github.com/resilient-tech/india-compliance/assets/111174201/1dcc960f-a55e-4b09-9779-9a7e2609aba1)

**Comment by vorasmit** [comment]
Can I request a proposal from you?

Scenario:
One supplier can have multiple GSTINs. How can this be handled at the Payment Entry Level?

**Comment by precihole** [comment]
Hello,

This is required for payment entry because the accounts department needs to know the status of the GST of the supplier or customer because the GST of the supplier or customer should never be cancelled.
@vorasmit

**Comment by vorasmit** [comment]
We plan to have GSTR2A/2B reconciliation status in Payment Entry after which this will make less sense. Hence we don't plan to add this feature.
