### ISSUE TITLE
Set correct GST category if not set

### ISSUE THREAD

**Issue by ankush** [resilient-tech/india-compliance#1063]
https://github.com/resilient-tech/india-compliance/blob/9224fd882a6171cf5390f10e314028a4c3049526/india_compliance/gst_india/overrides/address.py#L21-L31

This validation breaks integrations, can't we just set the right category if it's not set here? I get throwing error on incorrect value but when it's unset there's only one sane way to move forward, so we might as well just do it in code.

**Comment by anandbaburajan** [comment]
The following question seems related, so sharing here:

While creating a new `Address` from server-side, if a user only passes the `gstin` and not the `gst_category`, can we auto guess and set the correct category? Right now a "GST Category cannot be Unregistered for party with GSTIN" error is thrown. In desk it works fine: when the user sets the `gstin`, the `gst_category` field is auto guessed and set.
