### ISSUE TITLE
Migration from v13 to v14

### ISSUE THREAD

**Issue by rajatnesto** [resilient-tech/india-compliance#1074]
I have existing creds from Adaequare in my v13 instance, now we need to migrate to v14, and I dont see any option where I can use the existing creds.

Is it mandatory to purchase creds from India Compliance or we can use the existing creds from Adaequare, if possible please let me know where should I apply the Client Id and Client Secret?

**Comment by vorasmit** [comment]
Hi,

Direct Integration with Adaequare is not supported.
More Info: https://discuss.frappe.io/t/why-the-gst-application-is-routed-through-the-resilient-tech/95542/2
