### ISSUE TITLE
E way bill generation for Stock Entry (send to subcontractor)

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#1075]
### Information about bug

Hello,

As you added option to create e way bill for Purchase Invoice and Delivery note like can you add option for Send to subcontrator also.
![image](https://github.com/resilient-tech/india-compliance/assets/111174201/62e497b2-e6b7-4ba3-b962-127ee71e72ac)

### Version

India Compliance: v14.16.2 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bhargav007n** [comment]
Much need option for india.

**Comment by JitendraSAW** [comment]
@vorasmit , Is this Features has been introduced
