### ISSUE TITLE
GST Category Wise Purchase Report

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#1092]
### Is your feature request related to a problem? Please describe.

For Goverment Audit purpose we need from all the Purchases which purchase are from exempted supplier, unregistered supplier and registered supplier. (Value Wise)

**Comment by vorasmit** [comment]
Please provide more details. Which sections of the Audit require this? What could be the format of the report? How this is handled in other softwares?

This is very little information for us to understand this as a feature request.

**Comment by vorasmit** [comment]
Closing for no response received.
