### ISSUE TITLE
Gstr-1 Not Including Return Invoices

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#1110]
### Information about bug

e.g.  In September Month 

Type="B2B Invoices"
return Include Total Of taxable amount is :11,13190.87. for Register Invoice
In Gstr-1 it showing  taxable amount :  11,93478.5

Diff Is return invoice value=80287.62

Also same For B2C small & Nil rated Invoices

### Version

ERPNext: v14.43.0 (HEAD)
Frappe Framework: v14.51.0 (HEAD)
India Compliance: v14.16.3 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Please share more context here. Share screenshots etc for us to replicate the issue.

**Comment by asoral** [comment]
Value With Return Screenshot Below:
<img width="165" alt="Screenshot 2023-10-12 at 12 42 36 AM" src="https://github.com/resilient-tech/india-compliance/assets/11851156/ed00fb7c-600d-494e-9505-3c157602cfc6">
<img width="481" alt="Screenshot 2023-10-12 at 12 42 58 AM" src="https://github.com/resilient-tech/india-compliance/assets/11851156/4b7be44a-7ca0-4c99-ae1a-e647ca7a782c">

Value Without return Screenshot Below:
<img width="135" alt="Screenshot 2023-10-12 at 12 43 41 AM" src="https://github.com/resilient-tech/india-compliance/assets/11851156/0955f6e0-6d8c-4592-94fd-f2e7e3ccbff3">
<img width="511" alt="Screenshot 2023-10-12 at 12 44 02 AM" src="https://github.com/resilient-tech/india-compliance/assets/11851156/73c9ab71-37c9-44d0-931d-74ac8fe9c0e8">


GstR-1 Taxable Value Screenshot Below
<img width="639" alt="Screenshot 2023-10-12 at 12 44 53 AM" src="https://github.com/resilient-tech/india-compliance/assets/11851156/05442e38-1624-477f-bb50-259f23b1f7e3">

**Comment by vorasmit** [comment]
Did you check this tab?

![image](https://github.com/resilient-tech/india-compliance/assets/10496564/05ddff41-9148-4683-a0ae-2f523c4ce548)

**Comment by vorasmit** [comment]
Let us know if you still face the issue.
