### ISSUE TITLE
"Ineligible Others" in ITC Eligibility not working in Purchase Invoice

### ISSUE THREAD

**Issue by nikkothari22** [resilient-tech/india-compliance#1111]
### Information about bug

We have purchase invoices wherein the ITC is not eligible because "POS and supplier state are same but recipient state is different" - (e.g: for rent/hotel stays). 

When we create a purchase invoice, we add the GST details of the supplier, but we set "Eligibility For ITC" to "Ineligible Others". This does not seem to have any effect though since the "Availed ITC Tax" field in the purchase invoice is reset to the GST amounts, and the ledger shows the ITC even though it should be booked as an expense since ITC is not available. 

Am I missing a step here? Should I instead create a new account under expenses for "GST Expenses" and change the tax account in the taxes table for such purchase invoices?

### Version

ERPNext: v14.43.0
Frappe Framework: v14.51.0
India Compliance: v14.16.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
This is a known issue and we are coming up with a refactor and bigger fix here.
