### ISSUE TITLE
New User Sign Up, place of supply not getting updated

### ISSUE THREAD

**Issue by msanjay05** [resilient-tech/india-compliance#1134]
### Information about bug

New User signup
Added item. to cart
Add Shipping address
here since there is  no billing address it picks shipping address as billing address and add to cart but place of supply is not updating it is taking from compnay address

But on clearing cart and again adding items to cart , place of supply is getting updated

### Version

frappe 14.50.0
erpnext 14.40
india-compliance 14.16.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Please share relevant screenshots and more detailed steps to replicate the issue. Are you referring to the issue in Point of Sale?

**Comment by vorasmit** [comment]
We can reopen this with further details and issue validation.
