### ISSUE TITLE
Sales Invoice is not Generated due to GST error

### ISSUE THREAD

**Issue by tsmanagers** [resilient-tech/india-compliance#1154]
### Information about bug

At the time of sales invoice creation, we are getting the below error, 

e-Invoice Status cannot be "Not Applicable". It should be one of "","Pending", "Generated", Cancelled","Failed."

### Version

Installed Apps
ERPNext: v14.44.0
Frappe Framework: v14.52.0
Frappe HR: v14.13.0
India Compliance: v14.16.3
Payments: v0.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Although it's not visible from the versions you gave, Would you happen to have a custom App? Have you exported custom fields to the custom app? 

Could you make sure India Compliance fields are removed from the custom app?

**Comment by tsmanagers** [comment]
in my ERP setup following is the value for e-invoice filed

![image](https://github.com/resilient-tech/india-compliance/assets/108806672/0bab0e4d-70b5-47a9-80bd-7a314a7459d6)

If I am setting up new system then following are the options

Pending
Generated
Auto-Retry
Cancelled
Failed
Not Applicable

If I am trying to update my field value through customize form then I am getting below error

You can't set 'Options' for field e-Invoice Status

**Comment by tsmanagers** [comment]
> Although it's not visible from the versions you gave, Would you happen to have a custom App? Have you exported custom fields to the custom app?
> 
> Could you make sure India Compliance fields are removed from the custom app?

We are not using any custom app.

**Comment by vorasmit** [comment]
Did you run `bench migrate` on your site?
If still you don't see this updated, run the following command in bench directory
`bench execute india_compliance.gst_india.setup.create_custom_fields`

**Comment by tsmanagers** [comment]
We executed bench execute command after that we got the below message on top of the sales invoice.

All accounts are already confined in GST Setting, so what are we missing?

GST is applicable for this invoice, but no tax accounts specified in [GST Settings] are charged.

**Comment by tsmanagers** [comment]
Issue solved. Thank you very much for such quick resolution.
