### ISSUE TITLE
299 : E-Commerce Operator GSTIN field should be empty when Tax Payer generates e-Invoice, 2195 : e-Commerce GSTIN is not registered as TCS-GSTIN

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1157]
### Information about bug

299 : E-Commerce Operator GSTIN field should be empty when Tax Payer generates e-Invoice, 2195 : e-Commerce GSTIN is not registered as TCS-GSTIN

### Version

ERPNext: v14.39.0 (version-14)

Frappe Framework: v14.49.0 (version-14)

Frappe HR: v14.10.6 (version-14)

India Compliance: v14.16.2 (version-14)

PDF on Submit: v14.0.4 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
We will need more details here. Can you please share Integration Log for this?

**Comment by vorasmit** [comment]
We can reopen this with further details and issue validation.
