### ISSUE TITLE
Default GST Expense Account in Company

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1202]
### Information about bug

Can you please guide which account we need to create in the chart of accounts & under which root type ?

### Version

ERPNext: v14.45.3 (version-14)

Frappe Framework: v14.53.2 (version-14)

Frappe HR: v14.14.0 (version-14)

India Compliance: v14.18.0 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Docs: https://docs.indiacompliance.app/docs/configuration/purchase_transaction#itc-ineligibility

Should be created automatically. If wasn't created, you can create one in Indirect Expenses.
