### ISSUE TITLE
Move Audit Trail settings to GST Settings

### ISSUE THREAD

**Issue by rtdany10** [resilient-tech/india-compliance#1257]
### Is your feature request related to a problem? Please describe.

Audit Trail is mandatory for Indian companies only. Making it a system-wide setting makes it impossible to delete a wrong accounting entry created in another company(not based in India) in a multi-company scenario.

### Describe the solution you'd like

Move it to GST Settings, and add a hook in the standard function to check for this based on company or override the function itself?

**Comment by vorasmit** [comment]
Hi,

This is a software-level requirement as per the company's act. This cannot be configurable. Hence it cannot be disabled once you enable it.
https://bcajonline.org/catdescription.php?catid=44097&cid=98#:~:text=The%20term%20'Audit%20trail'%20has,been%20made%20to%20the%20data.


If you wish to have a different setting for some of your companies, you should have a different site.
