### ISSUE TITLE
Display HSN code in separate lines if the Interstate and Intra state tax is applied

### ISSUE THREAD

**Issue by ram-chandu** [resilient-tech/india-compliance#1258]
### Is your feature request related to a problem? Please describe.

Hi Team,

Facing the following issue in live instance:

Here HSN-wise-summary of outward supplies report, if the HSN code is same and IGST, SGST, CGST all are applied then it shows in the same line. The user is expecting to display HSN code in separate lines if the Interstate and Intra state tax is applied. Please check.

Steps to replicate:

Go to the HSN-wise-summary of outward supplies report (https://v14-test-rcil.frappe.cloud/app/query-report/HSN-wise-summary%20of%20outward%20supplies?company=Rangsutra%20Crafts%20India%20Ltd&gst_hsn_code=63049289).
Filter the report by adding any HSN code(https://github.com/frappe/erpnext/commit/63049289f4fbafbbd8d14491cc89566ba21f0e39).
Observation:
1.Here you can see that if the HSN code is same and IGST, SGST, CGST all are applied then it shows in the same line.

Expectation:

Display HSN code in separate lines if the Interstate and Intra state tax is applied in the HSN-wise-summary of outward supplies report
Attaching the Screenshots for reference.

![267188738-31d88f4d-a9ea-435a-8592-e8be80f6af9e](https://github.com/resilient-tech/india-compliance/assets/119317369/9ab3de58-773e-46ea-8469-14a38ce0f7f5)

Thanks,
Ram.

### Describe the solution you'd like

Display HSN code in separate lines if the Interstate and Intra state tax is applied in the HSN-wise-summary of outward supplies report

### Additional context

![267188738-31d88f4d-a9ea-435a-8592-e8be80f6af9e](https://github.com/resilient-tech/india-compliance/assets/119317369/ec1b7c31-8c23-4c12-b917-e240e1d163fd)

**Comment by vorasmit** [comment]
The existing report is in line with GSTR-1.

![image](https://github.com/resilient-tech/india-compliance/assets/10496564/b564fee0-0b6c-40b5-95b9-1f601126bd89)

We understand more detailed reporting could be useful.
We have a GST Itemised Sales Register with All details, that can be compiled to have any information you require.
