### ISSUE TITLE
How to display the bank charges recorded through Journal Entry in GSTR-3B

### ISSUE THREAD

**Issue by ram-chandu** [resilient-tech/india-compliance#1259]
### Is your feature request related to a problem? Please describe.

Hi Team,

We have got a case in which the Bank regularly charges some amount from RS as bank charge, and on this RS pay GST and take input credit of the same. The transaction is recorded using Journal Entry to capture these types of expenses. We cannot use PI as the bank is not a supplier. Please refer transaction:https://v14-test-rcil.frappe.cloud/app/journal-entry/JV%2FFY23%2F0007

Observation: We are unable to see the transaction details at the GSTR-3B.
![267188738-31d88f4d-a9ea-435a-8592-e8be80f6af9e](https://github.com/resilient-tech/india-compliance/assets/119317369/746433d5-0dc4-4a92-a0bd-d55b919bf012)

Expectation: We would like to see the transaction in the GSTR-3B report

Please let us know in case if we are missing something.

Thanks

### Describe the solution you'd like

We would like to see the transaction in the GSTR-3B report

### Additional context

![267188738-31d88f4d-a9ea-435a-8592-e8be80f6af9e](https://github.com/resilient-tech/india-compliance/assets/119317369/1c569f4b-6ed2-47c4-ae4f-03e52ec77b61)

**Comment by vorasmit** [comment]
You should create a bank as a Supplier in that case and only book it through a Purchase Invoice.

## Why?
- Purchase Invoice is a full-fledged document with all required details for claiming credit
- Like Tax breakup, Supplier GSTIN, HSN codes etc
- It's difficult to capture this information from Journal entries.

It would be like duplicating purchase invoice functionality with manual accounting in Journal Entry. Hence we don't plan to support Journal Entry for GSTR3B or 2A/2B reconciliation tool.
