### ISSUE TITLE
How to setup and account for GST-TCS and TDS by Ecommerce Operators in Sales Invoices?

### ISSUE THREAD

**Issue by innomalous** [resilient-tech/india-compliance#1297]
Hello-

Can anyone recommend the best workflow to record Sales Invoices issued by e-commerce operators such as Amazon, Flipkart etc? And consequently accounting for the GST-TCS and TDS deducted by them before transferring payments to our bank account.

Please consider the following example:
![image](https://github.com/resilient-tech/india-compliance/assets/42608563/a309922e-0d73-4b82-8016-ad0e5be460f3)

Currently, I'm recording a Sales Invoice with a total of ₹336.00 (Row 1-4)
A Purchase Invoice is recorded for ₹106.58 (Row 8-11)
The payment receipt is recorded for ₹223.73 (Row 12)

How do I account for the TCS and TDS (Row 5-7)?
Is a Journal entry the best way to do it?

Or is there a better way? A journal entry for each transaction will be too slow and painful.

Any help is appreciated.

**Comment by vorasmit** [comment]
Did you try the tax withholding feature from ERPNext?
This can be applied to sales as well. You could also use this with -ve tax rates.

Drawback: Only one account could be used here.

Workaround: You could use 2% as tax rate as consolidated TDS, and then split this at regular intervals into respective accounts.

**Comment by innomalous** [comment]
Hi @vorasmit ,

For some reason, I am unable to find the Tax Withholding checkbox in the Sales Invoice.

**Comment by vorasmit** [comment]
There is no field for tax withholding in Sales Invoice. It's auto-applied as per your customer configuration.

**Comment by sjain17** [comment]
How to add TCS section 206 in Tax Withholding Category?
