### ISSUE TITLE
Support for same item with multiple item tax templates

### ISSUE THREAD

**Issue by vorasmit** [resilient-tech/india-compliance#132]
Use case
- Different tax rate based on Item Price

Things to resolve
- Issue with `item_wise_tax_detail` in taxes
- Update its usage at all places

**Comment by asifmohtesham** [comment]
Any update on this?

This is a need if an Item's Tax Rate changes based on the price of the item.

How do we apply different Tax Rate to the same Item's variation?

**Comment by ljain112** [comment]
Hello, @asifmohtesham,

In the Taxes Table in Item Doctype, you have the option to set multiple tax rates for items based on their prices or date. This allows for flexibility in managing different tax rates for different items, depending on their respective prices. 

However, it is important to note that multiple tax rate for single item in an invoice is not allowed.
