### ISSUE TITLE
Validate gst invoice number for all the transction doctype where api is callable

### ISSUE THREAD

**Issue by ljain112** [resilient-tech/india-compliance#1350]
Frappe Support : https://support.frappe.io/app/hd-ticket/6243

**Comment by vorasmit** [comment]
Suggested Implementation.
- Ensure 16-digit validation before the generation of e-Waybill
- We already validated this where e-invoice is applicable before submitting the e-Invoice
- Banner on Document Naming Rule and Document Naming Settings if doctype is one where e-Waybill is applicable
- Generate preferred series for new sites for DN / PI / PR
