### ISSUE TITLE
feat: Easy way to build custom print format while printing QR code

### ISSUE THREAD

**Issue by ankush** [resilient-tech/india-compliance#1362]
(I am not sure if Framework supports this or not, just that requirement resonates more with IC)

I've seen several users customize print format and add QR code manually by writing code to fetch data from log, this is okay but they don't really know everything so their print format code will likely break in edge cases... If IC can provide a reusable component/template for QR code in custom formats then that solves the problem for everyone. 

ref: https://docs.indiacompliance.app/docs/developer-guide/e_invoice_qr

**Comment by rtdany10** [comment]
Rather than a template, a jinja function that would take in invoice number and return the html code for img would be better(?)
