### ISSUE TITLE
India Compliance Account page: Improve UX and handle permissions correctly 

### ISSUE THREAD

**Issue by QuakeString** [resilient-tech/india-compliance#1380]
### Information about bug

I've recently moved to frappecloud from my Linode cloud, and my India-compliance module not working properly. there is no account setting option for india-compliance.
![2023-12-09_19-25](https://github.com/resilient-tech/india-compliance/assets/5375918/4ab9738c-726c-4149-861d-7e765a6b0704)

### Version

![2023-12-10_18-46](https://github.com/resilient-tech/india-compliance/assets/5375918/0992b177-50ba-4b28-b08c-8de46dba836b)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
API credits cannot be purchased on Frappe Cloud and as it comes bundled. Hence you don't see this on the frappe cloud.

In case you were already logged in, before migrating to the frappe cloud, log out of the India compliance account before migrating to the frappe cloud.

**Comment by QuakeString** [comment]
as I've already migrated without logout from India compliance due to it was not working in my previous instance. does it mean I'll never be able to use it ?

**Comment by vorasmit** [comment]
Are you trying to view the India Compliance Page from the System Admin Account?

**Comment by QuakeString** [comment]
I'm login as system user account, with all the access rights.

**Comment by QuakeString** [comment]
Hi, is there any update ?

**Comment by rtdany10** [comment]
![image](https://github.com/resilient-tech/india-compliance/assets/52111700/afea7483-5ccf-43d3-bf54-8643a8a31e77)

You can open the same from search bar and logout

**Comment by vorasmit** [comment]
You can update permissions from here and view it if you are still not able to view the account page. It's disabled by default for frappe cloud from here.

![image](https://github.com/resilient-tech/india-compliance/assets/10496564/33c89620-63be-4e2b-8831-b83293f36531)
