### ISSUE TITLE
Missing fields in GST Purchase Register

### ISSUE THREAD

**Issue by ishanloya** [resilient-tech/india-compliance#1382]
### Information about bug

After recent changes to Purchase Receipt, Bill No. and Bill Date fields aren't showing up in GST Purchase Register report.

### Version

ERPNext: v15.5.0 (version-15)
Frappe Framework: v15.4.1 (version-15)
Frappe HR: v15.5.0 (version-15)
India Compliance: v15.0.4 (version-15)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello,
This is an ERPNext issue and we have opened PR there.

frappe/erpnext#38742
