### ISSUE TITLE
Warn if Scheduler is disabled when generating Sales Invoice and e-Invoice or e-Waybill is applicable

### ISSUE THREAD

**Issue by tdlworld** [resilient-tech/india-compliance#1384]
### Information about bug

Hi, using GST module and recently updates Bench

Now getting this error,

Error in print format on line 6: the JSON object must be str, bytes or bytearray, not DebugUndefined

The Line No 6 is 
    {%- set invoice_data = dict(json.loads(e_invoice_log.invoice_data)) -%}

What could be the cause of the error?

I have checked the e_invoice_log table but the relevant record is not there. And in Sales invoice table the irn is showing.

How to fetch the data from GST site if its missing in e_invoice_log?

### Version

ERPNext: v14.34.3 (version-14)
Frappe Framework: v14.44.0 (version-14)
India Compliance: v14.15.1 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
No QR is showing.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Looks like an installation Issue.

Are you self-hosting this instance? Most likely scheduler is disabled, and because of this e-invoice log wasn't created.
Hence issue with Print Format.

**Comment by tdlworld** [comment]
Can you give one button on invoice to fetch the data in e_invoice_log?

**Comment by vorasmit** [comment]
This is a transitional thing for you and it doesn't warrant a feature.

We should identify if the scheduler is disabled before generating e-invoice or e-Waybill. We'll add such validations and confirm before submitting documents.
