### ISSUE TITLE
Error while generating eWayBill

### ISSUE THREAD

**Issue by nitin-anantpranali** [resilient-tech/india-compliance#1396]
### Information about bug

While printing the e-WayBill 
from print button,

![telegram-cloud-photo-size-5-6323197715739162820-x](https://github.com/resilient-tech/india-compliance/assets/116695322/e5daec6f-13c4-440d-b7cd-c4e51ca71de6)

its showing like this

![telegram-cloud-photo-size-5-6323197715739162766-y](https://github.com/resilient-tech/india-compliance/assets/116695322/5cbed3b0-29e2-435e-809f-26528aaeb349)

### Version

ERPNext: v15.5.0 (HEAD)
Frappe Framework: v15.4.1 (HEAD)
India Compliance: v15.0.4 (HEAD)
Payments: v0.0.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
Print Format Error
Error in print format on line 268: 'FreeTypeFont' object has no attribute 'getsize'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
This has been fixed with recent updates. Can you try updating the app and check if the issue persists?
