### ISSUE TITLE
GST Category on Address should have suspended and cancelled option as well

### ISSUE THREAD

**Issue by sjain17** [resilient-tech/india-compliance#1413]
### Information about bug

GST Category on Address should have suspended and cancelled option as well. In case the Supplier / Customer is registered but their GSTIN is not active or suspended or cancelled then there is no option to make sure it is Registered but suspended.

### Version

ERPNext: v14.53.0 (HEAD)
Frappe Framework: v14.58.0 (HEAD)
Frappe HR: v14.18.1 (HEAD)
India Compliance: v14.19.6 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
No error
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello @sjain17,

We already have a separate doctype where we store the status of the GSTIN. It will be auto-updated based on your GST settings. Additionally, we validate the GSTIN before allowing transactions based on the GSTIN doctype.
![image](https://github.com/resilient-tech/india-compliance/assets/108322669/9f790f07-ba46-4c69-9526-41eb36d223c2)
![image](https://github.com/resilient-tech/india-compliance/assets/108322669/f485f6a5-df2a-419e-9abd-45fb117f0b9d)
![image](https://github.com/resilient-tech/india-compliance/assets/108322669/5c79cbbc-5006-455f-b357-f695ba24a0b1)

**Comment by sjain17** [comment]
Thanks for the upddate.
