### ISSUE TITLE
Controller permission issue

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#1418]
### Information about bug

Hello, @vorasmit @sagarvora ,

when i add pending e-invoice number card to Sales User dashboard i am getting an error.
![e inv number card](https://github.com/resilient-tech/india-compliance/assets/111174201/378b417e-4d35-41f1-9be4-7e79bea52315)

### Version

India Compliance: v14.19.6 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Hi,

We were not able to replicate this.
Does your sales user have access to the number type doctype?

**Comment by precihole** [comment]
> Hi,
> 
> We were not able to replicate this. Does your sales user have access to the number type doctype?

Hi @vorasmit ,

there is Number Card doctype which all user have permission.
![image](https://github.com/resilient-tech/india-compliance/assets/111174201/8d577e7f-7bc8-4894-b1fc-9b4bcc224388)

**Comment by precihole** [comment]
Hello, @vorasmit 

there are two Number cards in which first one is accessable but second one in which you have used script is not able to see on sales person dashboard.

![image](https://github.com/resilient-tech/india-compliance/assets/111174201/4520ffb4-3004-4fd1-86d4-516cab969f8b)
![image](https://github.com/resilient-tech/india-compliance/assets/111174201/79d55519-3fd6-4621-a438-8bdf4baabf2c)
