### ISSUE TITLE
Sale invoice print format type `e-invoice`

### ISSUE THREAD

**Issue by nayan-flooid** [resilient-tech/india-compliance#1436]
### Information about bug

In `e_envoice.html` file line ` <p>{{ get_state(address["Stcd"]) }} - {{ address["Pin"] }}</p>`  not giving expected output.
Its giving wrong `Stcd`

### Version

ERPNext: v14.54.2 (HEAD)
Frappe Framework: v14.59.0 (HEAD)
India Compliance: v14.19.6 (HEAD)
Payments: v0.0.1 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
@nayan-flooid ,
Can you describe what was expected and what is the output with relevant information?

**Comment by nayan-flooid** [comment]
> @nayan-flooid , Can you describe what was expected and what is the output with relevant information?

Here it suppose to give a correct state name and PIN from the address.
But its giving wrong state and PIN.

**Comment by vorasmit** [comment]
Can you please share the screenshots of the Invoice, e-Waybill, and addresses? Please show what should be the correct state for you.

The little information you provided makes it difficult to identify the issue.

**Comment by nayan-flooid** [comment]
![Screenshot from 2023-12-19 14-20-50](https://github.com/resilient-tech/india-compliance/assets/154306926/af806218-4bb8-4b24-a48b-c739381f8d76)
![Screenshot from 2023-12-19 14-21-45](https://github.com/resilient-tech/india-compliance/assets/154306926/7fd1ddd6-ee98-4903-9fa5-c9ac8cec9135)

here i have upload 2 images where `. Party Details` is from generated invoice and another is from customer address.

**Comment by vorasmit** [comment]
Looks like you have generated this in Sandbox mode.
FYI, Company GSTIN and State are hardcoded in Sandbox mode so that you can try generating an e-invoice within the scope of Sandbox GSTIN.

Even the Company GSTIN should be dummy `02AMBPG7773M002`

You'll not face any issues when generating invoices in production.

**Comment by nayan-flooid** [comment]
> Looks like you have generated this in Sandbox mode. FYI, Company GSTIN and State are hardcoded in Sandbox mode so that you can try generating an e-invoice within the scope of Sandbox GSTIN.
> 
> Even the Company GSTIN should be dummy `02AMBPG7773M002`
> 
> You'll not face any issues when generating invoices in production.

Ok got it
thanks

**Comment by nayan-flooid** [comment]
I have another question on `Work order` creation.
When i try to submit its throwing me error.
![Screenshot from 2023-12-19 14-44-04](https://github.com/resilient-tech/india-compliance/assets/154306926/48d62219-bc75-46d5-9da5-e629a228f413)
Why this message is showing?
I am creating work order which has start date on august but not able to create with old date.

**Comment by nayan-flooid** [comment]
@vorasmit I have tried as you said but still getting same data.

**Comment by vorasmit** [comment]
@nayan-flooid

You can still post here, and the issue can be re-opened if it's genuine.
Can you share the integration request log for e-Invoice?
