### ISSUE TITLE
Work order creation

### ISSUE THREAD

**Issue by nayan-flooid** [resilient-tech/india-compliance#1439]
### Information about bug

![Screenshot from 2023-12-19 14-44-04](https://github.com/resilient-tech/india-compliance/assets/154306926/baf3ce84-3072-4ad8-b712-c7c9c6694159)
Getting this error while creating work order.

### Version

ERPNext: v14.54.2 (HEAD)
Frappe Framework: v14.59.0 (HEAD)
India Compliance: v14.19.6 (HEAD)
Payments: v0.0.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
When i try to submit its throwing me error.
Why this message is showing?
I am creating work order which has start date on august but not able to create with old date.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
There are different repositories for different Apps.

You should report issues in relevant repositories.
ERPNext: https://github.com/frappe/erpnext/
Frappe: https://github.com/frappe/frappe/
