### ISSUE TITLE
5002 : The field e-Commerce GSTIN must be a string with a minimum length of 15 and a maximum length of 15., 5002 : Invalid GSTIN

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1458]
### Information about bug

Please explain 

### Version

ERPNext: v14.53.0 (version-14)

Frappe Framework: v14.58.0 (version-14)

Frappe HR: v14.18.1 (version-14)

India Compliance: v14.19.6 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
What is the e-Commerce GSTIN you are trying to use? Is it of valid length?

If this response is received from Govt, what is the e-Commerce GSTIN being sent? Can be identified from the e-Invoice log.

---
PS: A better place to request for answer on such issues is the discussion forum

**Comment by dineshpanchal93** [comment]
@vorasmit Thank you

Noted
