### ISSUE TITLE
GST Details in Sales Invoice

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1467]
### Information about bug

GST Details - Wrong calcuation 

IGST Rate * Taxable Value ( Wrong Calucation )

IGST Rate % * Taxable Value.

Also in the some item calculating minus figure too. 

<img width="1429" alt="Screenshot 2023-12-25 at 1 26 00 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/afec5c6f-9906-4aaa-a2e2-e1a12a5f5894">

<img width="1429" alt="Screenshot 2023-12-25 at 1 26 32 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/e1425098-ee91-49b3-a8b6-05484a6593a8">

### Version

ERPNext: v14.56.0 (version-14)

Frappe Framework: v14.60.0 (version-14)

Frappe HR: v14.20.0 (version-14)

India Compliance: v14.21.1 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
@dineshpanchal93 

Thank you for reporting the issue.
