### ISSUE TITLE
GST 2B Purchase Reconciliation Help

### ISSUE THREAD

**Issue by tsmanagers** [resilient-tech/india-compliance#1478]
### Information about bug

At the time of reconciling purchases via purchase reconciliation tool this error occurred. How can I reconcile my purchases with GSTR 2A/2B?
![image (1)](https://github.com/resilient-tech/india-compliance/assets/108806672/6e48df11-9672-4797-81b5-46ecfc691c58)

### Version

ERPNext: v14.56.0 (version-14)
Frappe Framework: v14.60.0 (version-14)
India Compliance: v14.21.1 (version-14)
Payments: v0.0.1 (develop)

### Relevant log output / Stack trace / Full Error Message.

```shell
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
@tsmanagers Can you please share the traceback of the error?

**Comment by vorasmit** [comment]
Accept my / supplier values can only be done if there is a match. It cannot be done where there is a missing purchase or 2a/2b data.
