### ISSUE TITLE
Field not permitted in query: is_nil_exempt

### ISSUE THREAD

**Issue by tsmanagers** [resilient-tech/india-compliance#1523]
### Information about bug

At the time of sales invoice creation, we get the error below.

**Error: Field not permitted in query: is_nil_exempt**

We have 2 companies set up in the same ERPNext instance, one for India and one for the UK. Currently, the same error message comes if we are trying to create an invoice from an Indian or UK company. 

Currently we are not able to create any sales invoice.

GST does not apply to UK companies, but we still face issues. Per your documentation, we have updated the tax template and tried various combinations but have yet to be successful.

### Version

Installed Apps
ERPNext: v15.8.3 (version-15)
Frappe Framework: v15.7.0 (version-15)
Frappe S3 Attachment: v0.0.1 (master)
Frappe HR: v15.7.1 (version-15)
India Compliance: v15.3.2 (version-15)
Payments: v0.0.1 (version-15)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Exported customizations in your app may cause existing custom fields to be undone when migrating.
https://frappeframework.com/docs/user/en/guides/app-development/exporting-customizations

To fix this, you need to remove exported customizations for India Compliance app fields and run custom field creation again. You can use the terminal command for re-creating custom fields “bench execute india_compliance.gst_india.setup.create_custom_fields”.

**Comment by tsmanagers** [comment]
Still same issue. There is no any customization in custom app related to GST or Account module

**Comment by vorasmit** [comment]
Can you search for `is_nil_rated` in your custom app? Does it show as an exported field in your custom app? Fields of India Compliance App should not be exported to Custom App.

If this this not the issue, likely, that you did not migrate the site properly.
Try `bench migrate`

**Comment by tsmanagers** [comment]
I run migration again and still same issue

![image](https://github.com/resilient-tech/india-compliance/assets/108806672/1b5bfb64-48ea-46f8-bfe5-995c28de6526)

**Comment by tsmanagers** [comment]
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1715, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 454, in validate_link
    values.update(get_value(doctype, fields, docname))
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 129, in get_value
    value = get_list(
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/client.py", line 66, in get_list
    validate_args(args)
  File "apps/frappe/frappe/desk/reportview.py", line 79, in validate_args
    validate_fields(data)
  File "apps/frappe/frappe/desk/reportview.py", line 104, in validate_fields
    raise_invalid_field(fieldname)
  File "apps/frappe/frappe/desk/reportview.py", line 165, in raise_invalid_field
    frappe.throw(_("Field not permitted in query") + f": {fieldname}", frappe.DataError)
  File "apps/frappe/frappe/__init__.py", line 603, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 575, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 526, in _raise_exception
    raise exc
frappe.exceptions.DataError: Field not permitted in query: is_nil_exempt

**Comment by ljain112** [comment]
@tsmanagers 

In the recent update of the India Compliance App, We have improved workflow around the Item Tax template.

We have removed the field `Is Nil Exempt` Field and Defined GST Treatment For the same in the ITem Tax Template.

https://docs.indiacompliance.app/docs/developer-guide/migration-guide

Error is raised because it is trying to fetch from item.is_nil_exempt.But this field is deprecated.

There may be exported customisation(Custom Fields) in your custom app for the `Sales Invoice Item` table which includes is_nil_exempt which we have removed. But due to customisation, it gets synced again on migrate.



To resolve the issue kindly remove exported customisation for India Compliance Related Field from your app.



Hope this helps.

**Comment by mohsinalimat** [comment]
> @tsmanagers
> 
> In the recent update of the India Compliance App, We have improved workflow around the Item Tax template.
> 
> We have removed the field `Is Nil Exempt` Field and Defined GST Treatment For the same in the ITem Tax Template.
> 
> https://docs.indiacompliance.app/docs/developer-guide/migration-guide
> 
> Error is raised because it is trying to fetch from item.is_nil_exempt.But this field is deprecated.
> 
> There may be exported customisation(Custom Fields) in your custom app for the `Sales Invoice Item` table which includes is_nil_exempt which we have removed. But due to customisation, it gets synced again on migrate.
> 
> To resolve the issue kindly remove exported customisation for India Compliance Related Field from your app.
> 
> Hope this helps.

Solve my issue.

**Comment by nadarvinod** [comment]
Is there a way to export customisations specific to my app only?
