### ISSUE TITLE
Issue while Linking the GST Invoice to GST Inward Supply (GSTR2A Entries) while Purchase Reconcilation Tool

### ISSUE THREAD

**Issue by JitendraSAW** [resilient-tech/india-compliance#1553]
### Information about bug

Issue while Linking the GST Invoice to GST Inward Supply (GSTR2A Entries) while Purchase Reconcilation Tool
<img width="851" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/80260184/a02f2cbf-8116-4d44-aac9-4d7ce421e832">

### Version

<img width="725" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/80260184/e5fda204-0f6f-4594-88bc-18b3841b07ec">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello @JitendraSAW ,

Can you share traceback?
You can copy the error using `Copy error to clipboard`.
