### ISSUE TITLE
Invalid field name: enable_audit_trail

### ISSUE THREAD

**Issue by mohsinalimat** [resilient-tech/india-compliance#1597]
When I migrate site then below error comes.

Queued rebuilding of search index for site1.local

**Comment by sagarvora** [comment]
Does this comment help?
https://github.com/resilient-tech/india-compliance/pull/795#issuecomment-1607182899

EDIT: The linked comment refers to custom fields in the GST India module, but you can execute the similar function that does this for Audit Trail feature:
https://github.com/resilient-tech/india-compliance/blob/18fd88699666bca344865166306105e1c2dcde5e/india_compliance/audit_trail/setup.py#L13

**Comment by sagarvora** [comment]
Closing this, since you've open a topic on the community forum:
https://discuss.frappe.io/t/invalid-field-name-enable-audit-trail/115831

**Comment by mohsinalimat** [comment]
Issue solved with below link

@sagarvora thanks a lot.

https://discuss.frappe.io/t/invalid-field-name-enable-audit-trail/115831/2?u=mohsininspire
