### ISSUE TITLE
Error While Installing India Compliance app v15 on site - "The table 'tabGST HSN Code' is full"

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#1608]
### Information about bug

Error While Installing India Compliance app v15 on Site- "The table 'tabGST HSN Code' is full"

<img width="848" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/119041865/3363c67c-1d52-4857-aea0-1c49a584d75e">

### Version

ERPNext- v15.10.1
Frappe- v15.9.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Looks like either a database configuration issue or insufficient resources in your instance.
Can you please try with better RAM? Also, it would be nice to have full traceback to analyze it further.

**Comment by sagarvora** [comment]
Closing for now. @RJMHASKE please respond to reopen.
