### ISSUE TITLE
Showing incorrect value in GSTR3B outward supplies

### ISSUE THREAD

**Issue by Govind-Jangid** [resilient-tech/india-compliance#1630]
### Information about bug

Showing incorrect value in GSTR3B. Also there is no Journal Entry created in this month.
_GSTR1 & Sales Register are showing correct values._

<img width="1375" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/63184660/b2ee116e-f51d-4f0b-9ee0-f66094de347c">

<img width="1375" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/63184660/866156e8-2466-4e83-aced-35756bac893d">

<img width="872" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/63184660/5278d7fe-530c-4937-8a6a-f63622fed017">

### Version

<img width="1132" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/63184660/81e416ba-b55b-43e9-95bd-7767594621b7">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
It's very difficult for us to understand what's going wrong from the given information.
We would need more details to figure out the issue and help you resolve the same.

**Comment by mmplerp** [comment]
is this solve 
I have same problem
![Capture](https://github.com/resilient-tech/india-compliance/assets/166016033/d86f8283-20a1-4b12-8ec4-7d594a752ca7)

**Comment by vorasmit** [comment]
Can you please help us with correct value vs incorrect value.
How did you compute correct value?
Which value is incorrect?

**Comment by mmplerp** [comment]
(b) Other outward supplies(Nil rated,Exempted) value are not match from report we have check item wise sale but there are not nil rated sales all are taxableSent from my iPhoneOn 13 Apr 2024, at 1:37 PM, Smit Vora ***@***.***> wrote:﻿
Can you please help us with correct value vs incorrect value.
How did you compute correct value?
Which value is incorrect?

**Comment by mmplerp** [comment]
Please Solve this fast we have urgent 
you can call me - 9214221136 
Modern Marwar Pvt Ltd

**Comment by vorasmit** [comment]
@mmplerp,

A refactor is need for this, it's in progress and @ljain112 from our team is on it.
