### ISSUE TITLE
Multiple Tax Items in Purchase Invoice  

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1648]
### Information about bug

Is it possible to resolve by this way?

<img width="1365" alt="Screenshot 2024-01-31 at 5 50 38 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/3a60fd5f-12a7-4ce3-90d6-d781b1f3d2f7">

When I create the Purchase invoice -  sometimes the item tax template is 18% 12%

When i am trying to add it manually it does not work.

### Version

ERPNext: v14.60.1 (version-14)

Frappe Framework: v14.62.2 (version-14)

Frappe HR: v14.21.1 (version-14)

India Compliance: v14.23.1 (version-14)

Qrcode Generator: v0.0.1 (main)

Reports: v0.0.1 (main)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Auto selection of Item Tax Template in Transactions would only work if there is one valid Item Tax Template.

Moreover, Item tax templates don't require tax categories and can include all the accounts from In-State and Out-state.
However, if you do want them to be separate, you need to select the tax category at the transaction level to be able to choose the item tax template.
