### ISSUE TITLE
Overseas Supplier  GST Category

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1649]
### Information about bug

https://github.com/resilient-tech/india-compliance/assets/21578167/36f72c9b-ac12-4eef-885a-db63a36bdf3c

### Version

Frappe Chat: v0.0.1 (main)

ERPNext: v14.60.1 (version-14)

Frappe Framework: v14.62.2 (version-14)

Frappe HR: v14.21.1 (version-14)

India Compliance: v14.23.1 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
@dineshpanchal93 
Maybe the country of the supplier is `India`.
For the `Overseas` gst category, the country shouldn't be India.
Kindly change the country and the issue should be resolved.

**Comment by dineshpanchal93** [comment]
Yes resolved !! thank you so much
