### ISSUE TITLE
Please switch to version 16 of Frappe to use the current version of India Compliance.

### ISSUE THREAD

**Issue by DeepBhat** [resilient-tech/india-compliance#1666]
### Information about bug

While trying to run `docker exec frappe-backend-1 bench install-app india_compliance` I am getting the following logs

```
App erpnext already installed

Installing india_compliance...
Incompatible Frappe Version: 
Please switch to version 16 of Frappe to use the current version of India Compliance.
```
But there is no version 16 of Frappe. The latest version on their [website](https://github.com/frappe/frappe) is 15.13.0. How do I get version 16? Even the [docs](https://docs.indiacompliance.app/docs/getting-started/installation) say
> Select Frappe Version-14 or above and select ERPNext and India Compliance from Apps to Install.

What do I do?

### Version

Frappe Version - 15.10.0
ERPNext version - Latest
India Compliance - Latest

### Relevant log output / Stack trace / Full Error Message.

```shell
App erpnext already installed

Installing india_compliance...
Incompatible Frappe Version: 
Please switch to version 16 of Frappe to use the current version of India Compliance.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
@DeepBhat

Version-16 refers to the `develop` branch of Frappe.
Kindly switch to the develop branch of Frappe to resolve the issue.

**Comment by DeepBhat** [comment]
Is it safe to use `develop` branch in production?

**Comment by vorasmit** [comment]
Not Recommended.
The point is, that all apps should be on the same branch.

Your ERPNext and India Compliance seem to be in develop.

**Comment by DeepBhat** [comment]
I just used the docker container for ERPNext, I do not think I am on `develop` branch for any where. I want this app for daily use for a large organization. Could you please guide me what I  can do to get this app working with Frappe and ERPNext which were installed using docker?
