### ISSUE TITLE
Tax is not adding to item in e-commerce 

### ISSUE THREAD

**Issue by Ulter52** [resilient-tech/india-compliance#1671]
### Information about bug

First, Item price is showing without taxes(excluding) and secondly even after adding to cart GST is not calculated and added to the item grand Total.

### Version

ERPNext: v14.x.x-develop () (develop)
Frappe Framework: v15.x.x-develop () (develop)
India Compliance: v16.0.0-dev (develop)
Payments: v0.0.1 (develop)
Webshop: v0.0.1 (develop)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by mumbaigirl** [comment]
@Ulter52 Here is the workaround . This is what worked for me 
https://github.com/resilient-tech/india-compliance/issues/1760 #1760

**Comment by Ulter52** [comment]
As @mumbaigirl said it works but after installing back india-compliance app, problem backs again. Still waiting for the resolution. 
![image](https://github.com/user-attachments/assets/804d6b62-1934-46d8-a1e5-6eb8071a7a46)
