### ISSUE TITLE
validate GSTIN status on autofill

### ISSUE THREAD

**Issue by vorasmit** [resilient-tech/india-compliance#168]
Under current auto-fill design, GSTIN status is not being validated although available.
Its very much possible that GSTIN is cancelled or inactive while a customer or supplier is being created.

## Proposed Solution

- Update description of GSTIN with the status of GSTIN when autofill is triggered.
- Warn user (with a message print) if status is anything other then active.

### Field before autofill

![image](https://user-images.githubusercontent.com/10496564/176984812-3ad04c65-cbd5-41bf-a5ed-bf54745e51fb.png)

### Field after autofill

![image](https://user-images.githubusercontent.com/54097382/176996863-f81738b1-3d0f-43da-99b8-a0cf0434205c.png)

**Comment by sagarvora** [comment]
- If inactive, status should be visible in red.
- Perhaps we should add `Status: `  before status, there isn't enough context.

**Comment by DaizyModi** [comment]
> * If inactive, status should be visible in red.
> * Perhaps we should add `Status: `  before status, there isn't enough context.

Done
