### ISSUE TITLE
UX: better error message for missing credentials

### ISSUE THREAD

**Issue by ankush** [resilient-tech/india-compliance#1749]
### Information about bug

![image](https://github.com/resilient-tech/india-compliance/assets/9079960/7b8db727-f019-4996-b205-7771086c8a62)

We can mention that it's missing for a specific company here. This can be confusing in multicompany setup

### Version

v14.24.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
This is raised from transactions, like Sales Invoice. And can only be one company and company GSTIN per transaction. Still added GSTIN for which credentials need to be added.
