### ISSUE TITLE
Not Working : View Tax Breakup Table Based On HSN Code

### ISSUE THREAD

**Issue by akashdubey22** [resilient-tech/india-compliance#1757]
### Information about bug

india_compliance version = 15.5.3

I have created custom invoice print format and using it since many years till v14. But yesterday after updating to v15..

View Tax Breakup Table Based On HSN Code - option on GST Setting is not working anymore so getting tax breakup based on items instead of HSN based.

This I replaced doc.other_charges_calculation with custom_gst_breakup_table

After above replacement, it worked on print preview but got the following error on actual print & PDF export.
{{ no such element: erpnext.accounts.doctype.sales_invoice.sales_invoice.SalesInvoice object['custom_gst_breakup_table'] }}

### Version

Frappe - 15.15.0
ERPNext - 15.14.6
India_compliance - 15.5.3

### Relevant log output / Stack trace / Full Error Message.

```shell
{{ no such element: erpnext.accounts.doctype.sales_invoice.sales_invoice.SalesInvoice object['custom_gst_breakup_table'] }}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Already fixed with #1734.
Should be released in a day or two.
