### ISSUE TITLE
Webshop not working with India Compliance

### ISSUE THREAD

**Issue by mumbaigirl** [resilient-tech/india-compliance#1760]
### Information about bug

Today, I removed the India Compliance app from my site, and what a relief! 
Now, I can use the webshop smoothly. Turns out, the India Compliance app doesn't work well with ERPNext v15 and the webshop. It's not a good idea for production use. Even though people have complained, the resilient-tech team hasn't done anything about it. 
If you're having trouble with the India Compliance app messing up your webshop, just get rid of it. Everything should work fine without it.

### Version

ERPNext: v15.14.6 (version-15)
Frappe Framework: v15.15.0 (version-15)
India Compliance: v15.5.3 (version-15)
Webshop: v0.0.1 (version-15)

### Relevant log output / Stack trace / Full Error Message.

```shell
All doctypes (including custom), modules related to this app will be deleted. Are you sure you want to continue? [y/N]: y
Backing up...
Removing Income Tax customizations...
Removing GST customizations...
Deleting Module 'Audit Trail'
* removing Report 'Audit Trail'...
* removing Module Def 'Audit Trail'...
Deleting Module 'VAT India'
* removing DocType 'C-Form'...
* removing DocType 'C-Form Invoice Detail'...
* removing Module Def 'VAT India'...
Deleting Module 'Income Tax India'
* removing Module Def 'Income Tax India'...
Deleting Module 'GST India'
* removing DocType 'e-Waybill Log'...
* removing DocType 'GST Settings'...
* removing DocType 'GSTR 3B Report'...
* removing DocType 'Bill of Entry'...
* removing DocType 'Bill of Entry Item'...
* removing DocType 'Purchase Reconciliation Tool'...
* removing DocType 'GST Credential'...
* removing DocType 'GST Inward Supply'...
* removing DocType 'GSTR Import Log'...
* removing DocType 'GSTIN'...
* removing DocType 'e-Invoice Log'...
* removing DocType 'GST UOM Map'...
* removing DocType 'e-Invoice Applicable Company'...
* removing DocType 'Bill of Entry Taxes'...
* removing DocType 'GST Account'...
* removing DocType 'GST Inward Supply Item'...
* removing DocType 'GST HSN Code'...
* removing Workspace 'GST India'...
* removing Report 'GST Advance Detail'...
* removing Report 'GSTR-3B Details'...
* removing Report 'GST Balance'...
* removing Report 'HSN-wise-summary of outward supplies'...
* removing Report 'Bill of Entry Summary'...
* removing Report 'e-Invoice Summary'...
* removing Report 'GSTR-1'...
* removing Report 'GST Purchase Register'...
* removing Report 'GST Sales Register'...
* removing Report 'GST Itemised Purchase Register'...
* removing Report 'GST Itemised Sales Register'...
* removing Page 'india-compliance-account'...
* removing Number Card 'Pending e-Waybill'...
* removing Number Card 'Pending e-Invoices'...
* removing Number Card 'Invoice Cancelled But Not e-Invoice'...
* removing Print Format 'e-Waybill'...
* removing Print Format 'e-Invoice'...
* removing Print Format 'GST Tax Invoice'...
* removing Print Format 'GST Purchase Invoice'...
* removing Print Format 'GST POS Invoice'...
* removing Module Def 'GST India'...
* dropping Table for 'Bill of Entry'...
* dropping Table for 'GST UOM Map'...
* dropping Table for 'C-Form'...
* dropping Table for 'Bill of Entry Item'...
* dropping Table for 'C-Form Invoice Detail'...
* dropping Table for 'GST Inward Supply Item'...
* dropping Table for 'GST Account'...
* dropping Table for 'GST HSN Code'...
* dropping Table for 'GSTR 3B Report'...
* dropping Table for 'e-Invoice Applicable Company'...
* dropping Table for 'e-Waybill Log'...
* dropping Table for 'e-Invoice Log'...
* dropping Table for 'GST Inward Supply'...
* dropping Table for 'GSTR Import Log'...
* dropping Table for 'GST Credential'...
* dropping Table for 'Bill of Entry Taxes'...
* dropping Table for 'GSTIN'...
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Duplicate #1667

**Comment by vorasmit** [comment]
We appreciate fixes and contributions from all community members.

You can follow the guidelines provided here:
https://github.com/resilient-tech/india-compliance#contributing

If you are very sure this issue is with the India Compliance app, Share a complete traceback. It could likely be with webshop app or your configuration.

---
If you want us to prioritise your issues or bugs, you should consider sponsored development / taking up a support plan.

**Comment by mumbaigirl** [comment]
@vorasmit No need to pay for the app if it's not matured enough to be used for production .Wish , I knew earlier that the issue  was India Compliance Module. I thought , its an error from ERPNext. You are already sponsored and funded by Frappe , aren't you then why to beg here?

**Comment by vorasmit** [comment]
You are please welcome with constructive issues.

Catchy issue title to grab attention and rant about the efforts of members of the community are against the guidelines and appropriate action will be taken if not followed.
https://github.com/frappe/erpnext/wiki/Issue-Guidelines#bug-report-guidelines

**Comment by mumbaigirl** [comment]
@vorasmit  Your perspective sheds light on the importance of maturity, wish you could learn too how important it is for an app to be matured.

**Comment by sagarvora** [comment]
> are already sponsored and funded by Frappe

Yes, but why should that concern you? Are you from Frappe or have you invested there? Not that we are required to inform you, but that funding was exhausted in the same year we received it.

And I would like to appreciate your confidence. After all how else can someone talk about maturity after equating sponsoring a FOSS app with begging.
