### ISSUE TITLE
Error while migrating the site.

### ISSUE THREAD

**Issue by sjain17** [resilient-tech/india-compliance#1801]
### Information about bug

File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 19, in create_company_fixtures
    create_or_update_tax_withholding_category(company)
      company = 'Demo Company'
  File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 49, in create_or_update_tax_withholding_category
    doc.insert(ignore_if_duplicate=True)
      company = 'Demo Company'
      accounts = []
      abbr = 'DC'
      tds_account = None
      categories = [{'name': 'TDS - 194C - Company', 'category_name': 'Payment to Contractors (Single / Aggregate)', 'doctype': 'Tax Withholding Category', 'accounts': [], 'tds_section': '194C', 'entity_type': 'Company', 'round_off_tax_amount': 0, 'consider_party_ledger_amount': 0, 'tax_on_excess_amount': 0, 'rates': [{'from_date': '2023-04-01', 'to_date': '2024-04-01', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}, {'from_date': '2024-04-01', 'to_date': '2025-03-31', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}]}, {'name': 'TDS - 194C - Individual', 'category_name': 'Payment to Contractors (Single / Aggregate)', 'doctype': 'Tax Withholding Category', 'accounts': [], 'tds_section': '194C', 'entity_type': 'Individual', 'round_off_tax_amount': 0, 'consider_party_ledger_amount': 0, 'tax_on_excess_amount': 0, 'rates': [{'from_date': '2023-04-01', 'to_date': '2...
      category_doc = {'name': 'TDS - 194C - Company', 'category_name': 'Payment to Contractors (Single / Aggregate)', 'doctype': 'Tax Withholding Category', 'accounts': [], 'tds_section': '194C', 'entity_type': 'Company', 'round_off_tax_amount': 0, 'consider_party_ledger_amount': 0, 'tax_on_excess_amount': 0, 'rates': [{'from_date': '2023-04-01', 'to_date': '2024-04-01', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}, {'from_date': '2024-04-01', 'to_date': '2025-03-31', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}]}
      existing_category_name = None
      doc = <TaxWithholdingCategory: TDS - 194C - Company>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 286, in insert
    self._validate()
      self = <TaxWithholdingCategory: TDS - 194C - Company>
      ignore_permissions = None
      ignore_links = None
      ignore_if_duplicate = True
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 568, in _validate
    self._validate_mandatory()
      self = <TaxWithholdingCategory: TDS - 194C - Company>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 904, in _validate_mandatory
    raise frappe.MandatoryError(
      self = <TaxWithholdingCategory: TDS - 194C - Company>
      missing = [('accounts', 'Error: Data missing in table: Accounts')]
      d = <TaxWithholdingRate: c27acc1718 parent=TDS - 194C - Company>
      idx = 'accounts'
      msg = 'Error: Data missing in table: Accounts'
frappe.exceptions.MandatoryError: [Tax Withholding Category, TDS - 194C - Company]: accounts

### Version

ERPNext: v15.14.4 (HEAD)
Frappe Framework: v15.15.0 (HEAD)
Frappe HR: v15.12.0 (HEAD)
India Compliance: v15.5.1 (HEAD)
Payments: v0.0.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 19, in create_company_fixtures
    create_or_update_tax_withholding_category(company)
      company = 'Demo Company'
  File "/home/frappe/frappe-bench/apps/india_compliance/india_compliance/income_tax_india/overrides/company.py", line 49, in create_or_update_tax_withholding_category
    doc.insert(ignore_if_duplicate=True)
      company = 'Demo Company'
      accounts = []
      abbr = 'DC'
      tds_account = None
      categories = [{'name': 'TDS - 194C - Company', 'category_name': 'Payment to Contractors (Single / Aggregate)', 'doctype': 'Tax Withholding Category', 'accounts': [], 'tds_section': '194C', 'entity_type': 'Company', 'round_off_tax_amount': 0, 'consider_party_ledger_amount': 0, 'tax_on_excess_amount': 0, 'rates': [{'from_date': '2023-04-01', 'to_date': '2024-04-01', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}, {'from_date': '2024-04-01', 'to_date': '2025-03-31', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}]}, {'name': 'TDS - 194C - Individual', 'category_name': 'Payment to Contractors (Single / Aggregate)', 'doctype': 'Tax Withholding Category', 'accounts': [], 'tds_section': '194C', 'entity_type': 'Individual', 'round_off_tax_amount': 0, 'consider_party_ledger_amount': 0, 'tax_on_excess_amount': 0, 'rates': [{'from_date': '2023-04-01', 'to_date': '2...
      category_doc = {'name': 'TDS - 194C - Company', 'category_name': 'Payment to Contractors (Single / Aggregate)', 'doctype': 'Tax Withholding Category', 'accounts': [], 'tds_section': '194C', 'entity_type': 'Company', 'round_off_tax_amount': 0, 'consider_party_ledger_amount': 0, 'tax_on_excess_amount': 0, 'rates': [{'from_date': '2023-04-01', 'to_date': '2024-04-01', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}, {'from_date': '2024-04-01', 'to_date': '2025-03-31', 'tax_withholding_rate': 2, 'single_threshold': 30000, 'cumulative_threshold': 100000, 'doctype': 'Tax Withholding Rate'}]}
      existing_category_name = None
      doc = <TaxWithholdingCategory: TDS - 194C - Company>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 286, in insert
    self._validate()
      self = <TaxWithholdingCategory: TDS - 194C - Company>
      ignore_permissions = None
      ignore_links = None
      ignore_if_duplicate = True
      ignore_mandatory = None
      set_name = None
      set_child_names = True
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 568, in _validate
    self._validate_mandatory()
      self = <TaxWithholdingCategory: TDS - 194C - Company>
  File "/home/frappe/frappe-bench/apps/frappe/frappe/model/document.py", line 904, in _validate_mandatory
    raise frappe.MandatoryError(
      self = <TaxWithholdingCategory: TDS - 194C - Company>
      missing = [('accounts', 'Error: Data missing in table: Accounts')]
      d = <TaxWithholdingRate: c27acc1718 parent=TDS - 194C - Company>
      idx = 'accounts'
      msg = 'Error: Data missing in table: Accounts'
frappe.exceptions.MandatoryError: [Tax Withholding Category, TDS - 194C - Company]: accounts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
closed by: #1793
