### ISSUE TITLE
Debit Note not showing in GSTR-1 report

### ISSUE THREAD

**Issue by lato-tech** [resilient-tech/india-compliance#1803]
Hi,

I had created a Debit Note last month and it has not been reported in the GSTR-1 report of that month.

Kindly look into it and please resolve this issue.

Thanks.

**Comment by vorasmit** [comment]
Did you check the relevant filter of GSTR-1?
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/368af203-5501-4fce-bb60-761fcc69902a)

What is the category of Transaction? B2B or B2CS or B2CL?
For B2CS, only net sales are required to be reported in sec 7 of GSTR-1.

**Comment by lato-tech** [comment]
I am attaching a few screenshots for your reference. Please note that the Credit notes made against Sales Invoices are visible in the report whereas, the Debit Notes created against Purchase Invoices are not visible.
![GSTR-1](https://github.com/resilient-tech/india-compliance/assets/129725214/b292a03f-2f08-4a10-8a7f-32d3d33460bb)
![Purchase Invoice List](https://github.com/resilient-tech/india-compliance/assets/129725214/8c8e1258-fd5f-45cf-ad74-135b727c038b)
![Sales Invoice List](https://github.com/resilient-tech/india-compliance/assets/129725214/93eb28f5-5322-42a1-8a2e-f57271374c50)

**Comment by vorasmit** [comment]
Debit notes against purchase invoices are **not** required to be reported in GSTR-1.

Debit notes if created from Sales Invoice are only required to be reported in GSTR-1.
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/b4aa0639-1a49-499c-91cc-983edcf7e396)

**Comment by lato-tech** [comment]
Hi,

1. How will I upload my Debit Notes to the GST Portal? It is mandatory to upload all the Debit Notes on portal.
2. Debit notes are created against Purchases of a company and not Sales. Sales are as you know are already Debit transactions.
3. Why are the Credit Notes being shown in GSTR-1 report then? The logic should be same for both types of documents.

Thanks in advance.


![Purchase Debit Note](https://github.com/resilient-tech/india-compliance/assets/129725214/7c314adb-dcee-45d6-a2e7-171b4fde5aa3)

**Comment by lato-tech** [comment]
Hi, any update?

**Comment by vorasmit** [comment]
As specified before,

Debit notes from Purchase Invoice are not required to be reported in GSTR-1.
Please consult your CA for more details.

**Comment by lato-tech** [comment]
Hi,
Thanks for the update. I have confirmed with my CA and they are saying we do not have an option to upload the Purchase Debit notes to GSTR-1. Only the tax amount needs to be adjusted in GSTR-3B filing.
Regards.
