### ISSUE TITLE
PR to PI Flow with Debit Note ( No validation ) | Multiple Taxes Adding in PI 

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#1820]
### Information about bug

Purchase Receipt

item- Glass
Qty - 1000
Rate  - 100

<img width="1050" alt="Screenshot 2024-03-06 at 1 25 47 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/a916eddd-a5ee-4157-ba02-fc7c7ec5ce38">

PI for the above PR 

1. Tax issue

https://github.com/resilient-tech/india-compliance/assets/21578167/a7ae96a8-cc96-41ee-a6a7-e8ed2c53f7b0

2. Invoice Booked - PR in Completed

3. Debit note against PI 20 each qty  | PR Billed amount Updated - Says partially billed

4. Again I can make the PI against the same PR for the full amount.

https://github.com/resilient-tech/india-compliance/assets/21578167/44e82631-5f12-49c9-88dd-13fb7bd53b10

### Version

ERPNext: v15.16.0 (version-15)

Frappe Framework: v15.17.0 (version-15)

Frappe HR: v15.12.0 (version-15)

India Compliance: v15.5.6 (version-15)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dineshpanchal93** [comment]
v14 also have same issue

**Comment by vorasmit** [comment]
![image](https://github.com/resilient-tech/india-compliance/assets/10496564/90676985-809d-4a37-b604-74958cb5fb99)

Is this setting enabled for you?
- Automatically add taxes and charges from the Item Tax Template?

**Comment by dineshpanchal93** [comment]
@vorasmit  

No its not enabled

<img width="837" alt="Screenshot 2024-03-06 at 9 30 30 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/90b7f147-dd2a-4faf-a3c9-939163f218f4">

**Comment by dineshpanchal93** [comment]
@vorasmit Is Another PR to PI  validation a bug or it's a new flow in ERPNext

**Comment by vorasmit** [comment]
For 2nd scenario, If you don't intend to book PI after booking returns, you should not check `update billed amount in purchase receipt`.

However, this seems to be a new development with ERPNext.
2nd part is not related to India compliance

**Comment by vorasmit** [comment]
Can you execute the following command in the bench directory?
It should most likely help resolve the issue with respect to taxes:

```
bench execute india_compliance.gst_india.setup.set_default_accounts_settings
```
