### ISSUE TITLE
On Sales Invoice GST Tax calculation is Correct but Still showing '0' in 'Tax Rate' Coloumn.

### ISSUE THREAD

**Issue by Sunitsarode** [resilient-tech/india-compliance#1881]
I m creating Sales Invoice 
Here I notified that GST Tax calculation of Items are Correct but Still showing **'0'** in **'Tax Rate'** Coloumn.

![image](https://github.com/resilient-tech/india-compliance/assets/124702553/5fd1ee11-38ec-41fc-9b32-bbc87bcdd5ba)

I searched a lot but didnt get any solution. I noticed that After installing India-Compliance the Tax Setting option is Overridden by India Compliance. And It has disabled the option for item taxation : Automatically Add Taxes and Charges from Item Tax Template

![image](https://github.com/resilient-tech/india-compliance/assets/124702553/38e8f87e-b9f9-48eb-9e8e-578ada5d1b96)

 Please help to resolve this issue.

Thanks
Sunit

**Comment by ljain112** [comment]
You may have set the Item Wise Tax Template.
Taxes are calculated from the ITem Wise Tax Template defined in Item.

If the No Item Tax template is selected in Items then Rate in Taxes row is used for calculation.

https://docs.erpnext.com/docs/user/manual/en/item-tax-template

**Comment by Sunitsarode** [comment]
Hi 
Thanks for reply.

I have already done above setting given by you, though tax calculation is correct but Still showing '0' in 'Tax Rate' Coloumn.

I have attached more screenshot here...

 Item Tax Template : 
![image](https://github.com/resilient-tech/india-compliance/assets/124702553/83296ac3-e694-4305-a89f-41908617bb10)


GST 5% Setting :
![image](https://github.com/resilient-tech/india-compliance/assets/124702553/564b7cd0-61eb-4ff9-b704-f06e45ae3b26)

**Comment by Sunitsarode** [comment]
> You may have set the Item Wise Tax Template. Taxes are calculated from the ITem Wise Tax Template defined in Item.
> 
> If the No Item Tax template is selected in Items then Rate in Taxes row is used for calculation.
> 
> https://docs.erpnext.com/docs/user/manual/en/item-tax-template

Hi 
please help this issue

**Comment by ljain112** [comment]
The tax rate field in taxes is for the default tax rate(if no tax template is selected in the item this rate is charged) and it is fetched from the Taxes and Charges Template. You should check whether the tax amount is correct or not.

You can also see the tax breakup to check the applied tax rate.

![image](https://github.com/resilient-tech/india-compliance/assets/108322669/7c3df948-d71c-47fb-ad74-18f7e7ca065a)
![image](https://github.com/resilient-tech/india-compliance/assets/108322669/b07ed751-6f41-440c-b856-90a0ca3050dd)
![image](https://github.com/resilient-tech/india-compliance/assets/108322669/9f1803f3-9f04-4d17-ab87-0093c6775353)

**Comment by Sunitsarode** [comment]
Thanks a lot Lakshit for your help.
I would like to suggest to India-Compliance that it would be more helpful for user if we able to show tax rate as well. 
Gratitude

**Comment by ljain112** [comment]
There is no specific way to show tax rates in the taxes table because there can be multiple tax rates for the same account in an invoice.
We are already setting gst tax in the item table and gst breakup table can be used for gst tax breakup.

![image](https://github.com/resilient-tech/india-compliance/assets/108322669/0a17ac01-dd52-4278-bb29-8a2cb1d9e7e4)
