### ISSUE TITLE
While extracting `address_line2` for GSTIN info, avoid duplicates

### ISSUE THREAD

**Issue by sagarvora** [resilient-tech/india-compliance#1917]
Line of code:
https://github.com/resilient-tech/india-compliance/blob/d5a5f7cd7f789fb042baaea0efe8c9372a8febeb/india_compliance/gst_india/utils/gstin_info.py#L134

Example:

![image](https://github.com/resilient-tech/india-compliance/assets/16315650/58127958-34d3-4e23-ad0e-cf2bf4c48760)

(fix also required in apim)

**Comment by vorasmit** [comment]
Looks like the problem is with original data source. It's reported with duplicate values to govt.
I suppose we should not alter this, as we do give option to edit.
