### ISSUE TITLE
GSTR 1 Report Not Showing Zero-Rated Value

### ISSUE THREAD

**Issue by creative-paramu** [resilient-tech/india-compliance#1974]
### Information about bug

We Create a Sales Invoice With Zero Rated and Taxable GST Treatment, It is a B2B Bill, After Submit the Sales Invoice We Will Check the GSTR 1 Report The Zero Rated Value Not Showing Only the Taxable Value Showing,

Here I attach The Invoice, Item Tax Template and Report Images
![Screenshot from 2024-04-03 21-59-17](https://github.com/resilient-tech/india-compliance/assets/101092028/3cc93c5d-5fe8-48a5-aabc-1a4db07c4ff3)
![Screenshot from 2024-04-03 21-59-42](https://github.com/resilient-tech/india-compliance/assets/101092028/b2a4b4a2-48be-498b-b867-fb6da430ceb9)
![Screenshot from 2024-04-03 22-03-50](https://github.com/resilient-tech/india-compliance/assets/101092028/302f977d-a8c0-4672-958e-51625ae90c50)
![Untitled design(1)](https://github.com/resilient-tech/india-compliance/assets/101092028/950113e9-f8bf-4c73-84e5-95ebc1e98b86)

### Version

ERPNext: v15.18.3

Frappe Framework: v15.19.1

Frappe HR: v15.15.0

India Compliance: v15.7.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
How are you seeing option of Zero-Rated in Item Tax Template?
This is not allowed. Looks like you have messed up with the configuration.

I'll soon add link to documentation on how these things work.

**Comment by creative-paramu** [comment]
I Was Customize Item Tax Template GST Treatment Sir,

**Comment by ljain112** [comment]
> I Was Customize Item Tax Template GST Treatment Sir,

This is not how Zero-Rated works in India Compliance App.
If the transaction is Export or supplies to SEZ, the GST treatment is set to Zero-Rated for all items.

You can refer to this blog:
https://docs.indiacompliance.app/blog/posts/post3#how-are-these-treatments-handled-in-the-india-compliance-app
