### ISSUE TITLE
[bug] Purchase invoice supplier GSTIN validation if overseas supplier

### ISSUE THREAD

**Issue by ishanloya** [resilient-tech/india-compliance#198]
Currently, the `is_inter_state` variable is set to get supplier_gstin[:2] in line 214 of transaction.py under overrides. When the purchase is made from an overseas supplier, this causes an error since the supplier GSTIN may be blank in this case.

TypeError: 'NoneType' object is not subscriptable

**Comment by sagarvora** [comment]
Hello,

Thanks for testing this app out early and reporting this issue.
We already flagged this internally and it has been fixed in https://github.com/resilient-tech/india-compliance/pull/179/.

It will be merged shortly.

**Comment by ishanloya** [comment]
Great! Thanks
