### ISSUE TITLE
Sales invoice page load fails when directly opening page

### ISSUE THREAD

**Issue by ankush** [resilient-tech/india-compliance#203]
Steps to reproduce:
1. open sales invoice
2. force refresh / copy URL and open in another tab.

This is quite likely because of order in which JS is loaded. 

```
sentry.bundle.6RRZBTNB.js:5 TypeError: Cannot read properties of undefined (reading 'is_api_enabled')
    at eval (sales_invoice__list_js:46:24)
    at Object.init_doctype (desk.bundle.SOVF7K6A.js:1:5730)
    at Object.callback (desk.bundle.SOVF7K6A.js:1:5483)
    at Object.e [as success_callback] (desk.bundle.SOVF7K6A.js:488:1208)
    at 200 (desk.bundle.SOVF7K6A.js:488:1775)
    at Object.<anonymous> (desk.bundle.SOVF7K6A.js:488:4907)
    at R (libs.bundle.MWSF4VQZ.js:1:30299)
    at Object.fireWith [as resolveWith] (libs.bundle.MWSF4VQZ.js:1:31091)
    at Oe (libs.bundle.MWSF4VQZ.js:4:6046)
    at XMLHttpRequest.<anonymous> (libs.bundle.MWSF4VQZ.js:4:8531)
    at XMLHttpRequest.i (sentry.bundle.6RRZBTNB.js:14:9773)
```

https://github.com/resilient-tech/india-compliance/blob/66f4acfb77d523a8969d8be85d5a441691640a33/india_compliance/gst_india/client_scripts/e_waybill_actions.js#L1

**Comment by ankush** [comment]
@sagarvora

**Comment by vorasmit** [comment]
Its not able to load IC, which is defined in the public > gst_india > utils.
Make sure this file is getting loaded. Probably bench build could solve this.

Please let us know if this is still an issue. I could not replicate this.

**Comment by sagarvora** [comment]
there's another reason to fix this:
we don't want the constants to stay same if API is no longer enabled because of change in GST settings.

but then we might need a page refresh anyway.. because we use this in setup events which only get called once AFAIK.

**Comment by sagarvora** [comment]
https://github.com/resilient-tech/india-compliance/commit/aaa495ce0d0c86b21a1c882a84046d4daaf781d2

**Comment by ankush** [comment]
This still happens btw! (versions: latest `develop` everything)

```
Uncaught (in promise) TypeError: ic.is_e_invoice_enabled is not a function
    onload sales_invoice__list_js:805
    setup_view list_view.js:294
    promise callback*frappe.run_serially/< dom.js:269
    run_serially dom.js:267
    init base_list.js:35
    show base_list.js:14
    promise callback*frappe.run_serially/< dom.js:269
    run_serially dom.js:267
    show base_list.js:9
    show list_view.js:36
    <anonymous> list_view.js:26
    make list_factory.js:30
    show factory.js:25
    render_page router.js:303
    render router.js:282
    route router.js:147
    set_route desk.js:176
    startup desk.js:86
    <anonymous> desk.js:30
    start_app desk.js:12
    <anonymous> desk.js:25
    jQuery 2
    i helpers.ts:95
    setTimeout handler*Dn/< trycatch.ts:121
    jQuery 11
    pe libs.bundle.LZZGUWMT.js:1
    <anonymous> jQuery
    <anonymous> libs.bundle.js:9
```

**Comment by ankush** [comment]
@sagarvora it's conflicting with minified code randomly :woozy_face: 


![image](https://user-images.githubusercontent.com/9079960/215978822-2bb22181-d9d6-4848-8fde-26a2927e981c.png)


Can you please reopen this?

**Comment by ankush** [comment]
@sagarvora lets just use longer name for `ic` and keep alias for backward compat.
