### ISSUE TITLE
Issu In GSTR 3B

### ISSUE THREAD

**Issue by mmplerp** [resilient-tech/india-compliance#2035]
GSTR 3b not match 
![Capture](https://github.com/resilient-tech/india-compliance/assets/166016033/6ae2aca8-cf2c-4ca6-ba42-49b8754afa20)
We check all invoice of nil rate nothing here but report show 5 lakhs amount

**Comment by vorasmit** [comment]
Duplicate #1630 .
We'll soon address this.

**Comment by mmplerp** [comment]
Sir we have to fill return 
Please do this fast 
If you want to contact us you can
