### ISSUE TITLE
HR Based compliances?

### ISSUE THREAD

**Issue by nautatva** [resilient-tech/india-compliance#2042]
### Is your feature request related to a problem? Please describe.

There are a lot of forms which needs to be submitted to the government as a part of HR compliances.
- Form-14
- Form-16
- Form-18
- PF, ESIC, LWF & other statutory compliance

Any plans to develop these? I have a structure in mind, but want to check on roadmap of this.

### Describe the solution you'd like

I am thinking on adding a template which can be taken out as PDF with Print button

**Comment by vorasmit** [comment]
This is missing and is nice to have.

Currently India Specific HR code is still part of HRMS app. When existing compliances are well met, we can migrate them to this app and maintain it side by side.

Best to create a detailed issue with proposal on how you plan to implement this in [HRMS App](https://github.com/frappe/hrms/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)

**Comment by nautatva** [comment]
Raised a feature request with https://github.com/frappe/hrms/issues/1684
