### ISSUE TITLE
While installing it is getting an error

### ISSUE THREAD

**Issue by rehandev26** [resilient-tech/india-compliance#2043]
### Information about bug

![image](https://github.com/resilient-tech/india-compliance/assets/165145630/26ace85b-ce5f-44eb-8e6f-97f33a8bc9a5)

### Version

frappe v15.23.0
erpnext v15.20.3
india_compliance v15.7.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Duplicate:

#1911 #1872 #1831 etc..

Please refer these issues.
