### ISSUE TITLE
Default RCM Taxes Setting Issue

### ISSUE THREAD

**Issue by BHAGYASHRIMHASKE** [resilient-tech/india-compliance#2044]
### Information about bug

In default RCM Taxes there is issue system showing Input GL Debit & Input RCM GL Credit. How its accounting effect correct?

As RCM Input Tax setup we required Input RCM GL Debit & Output RCM GL Credit. If we go through current setting its going wrong GL effect. We are trying to changing GST setting GL but its not allow to add multiple RCM GL

<img width="705" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/138584686/c1f2cbd6-1c82-46c7-bd3f-fa769112a1aa">

Also showing Input RCM GL in Liabilities side
<img width="345" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/138584686/09a672bc-8a32-4b5e-a699-346999cbae98">

### Version

ERPNext: v15.20.3
Frappe Framework: v15.22.0
India Compliance: v15.7.2
Payments: v0.0.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Hi,

RCM account is credit balance, as it's the liability of business to pay to government. Whereas, Input is asset hence debit balance.
You can change the grouping of account easily if required by editing chart of accounts for existing account. (if your CA suggests this to be dealt with differently)

**Comment by vorasmit** [comment]
Hi,

You may comment here as well instead of creating the new issue.
It's as easy as changing parent account and the grouping can be changed.

![image](https://github.com/resilient-tech/india-compliance/assets/10496564/ae069939-42e2-46d1-87e3-ae4548f70305)

**Comment by BHAGYASHRIMHASKE** [comment]
Hi @vorasmit as you said I have changed Parent Account and set taxes as per Our CA required i.e Input RCM Tax Debit & Output RCM Tax Credit but system doesn't allow both GL in RCM Taxes & also in GST Setting multiple RCM GL not allow.
So can you help us how we can convey to client and setup RCM tax??
