### ISSUE TITLE
Hi, @vorasmit  Thanks for reply. As you said I have tried to setup RCM as we required as per our CA but system doesn't allow to add Input RCM GL In debit & Output RCM GL in Credit side. So how we can handle this Scenario, In GST Setting there is no provision to add multiple RCM GL??? 

### ISSUE THREAD

**Issue by BHAGYASHRIMHASKE** [resilient-tech/india-compliance#2053]
Hi,

RCM account is credit balance, as it's the liability of business to pay to government. Whereas, Input is asset hence debit balance.
You can change the grouping of account easily if required by editing chart of accounts for existing account. (if your CA suggests this to be dealt with differently)

_Originally posted by @vorasmit in https://github.com/resilient-tech/india-compliance/issues/2044#issuecomment-2063561945_

**Comment by vorasmit** [comment]
duplicate #2044
