### ISSUE TITLE
India Compliance page is blank

### ISSUE THREAD

**Issue by karthikkangokar** [resilient-tech/india-compliance#2085]
### Information about bug

India Compliance is blank on self hosting

### Version

Frappe version - 15.20.6
ErpNext Version - 15.20.6

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Are your JS assets built correctly? Did you run bench build?

Kindly share traceback.
Traceback is the Error traceback. Press F12 in the browser when receiving the error. You'll see an error traceback in the console. You need to share that, for us to inspect the origin of the error.

**Comment by vorasmit** [comment]
Can be re-opened when actual issue is know. Currently we are not able to replicate this.

**Comment by bkvaiude** [comment]
@ljain112 @vorasmit 

I'm facing simillar issue, where after successful india-compliance installation, I see blank page.

Expectation is I suppose to see the sign up page

Please take look at attached screen for error details in console

![image](https://github.com/user-attachments/assets/b5fbc210-2cff-4543-9196-399d18b10c4e)

Let me know what am I missing here

**Comment by mohsinalimat** [comment]
I am also facing same issue but i used below command

bench build and bench site migrate

**Comment by bkvaiude** [comment]
@vorasmit @ljain112 
Here are the more logs, I suspect that following file linking issue creating a problem here!

$ bench build --app india_compliance
[Errno 18] Invalid cross-device link: 'tmpc18d7298857c3ddc3f6a846ed9ae7a6cc1eabba199229b87314b9760' -> './assets/frappe'                                                                                   
Cannot link /home/frappe/frappe-bench/apps/frappe/frappe/public to ./assets/frappe                                                                                                                         
[Errno 2] No such file or directory: 'tmp0197a643c40da77e454a782f0246c819118a8c25621cfdaff66d7866' -> './assets/frappe/node_modules'                                                                       
Cannot link /home/frappe/frappe-bench/apps/frappe/node_modules to ./assets/frappe/node_modules                                                                                                             
[Errno 18] Invalid cross-device link: 'tmpbf36903ebb97585126705cee9dac27587097c305c2fc22b2f834c05a' -> './assets/erpnext'                                                                                  
Cannot link /home/frappe/frappe-bench/apps/erpnext/erpnext/public to ./assets/erpnext                                                                                                                      
[Errno 2] No such file or directory: 'tmp3cc62006798fee692618cd4c46d8bf006ac6846b12ea4d53838c0aa0' -> './assets/erpnext/node_modules'                                                                      
Cannot link /home/frappe/frappe-bench/apps/erpnext/node_modules to ./assets/erpnext/node_modules                                                                                                           
[Errno 18] Invalid cross-device link: 'tmpb0b14b4479ede09e050c790d28a49aa51bc00c098fda6e188e97065f' -> './assets/india_compliance'                                                                         
Cannot link /home/frappe/frappe-bench/apps/india_compliance/india_compliance/public to ./assets/india_compliance                                                                                           
✔ Application Assets Linked        



@mohsinalimat I tried bench build manually after successful install of india_compliance, but it is giving following issue

https://github.com/frappe/erpnext/issues/38888
