### ISSUE TITLE
 Report for On A/c Payment but it is not settled against any Sales Invoice

### ISSUE THREAD

**Issue by JitendraSAW** [resilient-tech/india-compliance#2091]
### Is your feature request related to a problem? Please describe.

Hello Frappe Team

How to get a Report for On A/c Payment but it is not settled against any Sales Invoice or any JV Partywise, so that for that Party we can run the Payment Reconciliation Tool.

We cannot check manually one to one apty, so how we can get all party wise, where the SI is Open and Payments are done on A/c (not Settled) against them.

**Comment by ljain112** [comment]
Hello @JitendraSAW ,

This report is not related to India Compliance App.
Kindly open this request in https://github.com/frappe/erpnext/
