### ISSUE TITLE
Legal Name update when creating customer / supplier

### ISSUE THREAD

**Issue by bhavyajicomputers** [resilient-tech/india-compliance#2092]
### Is your feature request related to a problem? Please describe.

I please do needful so that the legal name of business  is also fetched and updated when new supplier / customer is created. at present trade name is updated.   for proprietor firms these two are not same.
Legal is required in TDS returns.

### Describe the solution you'd like

A new field required to have legal name of party

### Additional context

{
	"erpnext": "14.68.2",
	"frappe": "14.72.0",
	"hrms": "14.26.2",
	"india_compliance": "14.26.4"
}

**Comment by vorasmit** [comment]
It's not mandatory to match name in PAN when filing TDS Returns. Name is just for the internal reference of user.
Hence you may file the TDS return with tradename and that should not be an issue.

Since this is not a requirement, closing this for now. Can be reopened when this is legally required.
