### ISSUE TITLE
Error New Supplier / Customer Creation

### ISSUE THREAD

**Issue by bhavyajicomputers** [resilient-tech/india-compliance#2100]
Thanks

**Comment by vorasmit** [comment]
Fix was created and merged yesterday.
It's released just now. You may update the app. Check if error persists after update.

**Comment by bhavyajicomputers** [comment]
update not available for sites using  frappe cloud

**Comment by bhavyajicomputers** [comment]
till now update not available on frappe cloud v15

**Comment by vorasmit** [comment]
If you are on a shared bench, the update will come within a week's time.
In case you are on a private bench, you should be able to update the bench immediately.

You may contact FC support if you wish to have a faster update.
