### ISSUE TITLE
Sales Taxes and Charges Not created in sale invoice

### ISSUE THREAD

**Issue by Nora-Aurora** [resilient-tech/india-compliance#2107]
### Information about bug

I want to create item-wise taxing. I added an item tax template in the Tax tab of the item. However, when creating an invoice, the item fetches the item tax template but it's not showing in the Sales Taxes and Charges table on the invoice. I have attached the photos.

https://github.com/resilient-tech/india-compliance/assets/88709098/992feacd-b487-4e9b-a2a6-da532ed1c9bd
in item
<img width="953" alt="Screenshot 2024-05-09 at 1 52 58 AM" src="https://github.com/resilient-tech/india-compliance/assets/88709098/19f45958-f2e2-4122-8c11-4e9c2c77bd13">
in item tax template
<img width="951" alt="Screenshot 2024-05-09 at 1 52 17 AM" src="https://github.com/resilient-tech/india-compliance/assets/88709098/c04506e3-a690-4d39-b482-d60b6101a60c">

### Version

ERPNext: v15.21.2 (version-15)

Frappe Framework: v15.24.1 (version-15)

Healthcare: v14.0.3 (version-14)

India Compliance: v15.7.4 (version-15)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
You will need the Sales Taxes and Charges Template.
Taxes will be charged on the basis of accounts specified in the Taxes Table.
