### ISSUE TITLE
No Einvoice API Enable Option 

### ISSUE THREAD

**Issue by sumeetagra** [resilient-tech/india-compliance#212]
After migration from V13 to v14, there is not option available to enable EInvoice Applicability nor Einvoice Applicable date option nor credentials menu is visible.

Attached photographs
![Screenshot 2022-08-06 at 11 12 42 AM](https://user-images.githubusercontent.com/19186564/183235916-9bf4e8eb-9f43-488d-a4c0-d72f9d565219.png)
.

**Comment by sagarvora** [comment]
Hello,

Thanks for your interest. We haven't enabled in-app API subscription services yet - these are essential for enabling the e-Invoice integration. However, these can be enabled by setting the API key in a site config. Please email _hello at indiacompliance dot app_ and we will share a trial API key and the relevant instructions with you.

The in-app API subscription service is expected to be released in a couple of days.
