### ISSUE TITLE
India Compliance Account - option not visible in GST Settings page

### ISSUE THREAD

**Issue by shbkrm** [resilient-tech/india-compliance#2124]
### Information about bug

India Compliance Account Option is missing in the GST Settings page.
Am using ERPNext hosted on frappe cloud.

### Version

![image](https://github.com/resilient-tech/india-compliance/assets/9065106/f66f1e6e-6567-4b53-a51a-83ef10304420)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Frappecloud comes bundled with India Compliance API features and hence India Compliance Account won't be accessible there.
You don't need to purchase API Credits.

**Comment by shbkrm** [comment]
How do I create API Credentials for e-Invoicing?

**Comment by ljain112** [comment]
You can refer to Documentation:
https://docs.indiacompliance.app/docs/ewaybill-and-einvoice/generating_e_invoice
