### ISSUE TITLE
Credit notes from Sales Invoices not showing in Purchase Reconciliation Tool

### ISSUE THREAD

**Issue by lato-tech** [resilient-tech/india-compliance#2134]
Hi,

I have been using PRT for the past month. I have not been able to reconcile / link Credit Notes created from Sales Invoices. Is this functionality not available or am I not able to find it? I can only see Purchase Invoice and Bill of Entry in Document Type text field.
![Screenshot 2024-05-18 172634](https://github.com/resilient-tech/india-compliance/assets/129725214/75d78bdb-0140-49b7-abcf-b4069ca4fc52)

I tried searching for similar issues here but was not able to find it.

Your prompt response will be highly appreciated.

**Comment by ljain112** [comment]
Credit Notes from Sales Invoices are for Sales Return.
Sales Return are not part of GSTR 2A/2B

Only Purchase Document info is available in GSTR 2A/2B.

To book a purchase return (Debit-Note) you have to book a transaction in Purchase Doctype.
Debit Note is raised by the supplier.
https://docs.erpnext.com/docs/user/manual/en/debit-note
