### ISSUE TITLE
Line Item showing 'Missing in PI' and 'Accept My Values'

### ISSUE THREAD

**Issue by lato-tech** [resilient-tech/india-compliance#2146]
### Information about bug

Hi,
I am attaching the screenshot of the possible bug. The same entry is showing Missing in PI and Accept My Values, which is contradictory.

![Screenshot 2024-05-20 201122](https://github.com/resilient-tech/india-compliance/assets/129725214/734cdb8b-227c-484c-a64f-c33328e866b1)

### Version

ERPNext: v15.22.2 (version-15)
Frappe Framework: v15.25.0 (version-15)
India Compliance: v15.7.4 (version-15)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lato-tech** [comment]
Just to add to it, this is happening with multiple entries and this is only appearing when applying the filters 'Missing in PI' & 'Accept My Values'. There is no issue with 'Missing in 2A/2B' & 'Accept Supplier Values' filters.

**Comment by ljain112** [comment]
Could you please confirm if there is any document linked within the Inward Supply? If a document exists, has it been cancelled?

![image](https://github.com/resilient-tech/india-compliance/assets/108322669/4de7ef70-1fe6-4dd2-856b-3952a7b9bf46)

**Comment by lato-tech** [comment]
Hi,

Yes you are right. They are linked with cancelled Purchase Invoices.

**Comment by ljain112** [comment]
The issue occurred due to the cancellation of the Invoice after reconciliation.
We already have PR for this issue to unset linking if the document is cancelled.
https://github.com/resilient-tech/india-compliance/pull/2147

**Comment by lato-tech** [comment]
Alright. Thanks.
