### ISSUE TITLE
Credit Note created by Journal entry not showing in GSTR1 Reports

### ISSUE THREAD

**Issue by bhavyajicomputers** [resilient-tech/india-compliance#2148]
Hi,
GSTR1  reports not showing credit not created by journal entry
![image](https://github.com/resilient-tech/india-compliance/assets/113116758/48364530-e95e-4447-a709-0a5be2859755)

**Comment by ljain112** [comment]
Only transactions from Sales Invoice are supported in GSTR-1.
You need to create credit notes from the Sales Invoice.

Only Reversal of ITC is included in GST Reports from Journal Entry other journal entry is supported.
