### ISSUE TITLE
Error While Installing CannotChangeConstantError: Value cannot be changed for Created By

### ISSUE THREAD

**Issue by chechani** [resilient-tech/india-compliance#217]
I am getting this error while intalling India Compliance

CannotChangeConstantError: Value cannot be changed for Created By

Frappe V 14.1
Erpnext V14

**Comment by vorasmit** [comment]
Please follow the [Issue Guidelines](https://github.com/resilient-tech/india-compliance#contributing).

Traceback?
Screenshots?

How can we help you with so less information.
FYI. [Server Tests](https://github.com/resilient-tech/india-compliance/runs/7809952748?check_suite_focus=true) are Passing, and installation should not be a problem.

**Comment by chechani** [comment]
Traceback
```
frappe@ubuntu:~/frappe-bench$ bench --site site1.local install-app india_compliance
App payments already installed
App erpnext already installed

Installing india_compliance...
Updating DocTypes for india_compliance: [========================================] 100%
Setting up Income Tax...
Setting up GST...
Installation for India Compliance failed due to an error. Please try re-installing the app or report the issue on https://github.com/resilient-tech/india-compliance/issues/new if not resolved.
An error occurred while installing india_compliance: Value cannot be changed for Created By
Traceback (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 413, in install_app
    _install_app(app, verbose=context.verbose, force=force)
  File "apps/frappe/frappe/installer.py", line 299, in install_app
    frappe.get_attr(after_install)()
  File "apps/india_compliance/india_compliance/install.py", line 53, in after_install
    raise e
  File "apps/india_compliance/india_compliance/install.py", line 41, in after_install
    setup_gst()
  File "apps/india_compliance/india_compliance/gst_india/setup/__init__.py", line 27, in after_install
    create_custom_fields(fields, ignore_validate=True)
  File "apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 197, in create_custom_fields
    custom_field.save()
  File "apps/frappe/frappe/model/document.py", line 300, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 337, in _save
    self._validate()
  File "apps/frappe/frappe/model/document.py", line 550, in _validate
    self.validate_set_only_once()
  File "apps/frappe/frappe/model/document.py", line 604, in validate_set_only_once
    frappe.throw(
  File "apps/frappe/frappe/__init__.py", line 523, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 491, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.CannotChangeConstantError: Value cannot be changed for Created By
```
<img width="1418" alt="Screenshot 2022-08-13 at 11 06 28" src="https://user-images.githubusercontent.com/6291292/184470239-e382efa8-3098-441e-b044-f9f10b29297e.png">

**Comment by sagarvora** [comment]
Thanks for the information @chechani 

We are looking into this. Prima facie - it seems like an issue that needs to be fixed in Frappe Framework.

**Comment by sagarvora** [comment]
In this case, it looks like India Compliance is creating a custom field which already exists in your site and is created by someone other than Administrator. So Frappe is treating it as someone is trying to change the owner which is not permitted.

**Comment by chechani** [comment]
I was on erpnext version 14 beta 5 and I switched to V14 stable...since I am in India need GST compliance and hence installed India Compliance App.

No custom fields has been created.

**Comment by vorasmit** [comment]
A quick fix for you. Go to bench console and execute following commands.

```
from india_compliance.gst_india.constants.custom_fields import CUSTOM_FIELDS
from india_compliance.patches.post_install.update_e_invoice_fields_and_logs import delete_custom_fields

delete_custom_fields(CUSTOM_FIELDS)
frappe.db.commit()
```


After this try reinstalling the app.

**Comment by chechani** [comment]
> from india_compliance.gst_india.constants.custom_fields import CUSTOM_FIELDS
> from india_compliance.patches.post_install.update_e_invoice_fields_and_logs import delete_custom_fields
> 
> delete_custom_fields(CUSTOM_FIELDS)
> frappe.db.commit()

This solved the issue.


> Traceback
> 
> ```
> frappe@ubuntu:~/frappe-bench$ bench --site site1.local install-app india_compliance
> App payments already installed
> App erpnext already installed
> 
> Installing india_compliance...
> Updating DocTypes for india_compliance: [========================================] 100%
> Setting up Income Tax...
> Setting up GST...
> Installation for India Compliance failed due to an error. Please try re-installing the app or report the issue on https://github.com/resilient-tech/india-compliance/issues/new if not resolved.
> An error occurred while installing india_compliance: Value cannot be changed for Created By
> Traceback (most recent call last):
>   File "apps/frappe/frappe/commands/site.py", line 413, in install_app
>     _install_app(app, verbose=context.verbose, force=force)
>   File "apps/frappe/frappe/installer.py", line 299, in install_app
>     frappe.get_attr(after_install)()
>   File "apps/india_compliance/india_compliance/install.py", line 53, in after_install
>     raise e
>   File "apps/india_compliance/india_compliance/install.py", line 41, in after_install
>     setup_gst()
>   File "apps/india_compliance/india_compliance/gst_india/setup/__init__.py", line 27, in after_install
>     create_custom_fields(fields, ignore_validate=True)
>   File "apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 197, in create_custom_fields
>     custom_field.save()
>   File "apps/frappe/frappe/model/document.py", line 300, in save
>     return self._save(*args, **kwargs)
>   File "apps/frappe/frappe/model/document.py", line 337, in _save
>     self._validate()
>   File "apps/frappe/frappe/model/document.py", line 550, in _validate
>     self.validate_set_only_once()
>   File "apps/frappe/frappe/model/document.py", line 604, in validate_set_only_once
>     frappe.throw(
>   File "apps/frappe/frappe/__init__.py", line 523, in throw
>     msgprint(
>   File "apps/frappe/frappe/__init__.py", line 491, in msgprint
>     _raise_exception()
>   File "apps/frappe/frappe/__init__.py", line 443, in _raise_exception
>     raise raise_exception(msg)
> frappe.exceptions.CannotChangeConstantError: Value cannot be changed for Created By
> ```
> 
> <img alt="Screenshot 2022-08-13 at 11 06 28" width="1418" src="https://user-images.githubusercontent.com/6291292/184470239-e382efa8-3098-441e-b044-f9f10b29297e.png">

This happened even when setting up new blank site.

**Comment by chechani** [comment]
> A quick fix for you. Go to bench console and execute following commands.
> 
> ```
> from india_compliance.gst_india.constants.custom_fields import CUSTOM_FIELDS
> from india_compliance.patches.post_install.update_e_invoice_fields_and_logs import delete_custom_fields
> 
> delete_custom_fields(CUSTOM_FIELDS)
> frappe.db.commit()
> ```
> 
> After this try reinstalling the app.

this solved the issue

**Comment by sagarvora** [comment]
@chechani Did you install a custom app with India-specific fields first?
(you may have exported customisations to that app)

**Comment by chechani** [comment]
> @chechani Did you install a custom app with India-specific fields first? (you may have exported customisations to that app)

These were fixtures in my custom APP
```
fixtures = [
	{"dt": "Custom Field", "filters": [
		[
			"dt", "in", [
				"Lead",
				"Lead Source",
				"Opportunity",
				"Opportunity Lost Reason",
				"Customer",
				"Item",
				"Issue",
				"Issue Type",
				"Comment",
				"Item",
				"Item Group",
				"Sales Invoice"

			]
		]
	]},

	{"dt": "Property Setter", "filters": [
		[
			"doc_type", "in", [
				"Lead",
				"Lead Source",
				"Opportunity",
				"Opportunity Lost Reason",
				"Customer",
				"Item",
				"Issue",
				"Issue Type",
				"Comment",
				"Item",
				"Item Group",
				"Sales Invoice"
			

			]
		]
	]},

	{"dt": "Role", "filters": [
		[
			"name", "in", [

					"Admins",
					"Bren CRM Team",
					"CRM Lead",
					"CRM User",
					"Head of Sales",
					"Project Sales Head",
					"Project Sales User",
					"Presales Lead",
					"Presales User"

				]
		]
	]},

	{"dt": "Custom DocPerm", "filters": [
		[
			"role", "in", [
					"Admins",
					"Bren CRM Team",
					"CRM Lead",
					"CRM User",
					"Head of Sales",
					"Project Sales Head",
					"Project Sales User",
					"Presales Lead",
					"Presales User",
					"System Manager",
					"Customer",
					"Guest"

				]
		]
	]},

	{"dt": "Role Profile"} ,
	{"dt": "Module Profile"},
	{"dt": "Client Script"},
	{"dt": "Server Script"},
	{"dt": "Lead Source"},
	{"dt": "Issue Type"},
	{"dt": "Opportunity Lost Reason"},
	{"dt": "Project Location"},
	{"dt": "Specification"},
	{"dt": "USP"},
	{"dt":"Document Category"},
	{"dt":"Profession"},
	{"dt":"Document Standard Name"},
	{"dt":"Amenity Master"},
	{"dt": "Unit Status"},
	{"dt": "City"},
	{"dt": "State"},
	{"dt": "Structure Type"},
	{"dt": "Possession Item"},
	{"dt": "BHK"},  
	{"dt": "Project Milestone Master"}, 

	{"dt": "Notification", "filters": [
		[
			"document_type", "in", [
				"Lead"
			]
		]
	]}

]
```

**Comment by sagarvora** [comment]
It seems likely that some of these fixtures are creating the same Custom Fields as being created in India Compliance. Fret not, this issue will be fixed by https://github.com/frappe/frappe/pull/17816

**Comment by chechani** [comment]
Thanks

**Comment by sagarvora** [comment]
This issue will be fixed in next release of the Frappe Framework (`v14.2.1` or greater). Please reopen if it still happens.
