### ISSUE TITLE
Not able to install app in fresh installation of Frappe & Erpnext Version 15

### ISSUE THREAD

**Issue by jeetpatel60** [resilient-tech/india-compliance#2184]
### Information about bug

When installing on site showing below message.

Incompatible Frappe Version: 
Frappe version 15.28.0 not compatible with India Compliance 16.0.0.dev0
Please switch to version 16 of Frappe to use the current version of India Compliance.

### Version

Frappe version - 15.28.0
Erpnext Version - 15.25.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
For Frappe,Erpnext and India Compliance branches should be the same.
To ensure compatibility, please use the version-15 branch of India Compliance instead of the develop branch. Alternatively, you can use the develop branch of both Frappe and ERPNext.
