### ISSUE TITLE
Cannot print e-invoice format

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#2208]
### Information about bug

I created an invoice and generated the e-invoice. I got back the IRN number and it is updated in the invoice doctype as well but no e-invoice log was created. I do not know why?

Now when I use the print format for e-invoice, system shows the below error

![image](https://github.com/resilient-tech/india-compliance/assets/11851156/4e460aa0-1c6c-4066-b5bd-b223f4171226)

### Version

Frappe v15
ERPNext v15
India Compliance - v15.7.4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Scheduler might be disabled. It's required for log generation as it's enqueued.
