### ISSUE TITLE
Not able to add different Item Tax to same item (Inconsistent Item Tax Templates) and Tax as Actual

### ISSUE THREAD

**Issue by lato-tech** [resilient-tech/india-compliance#2227]
Hi,

I have been facing this issue since I started using India Compliance on ERP Next. We are not able to add different item taxes and tax as actual in Purchase Invoices. I'll mention below why I need it and why it is important.

1. There are a lot of vendors (specially repairs) who during repair of machinery and vehicle add a lot of items (around 10-50) in their Sales Invoices with different tax components. We only have a single item for those like - Vehicle Repair & Maintenance or Pump Repair or Motor Repair. We used to use this single item for all the tax components of their invoices, which we are not able to now. I am not in favor of adding Vehicle Repair & Maintenance 18%, Vehicle Repair & Maintenance 28%, etc., as all my previous entries / reporting will be of no use.
2. A lot of times we have a single item for example 'File' which includes Plastic (18%) & Paper / Cardboard (5%) files. When I purchase both Plastic and Cardboard file together and their taxes are different, I am not able to make the invoice and therefore not able to reconcile the GST returns. It also depends on the vendor. Some vendors will classify Plastic File as a plastic product and Cardboard file as a paper product so the HSN and tax component changes.
3. We deal with the Govt. for a lot of our procurement. There if we are buying for example an item 'x' (200 units) which has components like Govt. Royalty (₹10,000), Extraction(₹10,000), etc., and the Invoice Grand Total is ₹21,800 for 200 units. How will I be able to add this Invoice in my system and match the values? The Govt. only applies GST on Extraction and not on Royalty. Due to this I am not able to make that invoice since I am not able to add the same item 'x' in two rows with one having 0% tax and the other having 18% tax.

This is directly affecting the working of accounts in our company and maybe others too. It was there before as I mentioned earlier.

I would request you to kindly have a look into it as practically this logic / restriction is not working out. If you need any supporting Invoices from my end I can provide them.

Hoping for a positive response from your end.

**Comment by lato-tech** [comment]
Hi,
Please let me know if anyone has read this or needs more info.

**Comment by ljain112** [comment]
We understand your requirements.
But we have to disallow it because there is no way to identify item-wise tax details which is required for GST Reporting.
We are in discussions with the ERPNext Team to implement these changes. However, this will be a significant update and will be part of Version 16, which does not yet have a release date.

For now, you have to maintain separate items. There is no other way this can be handled.

**Comment by vorasmit** [comment]
It's important to maintain item wise taxes for reporting requirements in GSTR-9 (even for purchases).

Hence going ahead in future, after fixes in ERPNext, we may introduce ability to allow same item with different Item Tax Rates.

But you will not be able to add taxes manually with keeping tax type as actual even in the future.

**Comment by lato-tech** [comment]
Is adding same item with different taxes also expected in ERP Next v16? Isn't this feature controlled by India Compliance app?

**Comment by lato-tech** [comment]
Hi,
Is this resolved? I have a lot of pending Purchase Invoices with items having multiple tax slabs. Please update by when can this be implemented.
Thanks.

**Comment by vorasmit** [comment]
Different Item => Different Tax Rate = Already supported since inception.
Same Item => Different Tax Rate = Still not supported. Issue lies in the core design at ERPNext which is a little difficult to fix.
