### ISSUE TITLE
Do i need to install version-15-hotfix also after installating version-15

### ISSUE THREAD

**Issue by Pankajvcm244** [resilient-tech/india-compliance#2250]
### Information about bug

I have installed version-15, do i need to install version-15-hotfix also on top of version-15 ?

### Version

India compliance version-15

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
No, Just v15 is required.

---

Better place to ask general queries:
https://discuss.frappe.io/

Github issues should be preferred for reporting bugs or feature requests.
