### ISSUE TITLE
How to add the Expenses which are borne after the Purchase of the New Asset during the Year or In case there is an Opening Balance in the Asset A/c under the Fixed Asset Module.

### ISSUE THREAD

**Issue by JitendraSAW** [resilient-tech/india-compliance#2268]
### Is your feature request related to a problem? Please describe.

How to add the Expenses which are borne after the Purchase of the New Asset during the Year or In case there is an Opening Balance in the Asset A/c already under the Fixed Asset Module.

As I have a use case where I have to add my Rent or Transporation Expenses say Rs 10500 to my Asset A/c, but some Asset it is purchased during the year and some Asset which are purchased in the Last Year and thereby there is an opening Balances.

So My Question how the above can be managed through Fixed Assets Module.
Let say- We have a Purchase Invoices Bills for the Rent Expenses of Rs 5000, now this expenses should be capitalised in our Furnture and Fixtures of Rs 50000/- which is already in the Opening Balances

Thanks & Regards,

**Comment by vorasmit** [comment]
This is a general question related to ERPNext. Discuss forum is a better place to get answer for this. Github issues should be preferred only for Feature requests or Bug Reports.
