### ISSUE TITLE
Charge Type "Actual" is not supported in Bill of Entry

### ISSUE THREAD

**Issue by parasonit** [resilient-tech/india-compliance#2275]

**Comment by vorasmit** [comment]
How is the GST here calculated? Just on the assessable value?

We believe that it should be calculated on (assessable value + customs duty).

It's difficult to apportion taxes to items based on it's rates if we allow Actual's in the template. This directly would affect the reporting where item level information is required to be reported.

I guess your assessable value should be 2035048.46

**Comment by parasonit** [comment]
> How is the GST here calculated? Just on the assessable value?
> 
> We believe that it should be calculated on (assessable value + customs duty).
> 
> It's difficult to apportion taxes to items based on it's rates if we allow Actual's in the template. This directly would affect the reporting where item level information is required to be reported.
> 
> I guess your assessable value should be 2035048.46

Yes, it is calculated  on Asseseble value and custom duty

Please check another example below where the GST is calculated on (Ass. Value + Custom Duty + SWS +Freight +Insurance)

![image](https://github.com/resilient-tech/india-compliance/assets/118710551/da957e1f-927b-42f9-9535-21a3a0419afc)
![image](https://github.com/resilient-tech/india-compliance/assets/118710551/8f858d70-78e9-4f87-96fb-37f32d480bb4)

Above document is already posted in Version 14.

**Comment by vorasmit** [comment]
In such cases, ideally your assessable value should be computed after apportioning freight and other charges to your item. In the end such cost is attributable to item and should be loaded likewise through LCV.

Assessable value is not accounted for in BOE. It's just to show an indication of what is the cost attributable to item.

**Comment by parasonit** [comment]
> 3\. GST calculation

This "Actual" Option is available in version 14 for GST calculations. is it restricted in Version 15?

**Comment by vorasmit** [comment]
It's a recently introduced validation. It's restricted in both v14 and 15.
This is to ensure item taxes are retained for advanced reporting like GSTR-9. This information will not be available at a later date when HSN wise purchases or 9C is filed (if charge type actual is used).

**Comment by vorasmit** [comment]
Closing this issue as it's not planned. However, feel free to add comments or suggestion if this could be handled in better way.

**Comment by thenbdev** [comment]
> It's a recently introduced validation. It's restricted in both v14 and 15. This is to ensure item taxes are retained for advanced reporting like GSTR-9. This information will not be available at a later date when HSN wise purchases or 9C is filed (if charge type actual is used).

When Actual is used, default GST rate can be used as an alternative. Actual is needed where the GST is calculated on (Ass. Value + Custom Duty + SWS +Freight +Insurance) as mentioned in https://github.com/resilient-tech/india-compliance/issues/2275#issuecomment-2182703091

**Comment by vorasmit** [comment]
Please Note:

Assessable Value for customs = Taxable Value + SWS + Freight + Insurance.
This is the value on which customs duty is computed, and then GST is computed.
This is already editable and you can enter any value you wish to have there.

SWS + Freight + Insurance is not at actuals and is presumed at times, and hence there is not benefit of having this breakup.
