### ISSUE TITLE
When submit sales invoice the below error comes up - AttributeError: 'GSTSettings' object has no attribute 'restrict_changes_after_gstr_1'?

### ISSUE THREAD

**Issue by yabesh12** [resilient-tech/india-compliance#2332]
### Information about bug

![Screenshot 2024-07-02 153338](https://github.com/resilient-tech/india-compliance/assets/64887750/a5f4db97-8466-4ab0-a806-1f42b238838b)

### Version

Installed Apps
ERPNext: v15.28.2 (version-15)

Frappe Framework: v15.32.0 (version-15)

Helpdesk: v0.10.0 (main)

Frappe HR: v15.23.0 (version-15)

India Compliance: v15.9.0 (version-15)

Payments: v0.0.1 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
We can continue here.

https://discuss.frappe.io/t/when-submit-sales-invoice-the-below-error-comes-up/127912/2

We can re-open if it's a genuine bug.
