### ISSUE TITLE
GST r1 GST Rate not picked

### ISSUE THREAD

**Issue by bhavyajicomputers** [resilient-tech/india-compliance#2382]
![image](https://github.com/resilient-tech/india-compliance/assets/113116758/081fe9cd-4e32-4f7f-90c1-6b79f83a6f02)

**Comment by vorasmit** [comment]
Please create appropriate issue with which version are you on and what is the exact issue. It's not possible for us to know what the issue is just from the error message.

**Comment by vorasmit** [comment]
Can be reopened with complete details if the issue still persists.
