### ISSUE TITLE
Two Minor issues in "GST Tax Invoice" print format

### ISSUE THREAD

**Issue by GopalKedia2020** [resilient-tech/india-compliance#2384]
### Information about bug

I really appriciate how well you have developed this print format for india.

But i have obsersered one bug, I have updated the logo of compnay in Print Option Section of compnay doctype (PNG Format), but its not fecthing the logo in actual print format. 

Second thing is a suggestion, please add Account Holders Name option too in bank details, as this is also required to make paymnets, sometimes, company name differes from account name.

### Version

Frappe Chat: v0.0.1 (HEAD)

Email Delivery Service: v0.0.1 (HEAD)

ERPNext: v15.21.1 (HEAD)

Frappe Framework: v15.24.1 (HEAD)

Frappe Whatsapp: vv1.0.7 (HEAD)

Frappe HR: v15.22.3 (HEAD)

India Compliance: v15.10.1 (HEAD)

Payments: v0.0.1 (HEAD)

Print Designer: v1.3.3 (HEAD)

Webshop: v0.0.1 (HEAD)

Wiki: v2.0.0 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
First one looks like an issue with Frappe, we'll revert on that soon.
For second one: you can use any custom key (other than options available) in the configuration and that's allowed.

**Comment by GopalKedia2020** [comment]
Thanks, I have added Account Name, and its wokring as expected.

**Comment by GopalKedia2020** [comment]
we can add a logic in qr code scan, if outstanding is more than 1 lac rupee, it gives open field to enter amount. as in india max upi limit per day is 1 lac only, like below. and invoice aboove that cant be paid in full in one go.

<div>
                    {% if doc.outstanding_amount > 100000 %}
                        {{ web_block('UPI QR Code', values={'upi_qr_text': 'upi://pay?pa=' ~ upi_id.value ~ '&tn=' ~ doc.name ~ '&cu=INR' }) }}
                    {% else %}
                        {{ web_block('UPI QR Code', values={'upi_qr_text': 'upi://pay?pa=' ~ upi_id.value ~ '&am=' ~ doc.outstanding_amount ~ '&tn=' ~ doc.name ~ '&cu=INR' }) }}
                    {% endif %}
                </div>

**Comment by vorasmit** [comment]
>its not fecthing the logo in actual print format

Did you save the file as private file? I guess public files will cause an issue.

**Comment by GopalKedia2020** [comment]
> Did you save the file as private file? I guess public files will cause an issue.

I had uploaded logo as public file, but i just tested it by reuploading as private file, still not fetching in print format.

**Comment by vorasmit** [comment]
Can you share error from console of your browser? Additional screenshots of print format could be useful.

**Comment by GopalKedia2020** [comment]
I have just fixed the issue. Enclosed Image src Attribute in Quotes and it worked.

 ... src="{{ logo_for_printing }}" style="height: 30px ....
