### ISSUE TITLE
Revised B2CL Limit for GSTR-1

### ISSUE THREAD

**Issue by vorasmit** [resilient-tech/india-compliance#2413]
2.5 lacs changed to 1L

> Taxable outward inter-state supplies to unregistered persons, in other words, B2C supplies, where the invoice value is more than Rs.2.5 lakh (This limit has been reduced from Rs.2.5 lakh to Rs.1 lakh at the 53rd GST Council meeting).28 Jun 2024

### Pending

Effective date for this change is not yet known.

### Note

It's important to keep this change backwards compatible. Old limit should apply for transactions before effective date.

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NjkxMDRmNjIwOTUyNGNjNGY4NTc4ZjUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3IiwicHJvZHVjdElkIjoiIn0.mJSzxtAlOw5_Mn2z03ED7iKVF5UjafQFANj4QWICMNg">Huly&reg;: <b>IC-2526</b></a></sub>

**Comment by ljain112** [comment]
Effective from 1st August 2024
https://cleartax.in/s/gst-b2c-b2b-large-small-invoice
