### ISSUE TITLE
Einvoice QR Code Print

### ISSUE THREAD

**Issue by sumeetagra** [resilient-tech/india-compliance#247]
The QR Code pdf is not attached to Sale Invoice. Hence the Sale Invoice cannot be printed with QR Code inspite of Einvoice generation.

**Comment by sagarvora** [comment]
The QR code's PNG is no longer being attached. We decided it would be better not to create these files, since they can be generated on the fly. Check out the implementation in the standard **e-Invoice** print format:

https://github.com/resilient-tech/india-compliance/blob/4bd775ab656f81fc6764cc1dc6587d11e0097afd/india_compliance/gst_india/print_format/e_invoice/e_invoice.html#L109
 

You can print the sales invoice with QR Code by entering following code in your print format:

```html
{% set e_invoice_log = frappe.db.get_value("e-Invoice Log", doc.irn, ("signed_qr_code"), as_dict=True) %}
<img src="data:image/png;base64,{{ get_qr_code(e_invoice_log.signed_qr_code, scale=2) }}" class="qrcode">
```

**Comment by sumeetagra** [comment]
Thanks for the quick revert... We ll check at out IT team level and get
back to you.

Thanks & Regards
Sumeet Goyal

**Comment by sagarvora** [comment]
@sumeetagra Closing the issue for now. Please comment here if the issue still persists.

**Comment by dev-barlota** [comment]
" _{% set e_invoice_log = frappe.db.get_value("e-Invoice Log", doc.irn, ("signed_qr_code"), as_dict=True) %}
`<img src="data:image/png;base64,{{ get_qr_code(e_invoice_log.signed_qr_code, scale=2) }}" class="qrcode">` "

The above code throws an Error - 
**ValueError: too many values to unpack (expected 2)**

**Comment by sagarvora** [comment]
@dev-barlota 

It works for me:

![image](https://user-images.githubusercontent.com/16315650/194471544-e2036a90-6283-46f2-aaa6-4aa0e1c8fe64.png)


This is the print format for reference:

![image](https://user-images.githubusercontent.com/16315650/194471764-c0c24517-fc29-43f4-a064-8feed982adb2.png)

```
{"name":"e-Invoice Test","owner":"Administrator","creation":"2022-10-07 01:01:15.631753","modified":"2022-10-07 01:01:15.631753","modified_by":"Administrator","docstatus":0,"idx":0,"doc_type":"Sales Invoice","module":"Accounts","default_print_language":"en","standard":"No","custom_format":1,"disabled":0,"print_format_type":"Jinja","raw_printing":0,"html":"{% set e_invoice_log = frappe.db.get_value(\"e-Invoice Log\", doc.irn, (\"signed_qr_code\"), as_dict=True) %}\n<img src=\"data:image/png;base64,{{ get_qr_code(e_invoice_log.signed_qr_code, scale=2) }}\" class=\"qrcode\">","margin_top":15,"margin_bottom":15,"margin_left":15,"margin_right":15,"align_labels_right":0,"show_section_headings":0,"line_breaks":0,"absolute_value":0,"font_size":14,"page_number":"Hide","print_format_builder":0,"print_format_builder_beta":0,"doctype":"Print Format","__onload":{"print_templates":[]}}
```

Perhaps some other code in your print format may be failing. If you still need assistance, please post full traceback.

**Comment by dev-barlota** [comment]
Hi @sagarvora,
![Img2](https://user-images.githubusercontent.com/50095520/194487193-318700bc-dfbe-4f0d-9ba2-244471d13ebf.JPG)
![IMg1](https://user-images.githubusercontent.com/50095520/194487200-58c6db8b-7668-4cf8-bcb5-7207a57c15ae.JPG)


when i enter the code in the Custom HTML tab of the Print Format, it throws this error.

**Comment by sagarvora** [comment]
@dev-barlota I'll need the full traceback to assist you further. Alternatively, you can email us at the following e-mail address to avail support:

```
hello at indiacompliance dot app
```

**Comment by IamChhteri** [comment]
If anyone facing error pop-up :

**ValueError: too many values to unpack (expected 2)**


**this below line code may help** :

```
{% set e_invoice_log = frappe.db.get_value("e-Invoice Log", doc.irn, ("signed_qr_code"), as_dict=True) %}
{% set e_invoice_img = 'data:image/png;base64,'+get_qr_code(e_invoice_log.signed_qr_code, scale=2) %}
    <div class="col-sm-6" style="height: 100%; width: 100%;">
                    <img src = '{{ e_invoice_img }}' class="qrcode">
     </div>
```
