### ISSUE TITLE
Pip Pypng dependency issue

### ISSUE THREAD

**Issue by chechani** [resilient-tech/india-compliance#249]
Getting below dependency issue
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
frappe 14.7.0 requires pypng~=0.0.20, but you have pypng 0.20220715.0 which is incompatible.
```

**Comment by sagarvora** [comment]
You have not set up requirements for `frappe` again. You can do so by executing the following command from your bench directory:
```bash
bench setup requirements --python
```

**Comment by chechani** [comment]
still getting this error
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
india-compliance 0.0.1 requires pypng~=0.20220715.0, but you have pypng 0.0.21 which is incompatible.
```

**Comment by sagarvora** [comment]
Thanks for reporting. We have replicated the issue, which should be fixed by this PR:
https://github.com/frappe/frappe/pull/18121

Note: This is more like a warning and can be safely ignored. Your ERP should work fine irrespective of the which pypng version is used.

**Comment by chechani** [comment]
Thanks

**Comment by sagarvora** [comment]
The warning will go away when you upgrade to the next frappe release. Till then, you can safely ignore it.
