### ISSUE TITLE
Purchase Invoice not Matching GST: All details are same as in the 2A/2B but it is showing as Missing in PI and also showing MIssing in 2A/2B

### ISSUE THREAD

**Issue by eskhool** [resilient-tech/india-compliance#2533]
<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmM2ZjIzZThjMmMxOTBhN2E0ZDExYWQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3IiwicHJvZHVjdElkIjoiIn0.G2izCURz508_bTEv02Q4D7k0VFkvdm9-MCXNN84omLc">Huly&reg;: <b>IC-2641</b></a></sub>

**Comment by vorasmit** [comment]
We have identified this issue mainly with credit notes. We'll inspect this further and fix this issue.

**Comment by eskhool** [comment]
There is no credit note involved in this Purchase Invoice.

Is the code base same for 14 vs 15? I am planning to upgrade and will expedite if that will fix it

**Comment by vorasmit** [comment]
Sorry I meant debit note (Purchase Return). It's the debit note from the screenshot that you shared.
It's the same code in v15 for the reco tool.

**Comment by eskhool** [comment]
But there is no debit note involved here. There is a purchase invoice in the system which is showing a +957.63 but not found in 2A/2B. and there is a -957.63 which is the GST 2A/2B entry which didn't find an equivalent in the Purchase Invoice.

Where is the debit note according to you?

**Comment by eskhool** [comment]
This is a valid credit note case but there are other bills where we have a perfect match but are not matching.

Is there some logging that can be turned on or specific matching be done manually to see why the reconciliation tool is not finding these? @vorasmit 
Adding example

<img width="1255" alt="Screenshot 2024-08-23 at 5 53 19 PM" src="https://github.com/user-attachments/assets/57e3363c-c6f6-4ca7-ac94-046b6c708ffe">

**Comment by vorasmit** [comment]
Hi,

By any chance did you manually unlink the documents that were once linked automatically?

This is how we have implemented the matching. If a document is unlinked manually, it's never attempted for a rematch. You can check this from GST Inward Supply from match status.

![image](https://github.com/user-attachments/assets/92f0edac-807d-4e5b-9372-b327b1c25b78)

If this is the case, you can manually mark the status of these documents as `empty` and then retry the match.
