### ISSUE TITLE
Error While trying to view or update customer or company

### ISSUE THREAD

**Issue by sagarrgarg** [resilient-tech/india-compliance#2563]
### Information about bug

"User sagarratangarg@rbcolour.com does not have access to this document: PAN - None
Insufficient Permission for PAN (create)" for any user even administrator.

### Version

ERPNext: v15.33.4 (HEAD)

Frappe Framework: v15.39.0 (HEAD)

India Compliance: v15.13.0 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Permissions to create is not there intentionally as it's a system generated document.
It should be fixed and soon be available as a patch release.

Thank you for reporting this issue promptly.
