### ISSUE TITLE
ITC - 04 Explanation   Subcontracting 

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#2574]
### Information about bug

Can you please provide a explanation  on ITC 04 on subcontracting

### Version

RPNext: v15.33.5 (version-15)

Frappe Framework: v15.39.0 (version-15)

Frappe Whatsapp: vv1.0.7 (master)

Frappe HR: v15.27.0 (version-15)

India Compliance: v15.13.0 (version-15)

### Relevant log output / Stack trace / Full Error Message.

*No response*

### Code of Conduct

* [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmM5Y2NmNjhjMmMxOTBhN2E2NDBiYzEiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3IiwicHJvZHVjdElkIjoiIn0.OYaBoCIGeILI1xR47IcFuZ4JD9rldrVDhgMm0mwNSfU">Huly&reg;: <b>IC-2692</b></a></sub>

**Comment by vorasmit** [comment]
It's implemented:
https://docs.indiacompliance.app/blog/posts/post5
