### ISSUE TITLE
Recommendation list of CAs who are familiar with this app.

### ISSUE THREAD

**Issue by clayrisser** [resilient-tech/india-compliance#2575]
### Is your feature request related to a problem? Please describe.

It would be nice if there was a list of CAs in India who are familiar with this app and erpnext.

**Comment by frewper** [comment]
How is this an issue ?  The right place for this question is on the forum. 

Btw, the app is quite intuitive enough that any person with the knowledge of GST will understand whats going on. 

You may scan the telegram groups for available CAs. 

Kindly close this issue. This is a wrong place for this question

Cheers.

**Comment by clayrisser** [comment]
Ok, thank you for the clarification.
