### ISSUE TITLE
GST Amount population issue.

### ISSUE THREAD

**Issue by Yagniksojitra** [resilient-tech/india-compliance#2588]
### Information about bug

If the Tax Category of Supplier is blank, then after selection of Tax Category it does not update the tax amount in the CGST & SGST rows. The screenshot is attached herewith.

![image](https://github.com/user-attachments/assets/67896848-9cc7-4d5e-8508-b2bdfa47201d)

### Version

ERPNext: v15.34.0 (version-15)
Frappe Framework: v15.39.1 (version-15)
India Compliance: v15.13.2 (version-15)

### Relevant log output / Stack trace / Full Error Message.

```shell
Screenshot attached
```

### Code of Conduct

* [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmQ0YmJmMGZmMDBmMWVjN2RhNGIxOTgiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.-3jTbjJU8t0IiD8-Gvua_bCrHqlY6T8xIe-CfdEXXZs">Huly&reg;: <b>IC-2706</b></a></sub>

**Comment by vorasmit** [comment]
Tax category should not be necessary in customer / supplier / address / transactions.
Try using it without tax category.
