### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith' Possible source of error: india_compliance (app)

### ISSUE THREAD

**Issue by Sejal0608** [resilient-tech/india-compliance#2603]
At the time of creating a new purchase invoice, We are facing below issue:

![image (3)](https://github.com/user-attachments/assets/a0c07e15-59cf-4ac1-bf66-31e3aa8806d2)

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmRlZGVhMDNiYjU3YTg1ZTg3MGIzOGIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.wgVIZXpXr43tKUrqOm-sHD5LRqGtOD3AJckPYKYzj7I">Huly&reg;: <b>IC-2722</b></a></sub>

**Comment by vorasmit** [comment]
We'll fix this. For now, ensure all items have HSN Code in purchase invoice.

**Comment by Sejal0608** [comment]
Thanks. Issue fixed.
