### ISSUE TITLE
Filter for invalid invoice number in document issue summary(GSTR-1)

### ISSUE THREAD

**Issue by ljain112** [resilient-tech/india-compliance#2608]
There can be invalid invoice numbers (invalid character or length greater than 16 chars) they should be part of special group like draft invoice /non gst invoices because they are not accepted in json upload.

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NmUwNWViNTUxYWRhNGYzOTdhZjUzM2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.cQfOiJuypW8H5ltKgkWGAWboSvshUgFABGzEooYIJ90">Huly&reg;: <b>IC-2728</b></a></sub>

**Comment by vorasmit** [comment]
- Naming series for PINV. Only for new install.
- Exclude in Doc Issued summary
- Validate on save: Different PR. Only Develop.

**Comment by vorasmit** [comment]
#2609
