### ISSUE TITLE
Unable to view GSTR-1 Report,  UI not loading after update from 15.7->15.13.3

### ISSUE THREAD

**Issue by me1go** [resilient-tech/india-compliance#2649]
<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzAwM2E0ZTlhYjUzMTJlZjhkMWU3NWIiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.suFY5vKjPOi0_4im313hAcAcA5C6XUFeLe6eIxEYDU4">Huly&reg;: <b>IC-2773</b></a></sub>

**Comment by vorasmit** [comment]
This looks like a migrate or JS build issue with your site. Are you still facing this issue?

`bench build` should resolve this IMO.
