### ISSUE TITLE
e-Invoice Summary Report

### ISSUE THREAD

**Issue by nrhdasa** [resilient-tech/india-compliance#265]
![image](https://user-images.githubusercontent.com/40687270/193395409-dd44bbcb-bb73-40af-9acb-c4d28cbbcdbe.png)

The above error appears after running bench migrate.

Though there is solution which is to delete 'e-invoice Summary' from 'tabReport'. But I don't know why it is appearing.

**Comment by sagarvora** [comment]
@nrhdasa I couldn't replicate this issue locally. I'll need more information.

- Does it happen every time you migrate?
- If yes, can you produce the relevant error log? It may be present in `logs/web.log` or `logs/web.error.log` in your bench instance.

**Comment by nrhdasa** [comment]
@sagarvora 

- [ Yes it happens every time I run bench migrate and then I manually delete report from `tabReport`, then only I can do something else.]
- I am putting here the error message as asked.

**Comment by nrhdasa** [comment]
```
Traceback (most recent call last):
  File "apps/frappe/frappe/www/app.py", line 28, in get_context
    boot = frappe.sessions.get()
  File "apps/frappe/frappe/sessions.py", line 161, in get
    bootinfo = get_bootinfo()
  File "apps/frappe/frappe/boot.py", line 36, in get_bootinfo
    get_user(bootinfo)
  File "apps/frappe/frappe/boot.py", line 268, in get_user
    bootinfo.user = frappe.get_user().load_user()
  File "apps/frappe/frappe/utils/user.py", line 255, in load_user
    d.all_reports = self.get_all_reports()
  File "apps/frappe/frappe/utils/user.py", line 259, in get_all_reports
    return get_allowed_reports()
  File "apps/frappe/frappe/boot.py", line 140, in get_allowed_reports
    return get_user_pages_or_reports("Report", cache=cache)
  File "apps/frappe/frappe/boot.py", line 243, in get_user_pages_or_reports
    has_role[report.name]["report_type"] = report.report_type
KeyError: 'e-Invoice Summary' 
```

**Comment by sagarvora** [comment]
We have identified the issue and will release a fix shortly. Thanks for reporting!

You had custom roles for the earlier `E-Invoice Summary` report, and because the comparison in MariaDB is case insensitive, it causes the above issue.

**Comment by sagarvora** [comment]
@nrhdasa Please update to the latest commit. Feel free to comment here if this issue persists.
