### ISSUE TITLE
Request for Column Addition in GSTR-1 B2C (Small) Invoices Report

### ISSUE THREAD

**Issue by Deepakjs5665** [resilient-tech/india-compliance#2655]
<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA1ZmQ2NWI5ODBmNDFkYjY3ZDA2ZjQiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.9f1EVWiMwGQqkZUzgWdF_eeKy95j1lqze24VUzAhUhk">Huly&reg;: <b>IC-2779</b></a></sub>

**Comment by vorasmit** [comment]
Hi,

It's not possible in this report to have invoice number column in B2C, because there could be more than one invoice.

In GSTR-1 Beta Report or GST Sales Register Beta Report, this breakup is readily available. 

In GSTR-1 Beta => Books Tab => Click on B2C.

Does this help?
