### ISSUE TITLE
 CGST appears multiple times

### ISSUE THREAD

**Issue by nrhdasa** [resilient-tech/india-compliance#266]
![image](https://user-images.githubusercontent.com/40687270/193397239-5b43e4bc-db08-4c2b-bd10-1d942382cba5.png)

![image](https://user-images.githubusercontent.com/40687270/193397251-5bedf222-e43e-4798-a46f-d70b1c80f21e.png)

In the last version of ERPNext v13, we had a common GST account for both Input and Output transactions.
Since, in v14, it is mandatory to choose different accounts, we can select though, but then the difficulty is we will not get proper GST reports because of changes in GST accounts, for ex. from CGST to CGST-Input.

How to deal with it? Please suggest.

**Comment by vorasmit** [comment]
Hi,

You should be maintaining separate accounts. It's necessary, as you will see [here](https://cleartax.in/s/gst-accounts-record), for the bifurcation of Input Tax Credit Claimed. Also, this helps at a later date to identify the differences and resolve them.

If you have not maintained them separately until now, no issues.

Select a cut-off date, say 01-10-2022. Create new Input Accounts. Transfer appropriate balances from respective accounts to Input accounts. This will have your books sorted from that date without affecting previous accounting.

**Comment by sagarvora** [comment]
@nrhdasa Perhaps this discussion needs to continue on the [community forum](https://discuss.erpnext.com/c/erpnext/india-compliance/65) / e-mail. This is not a planned feature / bug that needs fixing.
