### ISSUE TITLE
Document Reference for Subcontracting is restrictive

### ISSUE THREAD

**Issue by Kushalnahata17** [resilient-tech/india-compliance#2661]
### Information about bug

In the current Job Work Process, when I receive a Subcontracting Receipt, the system allows for only one document reference to be manually selected in the Job Working Delivery Note field. However, in real-world scenarios, multiple documents are often associated with a single job. The current setup is limiting, as it does not accommodate this need.

Given that this feature does not meet current market standards and we don't require it at this time, I kindly request that this document reference feature be removed or Given any Solution for particular this things to which help to Generate ITC 04 Report.
![Screenshot 2024-10-09 173120](https://github.com/user-attachments/assets/aed14a4d-b454-4968-953c-988d691f2e91)

### Version

Erpera: v0.0.1 (HEAD)

ERPNext: v15.38.1 (HEAD)

Frappe Framework: v15.44.1 (HEAD)

Frappe HR: v15.31.0 (HEAD)

India Compliance: v15.13.4 (HEAD)

Print Designer: v1.4.3 (HEAD)

Sona: v0.0.1 (HEAD)

### Relevant log output / Stack trace / Full Error Message.

```shell
That should be not Connect With References
```

### Code of Conduct

* [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzA4ZmRlYWM3ZDZhNTZhOGY5MWUyYTYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.VI_PcTOQj2N7uQWmCMLEYk4ZywMMg8u2WSAlWUdlYnM">Huly&reg;: <b>IC-2785</b></a></sub>

**Comment by vorasmit** [comment]
You can add more than one reference of stock entry. Only condition is that it should be related to same subcontracting order for which you are receiving the material.

Do you think this is still a bug? If so, please explain it with a complete scenario or use case.

**Comment by Kushalnahata17** [comment]
Yes, it should be the opposite. For example, the Vendor sent 100kg to a subcontractor, and then I placed a subcontracting order for 30kg. I received 28 kg, which is a receipt. The process goes on until the Stock does not end at the subcontractor's warehouse.

hope you understand if any queries please let me know.

**Comment by Ninad1306** [comment]
Doc references are not there in Stock Entry, instead they have to be selected in `Stock Entry Return` as if against which stock entry the return is done.

And for subcontracting receipt we have removed `doc references` as mandatory and this change will be reflected in the next release.

If any queries then let me know.

**Comment by Kushalnahata17** [comment]
it does not solve the issue of the itc04 report. As I have given an example above, I am including it here for you. we have not received the stock, So we can not do the stock entry

**Comment by Ninad1306** [comment]
### Problems faced:

- Only one reference can be selected in subcontracting receipt (job worker delivery note).

### Current Implementation

- `Job worker delivery note` is not where the reference documents are to be selected. It just signifies the challan no of the finished goods returned from job worker (Hence only name can be entered).
- `Doc references` table is where the document references are to be selected. Currently `Stock Entry` with only one subcontracting order is allowed to be selected.

<img width="921" alt="Screenshot 2024-10-15 at 11 05 59 AM" src="https://github.com/user-attachments/assets/225589b6-d0e3-454d-88da-386c50b0410e">


### Possible Solutions

- Documents against multiple subcontracting orders can be allowed to be selected.


Please let me know if any more problems faced or other possible solutions to the current problems.

**Comment by Kushalnahata17** [comment]
My Suggestion is
We should remove the connection of the Subcontracting order And Keep the Subcontracting receipt as multiple selections with the Same Validation we have right now. It will Solve all the People.
lets connect on kushal@reformiqo.com

**Comment by Kushalnahata17** [comment]
Please let me know when there will be a non-mandatory Feature available
