### ISSUE TITLE
Purhcase Reconciliation tool finds mismatch even though tax amount is appearing in the PI

### ISSUE THREAD

**Issue by amrit-citrusleaf** [resilient-tech/india-compliance#2678]
### Information about bug

First of all, thanks a lot for maintaining this life-and-time-saver Frappe app!

Now, onto the issue-

While using the purchase reconciliation tool to match GST invoices, we found some “mismatch“ entries.
Lots of these entries have incorrect GST amount as compared to their respective Purchase invoices.

An example is below-

![image](https://github.com/user-attachments/assets/1e748265-b216-4b2b-86fa-6ad43fc20d22)

In this case the GST amount in the ERPNext PI is not set, according to the reconciliation tool.
However, the purchase invoice has taxes set-
![image](https://github.com/user-attachments/assets/da958ec5-04c0-4708-b487-c7e192ecec2c)

But the GST breakup table is empty-

![image](https://github.com/user-attachments/assets/f2541edc-56a4-4959-859f-595228afc110)

### Version

Ecommerce Integrations: v1.17.0 (HEAD)
ERPNext: v14.74.5 (HEAD)
Frappe Framework: v14.82.1 (HEAD)
India Compliance: v14.30.5 (HEAD)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzEzNzY3NGNlNzQ0ODdkZDQzZTBjN2UiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.0ZZhmPOUlPYsxIn8VilFgvBAkW5Jx_hDiVdpaRpXNgw">Huly&reg;: <b>IC-2802</b></a></sub>

**Comment by vorasmit** [comment]
Hi, Looks like in invoice gst details are not set correctly.
Have you specified these GST Accounts in GST Settings?

**Comment by amrit-citrusleaf** [comment]
Here comes the interesting part- for some invoices, the GST amount (CGST, SGST, IGST) are set to zero while the invoice itself has a tax template, and hence tax in the taxes and charges table.

Taxes are item level are zero-
<img width="1014" alt="image" src="https://github.com/user-attachments/assets/ca94334a-923f-4dad-862b-520d85487c7c">

Taxes at the invoice level are non zero-
<img width="979" alt="image" src="https://github.com/user-attachments/assets/cae9b9fc-4631-4289-b81b-1a45e4208a37">

I think the reconciliation tool checks the GST amount at item level, rather than at the form level.
Please confirm if my understanding is correct.

**Comment by vorasmit** [comment]
Yes correct.

What are the accounts specified in GST Settings?

**Comment by amrit-citrusleaf** [comment]
Got it. So the way out is to patch the existing data?

Or can I select the "Accept" button on the detail view and the system will update the 2A/2B status?

And, these are the accounts in GST settings-
![image](https://github.com/user-attachments/assets/61b9adf3-9bb2-4f19-90a8-232159bf5b02)

**Comment by vorasmit** [comment]
You can easily patch existing data.

- Change accounts in GST Settings.
- Execute [this](https://github.com/resilient-tech/india-compliance/blob/5541628b5881b35088382d11513d2c27f1f98a69/india_compliance/patches/post_install/manual_patch_to_update_gst_details.py#L17) patch manually.

You can do above for all set of accounts that you have. Afterwards,

- Transfer balances to new account (combined). Use only accounts from here for the future transactions.

---

Closing this issue, as no fix is required for this.

**Comment by amrit-citrusleaf** [comment]
Thanks for the help @vorasmit .

I will run the patch (the accounts shall remain the same as the accounts team is used to their incorrect name)
