### ISSUE TITLE
exception": "AttributeError: 'SubcontractingOrder' object has no attribute 'bill_to_gstin'"

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#2696]
### Information about bug

While Submit the Subcontracting Purchase Order.

### Version

ERPNext: v15.36.1 (version-15)

Frappe Framework: v15.42.0 (version-15)

Frappe Whatsapp: v1.0.7 (master)

Frappe HR: v15.29.0 (version-15)

InOutTrack: v0.0.1 (develop)

India Compliance: v15.13.3 (version-15)

Print Designer: v1.4.2 (main)

SBI: v0.0.2 (main)

### Relevant log output / Stack trace / Full Error Message.

```shell
Form/Purchase Order/SBI/PO/24-25/1668

### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 114, in application
    response = frappe.api.handle(request)
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1775, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/desk/form/save.py", line 37, in savedocs
    doc.submit()
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1048, in submit
    return self._submit()
  File "apps/frappe/frappe/model/document.py", line 1031, in _submit
    return self.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 390, in _save
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1131, in run_post_save_methods
    self.run_method("on_submit")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1304, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "apps/frappe/frappe/model/document.py", line 959, in fn
    return method_object(*args, **kwargs)
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 484, in on_submit
    self.auto_create_subcontracting_order()
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 638, in auto_create_subcontracting_order
    make_subcontracting_order(self.name, save=True, notify=True)
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
  File "apps/erpnext/erpnext/buying/doctype/purchase_order/purchase_order.py", line 871, in make_subcontracting_order
    target_doc.save()
  File "apps/frappe/frappe/model/document.py", line 337, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 359, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 291, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1091, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 962, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1322, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1306, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/subcontracting_transaction.py", line 183, in validate
    if validate_transaction(doc) is False:
  File "apps/india_compliance/india_compliance/gst_india/overrides/subcontracting_transaction.py", line 254, in validate_transaction
    SubcontractingGSTAccounts().validate(doc, True)
  File "apps/india_compliance/india_compliance/gst_india/overrides/subcontracting_transaction.py", line 285, in validate
    self.validate_for_same_party_gstin()
  File "apps/india_compliance/india_compliance/gst_india/overrides/subcontracting_transaction.py", line 291, in validate_for_same_party_gstin
    party_gstin = self.doc.get("supplier_gstin") or self.doc.bill_to_gstin
AttributeError: 'SubcontractingOrder' object has no attribute 'bill_to_gstin'

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"name\":\"SBI/PO/24-25/1668\",\"owner\":\"avinash.r@abc.com\",\"creation\":\"2024-11-11 11:27:00.569038\",\"modified\":\"2024-11-11 11:30:59.519890\",\"modified_by\":\"dinesh@addon-s.in\",\"docstatus\":0,\"idx\":0,\"title\":\"{supplier_name}\",\"naming_series\":\"SBI/PO/24-25/.####.\",\"supplier\":\"Swarup Das\",\"supplier_name\":\"Swarup Das\",\"transaction_date\":\"2024-11-11\",\"schedule_date\":\"2025-03-31\",\"company\":\"ABC Industries\",\"apply_tds\":0,\"is_reverse_charge\":0,\"is_subcontracted\":1,\"supplier_warehouse\":\"Third Party Jobwork - Swarup Das - SBI\",\"currency\":\"INR\",\"conversion_rate\":1,\"buying_price_list\":\"Standard Buying\",\"price_list_currency\":\"INR\",\"plc_conversion_rate\":1,\"ignore_pricing_rule\":0,\"total_qty\":300000,\"total_net_weight\":0,\"base_total\":600000,\"base_net_total\":600000,\"total\":600000,\"net_total\":600000,\"tax_withholding_net_total\":600000,\"base_tax_withholding_net_total\":600000,\"tax_category\":\"\",\"taxes_and_charges\":\"Input GST In-state - SBI\",\"base_taxes_and_charges_added\":0,\"base_taxes_and_charges_deducted\":0,\"base_total_taxes_and_charges\":0,\"taxes_and_charges_added\":0,\"taxes_and_charges_deducted\":0,\"total_taxes_and_charges\":0,\"base_grand_total\":600000,\"base_rounding_adjustment\":0,\"base_in_words\":\"INR Six Lakh only.\",\"base_rounded_total\":600000,\"grand_total\":600000,\"rounding_adjustment\":0,\"rounded_total\":600000,\"disable_rounded_total\":0,\"in_words\":\"INR Six Lakh only.\",\"advance_paid\":0,\"apply_discount_on\":\"Grand Total\",\"base_discount_amount\":0,\"additional_discount_percentage\":0,\"discount_amount\":0,\"other_charges_calculation\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto;\\\">\\n\\t<table class=\\\"table table-bordered table-hover\\\">\\n\\t\\t<thead>\\n\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-left\\\">HSN/SAC</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">Taxable Amount</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">CGST</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t<th class=\\\"text-right\\\">SGST</th>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\n\\t\\t\\t</tr>\\n\\t\\t</thead>\\n\\t\\t<tbody>\\n\\t\\t\\t\\n\\t\\t\\t\\t<tr>\\n\\t\\t\\t\\t\\t<td>998898</td>\\n\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t₹ 6,00,000.00\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(0.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 0.00\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t<td class=\\\"text-right\\\">\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t(0.0%)\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t\\t\\t₹ 0.00\\n\\t\\t\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\t\\t</td>\\n\\t\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t\\t\\n\\t\\t\\t\\t</tr>\\n\\t\\t\\t\\n\\t\\t</tbody>\\n\\t</table>\\n</div>\",\"gst_breakup_table\":\"<div class=\\\"tax-break-up\\\" style=\\\"overflow-x: auto\\\"><table class=\\\"table table-bordered table-hover\\\"><thead><tr><th class=\\\"text-left\\\">HSN/SAC</th><th class=\\\"text-right\\\">Taxable Amount</th><th class=\\\"text-right\\\">CGST</th><th class=\\\"text-right\\\">SGST</th></tr></thead><tbody><tr><td class=\\\"text-left\\\">998898</td><td class=\\\"text-right\\\">₹ 6,00,000.00</td><td class=\\\"text-right\\\">(0.0%)&nbsp;₹ 0.00</td><td class=\\\"text-right\\\">(0.0%)&nbsp;₹ 0.00</td></tr></tbody></table></div>\",\"supplier_address\":\"Swarup Das-Billing\",\"address_display\":\"37/1A/H/27,Cossipore Road,<br>Kolkata-700002<br>Kolkata\\nWest Bengal, State Code: 19 PIN Code: 700002 <br>India<br>\\n\",\"gst_category\":\"Unregistered\",\"shipping_address\":\"Shree Bhagwati Industries-Billing\",\"shipping_address_display\":\"Jalan Complex , Gate No.1 ,<br>Biprannapara , Domjur<br>Howrah\\nWest Bengal, State Code: 19 PIN Code: 711411 <br>India<br>\\nGSTIN: 19ANBPM8412A1ZC<br>\",\"billing_address\":\"Shree Bhagwati Industries-Billing\",\"billing_address_display\":\"Jalan Complex , Gate No.1 ,<br>Biprannapara , Domjur<br>Howrah\\nWest Bengal, State Code: 19 PIN Code: 711411 <br>India<br>\\nGSTIN: 19ANBPM8412A1ZC<br>\",\"company_gstin\":\"19ANBPM8412A1ZC\",\"place_of_supply\":\"19-West Bengal\",\"payment_terms_template\":\"30 Days\",\"tc_name\":\"Local Purchase Terms\",\"terms\":\"<div class=\\\"ql-editor read-mode\\\"><p>The material shall be supplied along with original Invoice and a Delivery Note.</p><p>Please take confirmation before sending materials.</p><p>Please maintain PO number, PO date and Item code in Invoice copy.</p><p><br></p></div>\",\"status\":\"Draft\",\"per_billed\":0,\"per_received\":0,\"group_same_items\":0,\"language\":\"en\",\"is_internal_supplier\":0,\"represents_company\":\"\",\"party_account_currency\":\"INR\",\"is_old_subcontracting_flow\":0,\"doctype\":\"Purchase Order\",\"pricing_rules\":[],\"taxes\":[{\"name\":\"0a0jv00dd3\",\"owner\":\"dinesh@addon-s.in\",\"creation\":\"2024-11-11 11:27:00.569038\",\"modified\":\"2024-11-11 11:30:59.519890\",\"modified_by\":\"dinesh@addon-s.in\",\"docstatus\":0,\"idx\":1,\"category\":\"Total\",\"add_deduct_tax\":\"Add\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"account_head\":\"Input Tax CGST - SBI\",\"description\":\"CGST\",\"is_tax_withholding_account\":0,\"rate\":0,\"gst_tax_type\":\"cgst\",\"cost_center\":\"Main - SBI\",\"tax_amount\":0,\"tax_amount_after_discount_amount\":0,\"total\":600000,\"base_tax_amount\":0,\"base_total\":600000,\"base_tax_amount_after_discount_amount\":0,\"item_wise_tax_detail\":\"{\\\"70JOBW02010013\\\":[0.0,0.0]}\",\"parent\":\"SBI/PO/24-25/1668\",\"parentfield\":\"taxes\",\"parenttype\":\"Purchase Order\",\"doctype\":\"Purchase Taxes and Charges\"},{\"name\":\"0a0juqv38c\",\"owner\":\"dinesh@addon-s.in\",\"creation\":\"2024-11-11 11:27:00.569038\",\"modified\":\"2024-11-11 11:30:59.519890\",\"modified_by\":\"dinesh@addon-s.in\",\"docstatus\":0,\"idx\":2,\"category\":\"Total\",\"add_deduct_tax\":\"Add\",\"charge_type\":\"On Net Total\",\"included_in_print_rate\":0,\"included_in_paid_amount\":0,\"account_head\":\"Input Tax SGST - SBI\",\"description\":\"SGST\",\"is_tax_withholding_account\":0,\"rate\":0,\"gst_tax_type\":\"sgst\",\"cost_center\":\"Main - SBI\",\"tax_amount\":0,\"tax_amount_after_discount_amount\":0,\"total\":600000,\"base_tax_amount\":0,\"base_total\":600000,\"base_tax_amount_after_discount_amount\":0,\"item_wise_tax_detail\":\"{\\\"70JOBW02010013\\\":[0.0,0.0]}\",\"parent\":\"SBI/PO/24-25/1668\",\"parentfield\":\"taxes\",\"parenttype\":\"Purchase Order\",\"doctype\":\"Purchase Taxes and Charges\"}],\"payment_schedule\":[{\"name\":\"07s54au0sr\",\"owner\":\"avinash.r@abc.com\",\"creation\":\"2024-11-11 11:27:00.569038\",\"modified\":\"2024-11-11 11:30:59.519890\",\"modified_by\":\"dinesh@addon-s.in\",\"docstatus\":0,\"idx\":1,\"payment_term\":\"30 Days\",\"description\":\"100% After 30 Days\",\"due_date\":\"2024-12-11\",\"mode_of_payment\":\"Wire Transfer\",\"invoice_portion\":100,\"discount_type\":\"Percentage\",\"discount_date\":\"2024-11-11\",\"discount\":0,\"payment_amount\":600000,\"outstanding\":600000,\"paid_amount\":0,\"discounted_amount\":0,\"base_payment_amount\":600000,\"parent\":\"SBI/PO/24-25/1668\",\"parentfield\":\"payment_schedule\",\"parenttype\":\"Purchase Order\",\"doctype\":\"Payment Schedule\"}],\"items\":[{\"name\":\"07lu38qs43\",\"owner\":\"avinash.r@abc.com\",\"creation\":\"2024-11-11 11:27:00.569038\",\"modified\":\"2024-11-11 11:30:59.519890\",\"modified_by\":\"dinesh@addon-s.in\",\"docstatus\":0,\"idx\":1,\"fg_item\":\"30PIPE01010009\",\"fg_item_qty\":300000,\"item_code\":\"70JOBW02010013\",\"item_name\":\"Jobwork Machining, 280mm Farrata Inner Pipe\",\"schedule_date\":\"2025-03-31\",\"item_group\":\"Services\",\"description\":\"<div><p>Jobwork Machining, 280mm Farrata Inner Pipe</p></div>\",\"gst_hsn_code\":\"998898\",\"is_ineligible_for_itc\":0,\"image\":\"\",\"qty\":300000,\"stock_uom\":\"Nos\",\"uom\":\"Nos\",\"conversion_factor\":1,\"stock_qty\":300000,\"price_list_rate\":2,\"last_purchase_rate\":2.5,\"base_price_list_rate\":2,\"margin_type\":\"\",\"margin_rate_or_amount\":0,\"rate_with_margin\":0,\"discount_percentage\":0,\"discount_amount\":0,\"base_rate_with_margin\":0,\"rate\":2,\"amount\":600000,\"gst_treatment\":\"Nil-Rated\",\"base_rate\":2,\"base_amount\":600000,\"pricing_rules\":\"\",\"stock_uom_rate\":2,\"is_free_item\":0,\"apply_tds\":1,\"net_rate\":2,\"net_amount\":600000,\"base_net_rate\":2,\"base_net_amount\":600000,\"taxable_value\":600000,\"igst_rate\":0,\"cgst_rate\":0,\"sgst_rate\":0,\"cess_rate\":0,\"cess_non_advol_rate\":0,\"igst_amount\":0,\"cgst_amount\":0,\"sgst_amount\":0,\"cess_amount\":0,\"cess_non_advol_amount\":0,\"warehouse\":\"Stores - SBI\",\"actual_qty\":0,\"company_total_stock\":0,\"delivered_by_supplier\":0,\"against_blanket_order\":0,\"blanket_order_rate\":0,\"received_qty\":0,\"returned_qty\":0,\"billed_amt\":0,\"expense_account\":\"Jobwork Charges - SBI\",\"include_exploded_items\":0,\"weight_per_unit\":0,\"total_weight\":0,\"cost_center\":\"Main - SBI\",\"is_fixed_asset\":0,\"item_tax_rate\":\"{}\",\"page_break\":0,\"parent\":\"SBI/PO/24-25/1668\",\"parentfield\":\"items\",\"parenttype\":\"Purchase Order\",\"doctype\":\"Purchase Order Item\"}],\"supplied_items\":[],\"__onload\":{\"supplier_tds\":\"TDS - 194C - Individual\",\"can_update_items\":true},\"__last_sync_on\":\"2024-11-11T06:04:14.310Z\"}",
		"action": "Submit"
	},
	"btn": {
		"jQuery370028212938677271551": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 388,
						"namespace": ""
					}
				]
			}
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "AttributeError: 'SubcontractingOrder' object has no attribute 'bill_to_gstin'",
	"exc_type": "AttributeError",
	"_exc_source": "india_compliance (app)"
}
```
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dineshpanchal93** [comment]
Note - This Supplier is Unregistered  - Non GST

**Comment by Ninad1306** [comment]
This issue is already fixed, kindly update your app.
