### ISSUE TITLE
E-waybill credentials not working

### ISSUE THREAD

**Issue by SvbZ3r0** [resilient-tech/india-compliance#2697]
### Information about bug

![image](https://github.com/user-attachments/assets/6609c9c5-af34-4565-a14e-fe699eee7012)

I promise, the credentials are correct. I have tried typing in the username and password. I have tried copying from Google Password Manager and pasting it here. The same credentials work on the ewaybill portal but don't work through india-compliance.
I don't know how to check the password hash in the db to verify if the password is being saved correctly.

There is a `/` in the password and I don't know if that is causing issues. In any case, if it turns out I've been incorrectly entering the credentials, I will close this immediately.

### Version

agriculture 0.0.1
ecommerce_integrations 1.20.1
erpnext 15.38.2
frappe 15.44.2
hrms 15.31.0
india_compliance 15.13.4
payments 0.0.1

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzMxYmU0M2U3Y2M1YTc4NTQyYTllNTciLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.VIHREy-H8O8C6lYKqNTSftieH9QsVUu-KXe2VZFY5zc">Huly&reg;: <b>IC-2822</b></a></sub>

**Comment by vorasmit** [comment]
Did you follow these instructions to setup the credentials:
https://docs.indiacompliance.app/docs/ewaybill-and-einvoice/gst_settings

**Comment by SvbZ3r0** [comment]
Yeah.. Definitely my fault. I was using my portal credentials. Sorry.

**Comment by SvbZ3r0** [comment]
It would be useful to have this info on the Credentials page of GST Settings.
