### ISSUE TITLE
e-Invoice Print Format Error

### ISSUE THREAD

**Issue by dev-barlota** [resilient-tech/india-compliance#270]
You can print the sales invoice with QR Code by entering following code in your print format:

```html
{% set e_invoice_log = frappe.db.get_value("e-Invoice Log", doc.irn, ("signed_qr_code"), as_dict=True) %}
<img src="data:image/png;base64,{{ get_qr_code(e_invoice_log.signed_qr_code, scale=2) }}" class="qrcode">
```

_Originally posted by @sagarvora in https://github.com/resilient-tech/india-compliance/issues/247#issuecomment-1243813442_

This throws a  ValueError: too many values to unpack (expected 2)

**Comment by sagarvora** [comment]
Duplicate. Let's continue this on the original thread please.
