### ISSUE TITLE
India Compliance with Frappe Cloud

### ISSUE THREAD

**Issue by jpettan** [resilient-tech/india-compliance#2729]
Hi,

I came across following message in the India compliance wiki page.

Bundled on Frappe Cloud
We recommend [Frappe Cloud](https://frappecloud.com/dashboard/signup?referrer=99df7a8f) for hosting your site. It comes bundled with India Compliance API features, providing free API access without requiring a purchase from the India Compliance app. For sites hosted outside of Frappe Cloud, credits must be purchased through the India Compliance app.

I have been using India compliance through Frappe cloud for the last 2 years. However I had to purchase credits recently. What should I do to activate the bundled api credits with Frappe Cloud?

Thanks,
Jithu Pettan

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzM4MmVmZGU3Y2M1YTc4NTQyZDNkMWYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.0b6ppSTjZz0MyNbuun8iNSxVSO0nW1E6Y9Q5yyrEO_E">Huly&reg;: <b>IC-2855</b></a></sub>

**Comment by ljain112** [comment]
You need to log out of the India Compliance Account to use Frappe bundled free APIs.

![image](https://github.com/user-attachments/assets/01310b48-d683-4e0c-9d11-c71272ff0d2f)
