### ISSUE TITLE
GST Inward Supply docs not created on GSTR2B Sync in Purchase Reconciliation Tool

### ISSUE THREAD

**Issue by innomalous** [resilient-tech/india-compliance#2740]
### Information about bug

Hello, we used the Purchase Reconciliation Tool as always to sync our GSTR2B return with ERPNext and reconcile against Purchase Invoices. The progressbar went green all the way but no success message was shown for a long time.

No data was updated in the tool.

However, it shows that the return for the period is updated (screenshot below).
![image](https://github.com/user-attachments/assets/1ba99f3a-b7f8-41b0-8adf-76792283e2d5)

There is also an integration request that shows data being received successfully.
![image](https://github.com/user-attachments/assets/30950163-a157-49e8-baa0-af55b25186aa)

However, no GST Inward Supply docs were created for the data received.

### Version

Frappe version: 15.47.2
ERPNext version: 15.41.2
India Compliance version: 15.13.5

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhZGIyZmU3Y2M1YTc4NTQyZGE4N2MiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.fcD2J9PHKSSVoc2qdCOR-X0okc3muiFPKusyYHHxkxI">Huly&reg;: <b>IC-2866</b></a></sub>

**Comment by ljain112** [comment]
resolved
https://github.com/resilient-tech/india-compliance/pull/2723
