### ISSUE TITLE
[Accounts] Error on Generate Button in GSTR-1 Beta After Updating india_compliance

### ISSUE THREAD

**Issue by hrishikesh8848** [resilient-tech/india-compliance#2741]
### Information about bug

After updating the india_compliance app from version v15.13.2 (HEAD) to v15.13.5 (version-15), clicking the "Generate" button in the GSTR-1 Beta report throws an error, and the data is not fetched.

Steps to Reproduce:
Update the india_compliance app to version v15.13.5 (version-15).
Navigate to Accounting > Compliance > GSTR-1 Beta.
Click on the "Generate" button to fetch data.
Observe the error and the absence of fetched data.

Error Details:

Uncaught TypeError: frm.taxpayer_api_call is not a function

### Version

ERPNext: v15.42.0 (version-15)

Frappe Framework: v15.47.2 (version-15)

Frappe HR: v15.26.0 (version-15)

India Compliance: v15.13.5 (version-15)

### Relevant log output / Stack trace / Full Error Message.

```shell
gstr_1_beta__js:204 Uncaught TypeError: frm.taxpayer_api_call is not a function
    at HTMLButtonElement.eval (gstr_1_beta__js:204:17)
    at HTMLButtonElement.<anonymous> (page.js:305:31)
    at HTMLButtonElement.dispatch (jquery.js:5135:27)
    at Rt.handle (jquery.js:4939:28)
eval	@	gstr_1_beta__js:204
(anonymous)	@	page.js:305
dispatch	@	jquery.js:5135
Rt.handle	@	jquery.js:4939
Show less
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzNhZGYwMWU3Y2M1YTc4NTQyZGE4ZGUiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0._oonbTmUUvLxpy4kndEYFHJxmrr8yqS4ZlRjya9Pb38">Huly&reg;: <b>IC-2867</b></a></sub>

**Comment by vorasmit** [comment]
Looks like JS assets are not loaded correctly.
`bench build` should help. Alternatively update the app and try again.

**Comment by vorasmit** [comment]
Please feel free to reopen this issue or a new issue if the issue still persists
