### ISSUE TITLE
Add FSSAI License fields to Company DocType for Indian compliance

### ISSUE THREAD

**Issue by azharumar** [resilient-tech/india-compliance#2809]
### Is your feature request related to a problem? Please describe.

Currently, there is no dedicated field to store and display FSSAI License details in the Company DocType's registration details section. FSSAI License number is a mandatory requirement for food businesses in India and needs to be displayed on various business documents and reports. Having to manually add this information each time or store it in custom fields creates inconsistency and additional work.

### Describe the solution you'd like

Add the following fields under Company DocType > Print Settings > Registration Details section:

FSSAI License Number (Data type: Data)
FSSAI License Valid From (Data type: Date)
FSSAI License Valid Until (Data type: Date)

These fields should:

Be available for printing on standard documents like Sales Invoice, Purchase Order, etc.
Include validation for the standard FSSAI license number format
Show a warning when the license is about to expire (30 days before expiry)

### Describe alternatives you've considered

Using Custom Fields - While this works, it doesn't provide a standardized solution across installations

### Additional context

FSSAI License is a regulatory requirement for food businesses in India
The license number follows a standard 14-digit format
This information needs to be printed on various business documents and packaging

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzRlOGRkYWQyZWY0Y2JjYzQ2ZGEzMjMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.7D8UCAsLRedxoal6MT_Y5DA43ovgKtLbvy1Gq5qkPY4">Huly&reg;: <b>IC-2935</b></a></sub>

**Comment by Sanket322** [comment]
You can use the GST Tax Invoice print format and customize it by adding your own fields. In the Company DocType > Print Settings > Registration Details section, you can either select from the suggested options or add your own custom options as needed. These fields will dynamically reflect in the print format.

Example of added fields in Registration Details:

<img width="1055" alt="Screenshot 2024-12-05 at 6 00 48 PM" src="https://github.com/user-attachments/assets/16ef3f2a-c22c-45ea-a96e-b630b764f111">

Example of how it appears in the print format:

<img width="790" alt="Screenshot 2024-12-05 at 6 00 14 PM" src="https://github.com/user-attachments/assets/bf61d90d-025b-4f21-ba7d-26bff1e88860">

You can read more about this feature here: [Print Format Setup](https://docs.indiacompliance.app/docs/configuration/gst_setup#print-format)
