### ISSUE TITLE
GSTR-1 System Failure error when downloading CDNR - Random 

### ISSUE THREAD

**Issue by jpettan** [resilient-tech/india-compliance#2827]
### Information about bug

Following error pops up when we try to generate gstr1 report using gstr1 beta.

<img width="1366" src="https://github.com/user-attachments/assets/0d59688d-cd7b-4fc3-a6b7-7a027ea85532" alt="image">

### Version

Frappe version - 15.49.1
Erpnext - 15.45.0
India compliance- 15.14.2

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzU2YjNiOTFlMDYzMmRkMDhlMjc2N2QiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.f_B03PBtYOLhbE8QDut5YMvs20zR5hOPvBBey1rLHrQ">Huly&reg;: <b>IC-2953</b></a></sub>

**Comment by vorasmit** [comment]
Can you please check error logs or error in Integration Request? This is too little information for us to help you further.

**Comment by jpettan** [comment]
<img width="837" alt="image" src="https://github.com/user-attachments/assets/0c77235b-ae49-4b53-aa8f-6f40294e03f0" />

Please find the screenshot of the error that we found in the integration request page.

**Comment by vorasmit** [comment]
https://taxguru.in/goods-and-service-tax/gst-portal-common-errors-suggested-solutions.html

This should have been a temporary issue with the GST Portal. Are you now able to generate GSTR-1 now? If not, you may connect with GST Portal help desk.

There is very little we can do about this.

**Comment by jpettan** [comment]
Tried again and the results are same for November 2024. 
Also an observation - a large number of integration requests were created when we used gstr-1 beta.

We used the gstr1 feature instead of gstr1-beta and filed for November 2024.

**Comment by vorasmit** [comment]
GSTR-1 is expected to use many APIs, as for fetching data, (for reconciling), API call needs to be made for each section for GSTR-1 (say B2B etc).

GST Portal Help Desk could only help on this.

**Comment by jpettan** [comment]
Just tried again for November 2024 using gstr1-beta.

Around 170 integration requested got created. There is no failure of integration request. Also there is no error message on gstr1 page.

But following is unusual.

<img width="1366" alt="image" src="https://github.com/user-attachments/assets/d645e11e-8e35-465e-8fc6-f1e75873defa" />

Also had a look into the requests. Only the request Id is different, rest of the content is same.

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/f1674313-5c63-40d1-8c43-556c86807584" />


Sharing our observations with you. Hope this will be helpful.

**Comment by vorasmit** [comment]
> Around 170 integration requested got created.

You can expect about 15 requests for generating GSTR-1. 170 requests shouldn't have happened in one go. Could be because of retrying to generate again?

If not, it could be useful if you can help us replicate this issue, preferably create a new issue for the same.
