### ISSUE TITLE
Invalid depends on  Expression

### ISSUE THREAD

**Issue by viralkansodiya** [resilient-tech/india-compliance#2907]
### Information about bug

we have recently updated the version on latest

we are facing error, when we are trying to open Stock Entry and Subcontracting Order

<img width="1438" alt="Screenshot 2024-12-27 at 2 38 37 PM" src="https://github.com/user-attachments/assets/fe12a9dd-b2dc-42b3-97b8-6c5bef606fce" />

This Error is appear because of wrong eval condition

<img width="1438" alt="Screenshot 2024-12-27 at 2 42 23 PM" src="https://github.com/user-attachments/assets/a15230f6-3df9-4aef-90df-b8ba1b305a48" />

<img width="1438" alt="Screenshot 2024-12-27 at 2 46 48 PM" src="https://github.com/user-attachments/assets/d7e30c13-76df-4379-ad87-c18bd2068669" />

Even if we disable the e-waybill feature, the error still appears.

After removing this dependency on the expression, the errors no longer appear.

Please help us to resolve this

### Version

Frappe Version :- v15.50.1 (version-15)
Erpnext Version :- v15.46.1 (version-15) 
India_compliance :- v15.14.5 (version-15)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ninad1306** [comment]
Try `bench build` and `bench migrate`

If still issue persists, let us know.

**Comment by mohsinalimat** [comment]
> Try `bench build` and `bench migrate`
> 
> If still issue persists, let us know.

I tried this one and It works.

**Comment by Ninad1306** [comment]
> Try `bench build` and `bench migrate`
> 
> If still issue persists, let us know.

Resolved with this solution.
