### ISSUE TITLE
I am Unable to Download GSTR 2B reports from my ERP Next .. Pls help Urgently 

### ISSUE THREAD

**Issue by Evergreenfoods** [resilient-tech/india-compliance#2909]
I am Unable to Download GSTR 2B reports from my ERP Next .. Pls help Urgently

Rahul Anam
9867045888

<sub><a href="https://huly.app/guest/resilienttech?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzZmYWY4ZmYxNDRmNTg1YWU1MTM0OWMiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6Inctc21pdHZvcmEyMDMtcmVzaWxpZW50dGVjLTY2N2U0MjkxLWEwNWMwNjY4N2EtNjM4MjY3In0.cCavBuUZRNTBaX9wmI0HyOePlMOmm0CpGXLSsyHVlcg">Huly&reg;: <b>IC-3036</b></a></sub>

**Comment by Ninad1306** [comment]
Issue related to JS assests. 

Resolved by executing `bench build`
