### ISSUE TITLE
Error while Installation

### ISSUE THREAD

**Issue by tdlworld** [resilient-tech/india-compliance#305]
Hi, 
Running this command
bench get-app https://github.com/resilient-tech/india-compliance.git

Getting this error.

clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
✘ [ERROR] No matching export in "node_modules/vue-router/dist/vue-router.esm.js" for import "createRouter"

    ../india_compliance/india_compliance/public/js/india_compliance_account/router.js:1:9:
      1 │ import { createRouter, createWebHistory } from 'vue-router';
        ╵          ~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/vue-router/dist/vue-router.esm.js" for import "createWebHistory"

    ../india_compliance/india_compliance/public/js/india_compliance_account/router.js:1:23:
      1 │ import { createRouter, createWebHistory } from 'vue-router';
        ╵                        ~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/vuex/dist/vuex.esm.js" for import "createStore"

    ../india_compliance/india_compliance/public/js/india_compliance_account/store/index.js:1:9:
      1 │ import { createStore } from 'vuex'
        ╵          ~~~~~~~~~~~

✘ [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "createApp"

    ../india_compliance/india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js:1:9:
      1 │ import { createApp } from "vue";
        ╵          ~~~~~~~~~

 ERROR  There were some problems during build

Error: Build failed with 4 errors:
../india_compliance/india_compliance/public/js/india_compliance_account/india_compliance_account.bundle.js:1:9: ERROR: No matching export in "node_modules/vue/dist/vue.runtime.esm.js" for import "createApp"
../india_compliance/india_compliance/public/js/india_compliance_account/router.js:1:9: ERROR: No matching export in "node_modules/vue-router/dist/vue-router.esm.js" for import "createRouter"
../india_compliance/india_compliance/public/js/india_compliance_account/router.js:1:23: ERROR: No matching export in "node_modules/vue-router/dist/vue-router.esm.js" for import "createWebHistory"
../india_compliance/india_compliance/public/js/india_compliance_account/store/index.js:1:9: ERROR: No matching export in "node_modules/vuex/dist/vuex.esm.js" for import "createStore"
    at failureErrorWithLog (/home/anant13admin/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1600:15)
    at /home/anant13admin/frappe-bench/apps/frappe/node_modules/esbuild/lib/main.js:1246:28
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Terminated
error Command failed with exit code 143.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

What could be the reason?

**Comment by sagarvora** [comment]
I think you've installed the wrong version? Please refer to this post:
https://discuss.erpnext.com/t/india-compliance-changes-to-branching-and-versioning/95783

We had to create the `version-14` branch, so if you're trying to setup an installation with the `version-14` branches of frappe and erpnext, you will have to use that.

I am closing this issue for now, but feel free to comment here if it's still unresolved.

**Comment by tdlworld** [comment]
I have these Installations
erpnext 14.3.0
frappe 14.11.1
hrms 1.0.0
payments 0.0.1

**Comment by sagarvora** [comment]
You need to call the `get-app` command with the `--branch` flag like so:
```
bench get-app https://github.com/resilient-tech/india-compliance.git --branch version-14
```
