### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by rknroot** [resilient-tech/india-compliance#312]
While creating new customer 429 Too Many Requests was popping up

<img width="576" alt="image" src="https://user-images.githubusercontent.com/9102676/196749225-c73cdc5a-1d48-413c-852c-9913d538c8a8.png">

**Comment by sagarvora** [comment]
Can you share a traceback?

**Edit:** You may also find more info in the Integration Request DocType.

**Comment by sagarvora** [comment]
Okay. I was able to replicate this issue. It's a bit weird. The other APIs are working (we tested e-Waybill). But only the GSTIN search API seems to be failing. Looks like the GSTN is throttling requests for this API as of now.

**Comment by rknroot** [comment]
<img width="1292" alt="image" src="https://user-images.githubusercontent.com/9102676/196850369-0d4009c6-c438-4f76-98a4-1c5bb7278c69.png">

**Comment by sagarvora** [comment]
@rkr00t It seems to be resolved now. Can you try again?

---

I am closing this issue for now, but feel free to comment here if it persists - I will reopen it.

**Comment by rknroot** [comment]
@sagarvora Hi, Same error is popping up again...

**Comment by sagarvora** [comment]
> @sagarvora Hi, Same error is popping up again...

We've raised this issue with the upstream provider, and their contention is that they get a limited quota of Public API requests. So we're still trying to figure out how to best circumvent this. Apologies for the inconvenience. I will reopen this issue until we can figure out a proper fix.

**Comment by rknroot** [comment]
Ok, this happens only during customer/supplier creation but not frequently.

**Comment by sagarvora** [comment]
> Ok, this happens only during customer/supplier creation but not frequently.

FWIW, you should still be able to create customer / supplier, although manually. The feature is more of an addon rather than a blocking requirement.

**Comment by vorasmit** [comment]
Closing as not occurred recently.
