### ISSUE TITLE
e-Invoice and e-Waybill Logs are not generating

### ISSUE THREAD

**Issue by hafeez3000** [resilient-tech/india-compliance#314]
Upon invoice submission, both e-invoice and e-waybills are auto-generated successfully, but e-Invoice and e-Waybill Logs are not creating.

Installed Apps
ERPNext: v14.3.1
Frappe Framework: v14.12.0
India Compliance: v14.0.1
Payments: v0.0.1

![e-Invoice_Log](https://user-images.githubusercontent.com/805214/197397256-c7a6ad66-abde-403a-9308-af8119d37847.jpg)

**Comment by sagarvora** [comment]
It looks like your Redis queue processes may not be running like they're supposed to. To ensure that logs always get generated without putting load on the web processes, we [enqueue](https://github.com/resilient-tech/india-compliance/blob/next/india_compliance/gst_india/utils/e_waybill.py#L384) their generation. Kindly check the Background Jobs page to ascertain whether or not the relevant jobs are getting processed.

**Comment by sagarvora** [comment]
Since this isn't related to the app's development, I am closing this issue for now. If you need further help with this, consider emailing us or posting on the [community forum](https://discuss.erpnext.com/c/erpnext/india-compliance/65).
