### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by QuakeString** [resilient-tech/india-compliance#318]
Hi, I've just upgraded ERPNext to v14 and when I try to install the India-compliance it gives me errors.
![2022-10-28_13-24](https://user-images.githubusercontent.com/5375918/198534627-d0cbffad-b907-4aa7-9ee5-6a004a4ab660.png)

**Comment by sagarvora** [comment]
You're installing the wrong branch of India Compliance. Use the `version-14` branch, just like you would for ERPNext.

There are other closed duplicate issues like this. Please search first.
