### ISSUE TITLE
India Compliance Account showing Error

### ISSUE THREAD

**Issue by sowndharya998** [resilient-tech/india-compliance#322]
-while opening the  India compliance account showing Failed to Fetch error

![Screenshot 2022-11-05 at 10 52 35 AM](https://user-images.githubusercontent.com/75109236/200104048-95a4bafc-3768-45a8-966c-55474b2ce25e.png)

**Comment by sagarvora** [comment]
Please share the console log for more info. You can also email us about this issue here:
```
hello at indiacompliance dot app
```

**Comment by sowndharya998** [comment]
VM6481:1 TypeError: Cannot read properties of undefined (reading 'exc_type')
    at ic.gst_api.call (<anonymous>:2399:1502)
    at async ee.fetchDetails (<anonymous>:2203:1779)

**Comment by sagarvora** [comment]
I think we'll need more info to get to the root of this. Try the following instructions, but consider emailing us if they don't help.

- Logout of the India Compliance page by running the following command:
```
bench execute india_compliance.gst_india.page.india_compliance_account.logout
```

- Visit the India Compliance Account page and try logging in again.

**Comment by sagarvora** [comment]
@sowndharya998 please comment here if the issue still persists. Closing for now.

**Comment by sowndharya998** [comment]
This Issue Fixed Thank You
