### ISSUE TITLE
2273 : Dispatch from PIN code cannot be 999999 when generating Einvoice for sales return for  "SupTyp": "EXPWOP"

### ISSUE THREAD

**Issue by rjbharath1003** [resilient-tech/india-compliance#323]
Request Data :
{
    "BuyerDtls": {
        "Addr1": "Eastern Seaboard Industrial Estate   ",
        "Addr2": "xxxxxxxxxxx ",
        "Gstin": "URP",
        "LglNm": "xxxxxxxxxxxxxx,
        "Loc": "xxxxxxxxxxxxx",
        "Pin": 999999,
        "Pos": "96",
        "Stcd": "96",
        "TrdNm": "xxxxxxxxxxxx"
    },
    "DispDtls": {
        "Addr1": "xxxxxxxxxxxx   ",
        "Addr2": "xxxxxxxxxxxx ",
        "Loc": "A.Pluadaeng Rayong",
        "Nm": "xxxxxxxxxxxx",
        "Pin": 999999,
        "Stcd": "96"
    },
    "DocDtls": {
        "Dt": "26/10/2022",
        "No": "20223545-1",
        "Typ": "CRN"
    },
    "EwbDtls": {
        "Distance": 0
    },
    "ItemList": [
        {
            "AssAmt": 385834.75,
            "CesAmt": 0,
            "CesNonAdvlAmt": 0,
            "CesRt": 0,
            "CgstAmt": 0,
            "Discount": 0,
            "GstRt": 0.0,
            "HsnCd": "39232100",
            "IgstAmt": 0,
            "IsServc": "N",
            "PrdDesc": "xxxxxxxxxxxx - 3 x 60 meter - 300  - UV",
            "Qty": 24.0,
            "SgstAmt": 0,
            "SlNo": "1",
            "TotAmt": 385834.75,
            "TotItemVal": 385834.75,
            "Unit": "NOS",
            "UnitPrice": 16076.448
        }
    ],
    "PayDtls": {
        "CrDay": 0,
        "PaidAmt": 0,
        "PaymtDue": 385834.75
    },
    "RefDtls": {
        "PrecDocDtls": [
            {
                "InvDt": "26/10/2022",
                "InvNo": "20223545"
            }
        ]
    },
    "SellerDtls": {
        "Addr1": "xxxxxxxxxxxx",
        "Addr2": "xxxxxxxxxxxx",
        "Gstin": "xxxxxxxxxxxx",
        "LglNm": "xxxxxxxxxxxx",
        "Loc": "Chennai",
        "Pin": 600069,
        "Stcd": "33",
        "TrdNm": "xxxxxxxxxxxx"
    },
    "ShipDtls": {
        "Addr1": "xxxxxxxxxxxx",
        "Addr2": "xxxxxxxxxxxx",
        "Gstin": "xxxxxxxxxxxx",
        "LglNm": "xxxxxxxxxxxx",
        "Loc": "xxxxxxxxxxxx",
        "Pin": 600069,
        "Stcd": "33",
        "TrdNm": "xxxxxxxxxxxx"
    },
    "TranDtls": {
        "RegRev": "N",
        "SupTyp": "EXPWOP",
        "TaxSch": "GST"
    },
    "ValDtls": {
        "AssVal": 385834.75,
        "CesVal": 0,
        "CgstVal": 0,
        "Discount": 0,
        "IgstVal": 0,
        "OthChrg": 0.0,
        "RndOffAmt": -0.0,
        "SgstVal": 0,
        "TotInvVal": 385834.75,
        "TotInvValFc": 4659.84
    },
    "Version": "1.1"
}

Response
Output
{
    "message": "2273 : Dispatch from PIN code cannot be 999999",
    "success": false
}
Error
2273 : Dispatch from PIN code cannot be 999999

**Comment by vorasmit** [comment]
Hello,

We request you to try this.

Create a new address for the customer (in India) where the material shall be loaded (Say customs / Madras Port).
Use that in the shipping address (becomes dispatch address for credit note) for the credit note.

Please let us know if you still face the issue.

**Comment by vorasmit** [comment]
Is this still an issue? If not, request you to please close the same.

**Comment by sagarvora** [comment]
Closing for now. Feel free to comment here if the issue persists, we will reopen it.
