### ISSUE TITLE
Request Data for e-Invoice

### ISSUE THREAD

**Issue by HnSSiva** [resilient-tech/india-compliance#324]
We notice the Request Data for e-Invoice section goes with  wrong values:

 "ValDtls": {
        "AssVal": 212400.0,
        "CesVal": 0,
        "CgstVal": 0,
        "Discount": 0,
        "IgstVal": 0,
        "OthChrg": 0.0,
        "RndOffAmt": 0.0,
        "SgstVal": 0,
        "TotInvVal": 212400.0
    },

In this the "AssVal" is Total value including SGST(9%) and CGST (9%). The actual should be as follows:

 "ValDtls": {
        "AssVal": **180000.0**,
        "CesVal": 0,
        "CgstVal": **16200.0**,
        "Discount": 0,
        "IgstVal": 0,
        "OthChrg": 0.0,
        "RndOffAmt": 0.0,
        "SgstVal": **16200.0**,
        "TotInvVal": 212400.0
    },

Please support.

**Comment by vorasmit** [comment]
What is the GST Account configuration in GST Settings?

Tax amounts are calculated based on GST Account configuration from GST Settings. If you are using a different account for GST, it won’t be able to calculate GST correctly.

**Comment by vorasmit** [comment]
Closing: https://discuss.erpnext.com/t/e-invoice-request-data/96985/2

**Comment by HnSSiva** [comment]
Thanks after re-configuring the actual account heads it worked
