### ISSUE TITLE
 Uncaught TypeError: (0 , import_vue.defineComponent) is not a function

### ISSUE THREAD

**Issue by vignesh235** [resilient-tech/india-compliance#325]
### **Now I am currently exploring India compliance for e-way bill integration in my future projects. But this below error stops me to take the next steps.**
![issue](https://user-images.githubusercontent.com/95606753/200296681-3eea0f57-b3e4-46a0-bf58-98698ec62f6e.gif)

**Comment by ankush** [comment]
Post all versions. If on develop branch then last commits. 


You're likely running mismatching versions :sweat_smile:

**Comment by vignesh235** [comment]
> Post all versions. If on develop branch then last commits.
> 
> You're likely running mismatching versions sweat_smile

![image](https://user-images.githubusercontent.com/95606753/200299014-e3891317-3f91-42b6-a28e-0dde1aeba8f8.png)

**Comment by vignesh235** [comment]
> Post all versions. If on develop branch then last commits.
> 
> You're likely running mismatching versions sweat_smile

![image](https://user-images.githubusercontent.com/95606753/200299275-72adf11b-5fef-49b1-bd6c-f3d97b446698.png)

**Comment by sagarvora** [comment]
@vignesh235 You need the version-14 branch instead.

Refer https://discuss.erpnext.com/t/india-compliance-changes-to-branching-and-versioning/95783
