### ISSUE TITLE
Bill to Ship To Feature Request 

### ISSUE THREAD

**Issue by vishdha** [resilient-tech/india-compliance#346]
![image](https://user-images.githubusercontent.com/6947417/203223725-b476625b-9d96-44b2-9dbf-25b41ad2c3e4.png)

1. DropShip - for External supplier
3. Dropship with Sister company or Child Company - for Sister company possible with dropship
4. but Company with multiple branch drop ship will not effective solution. Need handle branch with bill to ship to feature 
https://cleartax.in/s/how-to-determine-the-place-of-supply-in-case-of-bill-to-ship-to-transactions

**Comment by vorasmit** [comment]
https://docs.erpnext.com/docs/v13/user/manual/en/accounts/articles/gst-for-multiple-branches

A branch with a different GSTIN is a customer or supplier. Hence, dropship should work in a very similar way as it works in the existing scenarios.

There are options to choose the shipping and dispatch address from the Sales Invoice and appropriate e-Waybill and e-Invoices are also generated.

The place of supply is determined correctly (as per the link you have shared), and taxes are validated accordingly.

Can you elaborate on the problem, and how it can be resolved in India Compliance?

**Comment by vishdha** [comment]
Example. We get PO from Flipkart and we create SO from Delhi but our shipment happend trough indore. in this case company asking the a solution for multiple branch. One customer tax invoice should created and 2 internal tax invoice should created

**Comment by vorasmit** [comment]
There should only be one invoice for internal transfer (from Indore to Delhi).
The second Invoice is to be created for Flipkart from Delhi.

Are you referring to automation for an internal/external invoice (as a feature)?

This should be a custom solution and this cannot be generalised.
There are many variables that go into the generation of an Invoice, and it's a legal document. Hence it's best if it's customised for the customer who needs this.
