### ISSUE TITLE
Export GSTR-3B in excel format

### ISSUE THREAD

**Issue by ram-chandu** [resilient-tech/india-compliance#362]
Hi Team,

Facing the following issue in GSTR- 3B in Indian compliance, Currently the GSTR-3B is exported in PDF or J-son format. Can we get the GSTR-3B report in excel format as it is required to check the quaterly data etc. Here export in Excel format is required to do tax computations on quarterly basis using GSTR 3B data. Please check the feasibility and let us know if this can be taken up. 

Thanks,
Ram.

**Comment by vorasmit** [comment]
Hi Ram,

Can you be more specific about what kind of report you are looking for?
It would be easier to understand the requirement with an example.

**Comment by ram-chandu** [comment]
Hi Vorasmit,

Here we expecting the GSTR-3B report in Excel format, currently its available in PDF and J-son format. 
We required this in excel format as we need to do tax computations on quarterly basis etc using GSTR 3B data.
![Screenshot from 2022-11-30 15-50-26](https://user-images.githubusercontent.com/119317369/204771992-92a9a6dd-46ad-43af-b23d-c1c32f425b14.jpg)

**Comment by smbcatalyst** [comment]
Hi Smit,

Have you worked on Excel report? Clients ask for the details from where the values are coming in 3B PDF report to cross check the details. It is getting very difficult to show the details of 3B. 1 of clients asked the details of RCM value as all JVs and PIs amount was not matching value with 3B pdf report values. Till time we are unable to find out the difference. Kindly provide excel report for 3B.

**Comment by vorasmit** [comment]
closed with: https://github.com/resilient-tech/india-compliance/pull/847
