### ISSUE TITLE
IRN details in E-way bill print format

### ISSUE THREAD

**Issue by ishanloya** [resilient-tech/india-compliance#382]
When an e-way bill generated from ERPNext is downloaded from the portal, IRN details (IRN, Ack No. & Ack. Date) are mentioned on the e-way bill.
In the current print format of the e-way bill however, the IRN details aren't there.
Is it possible to get these on the e-way bill?

**Comment by vorasmit** [comment]
Are you referring to the print format generated from the Tally? (It's the custom tally format with all details)

I agree with you on the following.

- IRN can be added to the e-Waybill print format
- e-Waybill Number can be added to e-Invoice Print Format

Ack No and Ack Date is not part of the official e-Waybill print format and can be ignored.
