### ISSUE TITLE
eWayBill not generated during Bulk Submit of Sales Invoices

### ISSUE THREAD

**Issue by ganz007** [resilient-tech/india-compliance#413]
When we bulk submit sales invoices in ERPNext, only the topmost invoice has its eWaybill generated. Rest are ignored.

**Comment by vorasmit** [comment]
More information is needed for this.

- Share error log with traceback if generated
- Share error response from Integration Request if that's the case

If you don't have any of the above, most likely e-Waybill was not applicable for other Invoices. Check Applicability.

**Comment by ganz007** [comment]
You are correct. Its working fine. In the earlier situation, there was an error in the Pincode field due to which the ewaybill was not generated.
