### ISSUE TITLE
Issue generating eway bill

### ISSUE THREAD

**Issue by rtdany10** [resilient-tech/india-compliance#423]
![WhatsApp Image 2022-12-27 at 5 52 01 PM](https://user-images.githubusercontent.com/52111700/209666085-2ae510f6-c3eb-4fbb-9aaa-bc9bb138c56b.jpeg)

**Comment by rtdany10** [comment]
https://github.com/resilient-tech/india-compliance/blob/38e66fe78cdc99826b6ad98d36fca56a024355d1/india_compliance/gst_india/utils/e_waybill.py#L838-L839

Wrapping them in int() or float() would fix the issue.

**Comment by vorasmit** [comment]
Hello,

This is already fixed and released here.
https://github.com/resilient-tech/india-compliance/pull/418

Thanks for reporting.
