### ISSUE TITLE
remove gst state and state number fields

### ISSUE THREAD

**Issue by sagarvora** [resilient-tech/india-compliance#43]
## Reason to propose a change

- Duplication of Data.
- This field is now being auto-set from the backend, and user have no control over it.
- Now there is no dependency on this field once state field is made auto-complete.
- Added Advantage: Future changes to state-codes will not require patch

## Dependency

- Currently `gst_state_number` is being used to set Place of Supply 
- Places where GSTIN Info is being fetch from Address, `gst_state_number` is used.

## Solution

- We have achieved consistency in state, by keeping it auto-complete for India.
- State number can be fetch from this state at all places where gst state number was used.

**Comment by vorasmit** [comment]
GST State No is part of the Address template and is used extensively in print formats. So this would be a breaking change.
