### ISSUE TITLE
india_compliance has started throwing error due to update of VueJS to version 4

### ISSUE THREAD

**Issue by yogeshvachhani** [resilient-tech/india-compliance#430]
Hi,

Existing installation of ERPNext with india_compliance has started throwing errors as the Route method has changed drastically.

Can you please look into this and update the code accordingly.

Regards,

**Comment by sagarvora** [comment]
- [There is no VueJS v4](https://vuejs.org/about/releases.html) (yet).
- Kindly refer to [our announcement about changes to branching and versioning](https://discuss.erpnext.com/t/india-compliance-changes-to-branching-and-versioning/95783).

This issue will be closed since it isn't a bug / feature request. You can still comment here though.

**Comment by yogeshvachhani** [comment]
Hi,

Installed apps in my Instance of ERPNext are:

ERPNext: v14.12.0 (version-14)
Frappe Framework: v14.21.1 (version-14)
Frappe HR: v1.0.0 (develop)
Payments: v0.0.1 (develop)

I am still getting this error when I use the command: `bench get-app --branch version-14 https://github.com/resilient-tech/india-compliance.git`

<pre><b>yarn run v1.22.19</b>
<font color="#AAAAAA">$ node esbuild --production --apps india_compliance --run-build-command</font>
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
clean: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration
<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;getCurrentInstance&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:9:
<font color="#D0CFCC">      6 â”‚ import { </font><font color="#26A269">getCurrentInstance</font><font color="#D0CFCC">, inject, onUnmounted, onDeactivated, onActivated, computed, unref, watchEffect, defineComponent, reac...</font>
<font color="#D0CFCC">        â•µ          </font><font color="#26A269">~~~~~~~~~~~~~~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;inject&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:29:
<font color="#D0CFCC">      6 â”‚ import { getCurrentInstance, </font><font color="#26A269">inject</font><font color="#D0CFCC">, onUnmounted, onDeactivated, onActivated, computed, unref, watchEffect, defineComponent, reac...</font>
<font color="#D0CFCC">        â•µ                              </font><font color="#26A269">~~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;onUnmounted&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:37:
<font color="#D0CFCC">      6 â”‚ import { getCurrentInstance, inject, </font><font color="#26A269">onUnmounted</font><font color="#D0CFCC">, onDeactivated, onActivated, computed, unref, watchEffect, defineComponent, reac...</font>
<font color="#D0CFCC">        â•µ                                      </font><font color="#26A269">~~~~~~~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;onDeactivated&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:50:
<font color="#D0CFCC">      6 â”‚ import { getCurrentInstance, inject, onUnmounted, </font><font color="#26A269">onDeactivated</font><font color="#D0CFCC">, onActivated, computed, unref, watchEffect, defineComponent, reac...</font>
<font color="#D0CFCC">        â•µ                                                   </font><font color="#26A269">~~~~~~~~~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;onActivated&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:65:
<font color="#D0CFCC">      6 â”‚ ...{ getCurrentInstance, inject, onUnmounted, onDeactivated, </font><font color="#26A269">onActivated</font><font color="#D0CFCC">, computed, unref, watchEffect, defineComponent, reactive...</font>
<font color="#D0CFCC">        â•µ                                                              </font><font color="#26A269">~~~~~~~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;computed&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:78:
<font color="#D0CFCC">      6 â”‚ ...Instance, inject, onUnmounted, onDeactivated, onActivated, </font><font color="#26A269">computed</font><font color="#D0CFCC">, unref, watchEffect, defineComponent, reactive, h, provide...</font>
<font color="#D0CFCC">        â•µ                                                               </font><font color="#26A269">~~~~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;unref&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:88:
<font color="#D0CFCC">      6 â”‚ ..., inject, onUnmounted, onDeactivated, onActivated, computed, </font><font color="#26A269">unref</font><font color="#D0CFCC">, watchEffect, defineComponent, reactive, h, provide, ref, w...</font>
<font color="#D0CFCC">        â•µ                                                                 </font><font color="#26A269">~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;watchEffect&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:95:
<font color="#D0CFCC">      6 â”‚ ...onUnmounted, onDeactivated, onActivated, computed, unref, </font><font color="#26A269">watchEffect</font><font color="#D0CFCC">, defineComponent, reactive, h, provide, ref, watch, shal...</font>
<font color="#D0CFCC">        â•µ                                                              </font><font color="#26A269">~~~~~~~~~~~</font>

<font color="#C01C28">âœ˜ </font><span style="background-color:#C01C28"><font color="#C01C28">[</font></span><span style="background-color:#C01C28"><font color="#FFFFFF">ERROR</font></span><span style="background-color:#C01C28"><font color="#C01C28">]</font></span> <b>No matching export in &quot;node_modules/vue/dist/vue.runtime.esm.js&quot; for import &quot;defineComponent&quot;</b>

    ../../../node_modules/vue-router/dist/vue-router.esm-bundler.js:6:108:
<font color="#D0CFCC">      6 â”‚ ...Deactivated, onActivated, computed, unref, watchEffect, </font><font color="#26A269">defineComponent</font><font color="#D0CFCC">, reactive, h, provide, ref, watch, shallowRef, nextTic...</font>
<font color="#D0CFCC">        â•µ                                                            </font><font color="

**Comment by sagarvora** [comment]
I think you're trying to use Vue 3.

Frappe and India Compliance v14 only support Vue 2. To use Vue 3, upgrade to Frappe `develop` branch and corresponding `next` branch for India Compliance.

If you don't need Vue 3, ensure your Frappe installation is clean and run the following command:
```
bench setup requirements --node
```

If you still need help, consider emailing us for paid support at the following email:

```
hello at indiacompliance dot app
```

**Comment by yogeshvachhani** [comment]
Hi,

I am a laymen and don't know how to use VueJS at all.

My Frappe installation is clean.

Here is the output of the command you suggested - `bench setup requirements --node`
```:~/erp14$ bench setup requirements --node
Updating node packages...

Installing node dependencies for frappe
$ yarn install
yarn install v1.22.19
[1/5] Validating package.json...

[2/5] Resolving packages...
success Already up-to-date.
Done in 1.51s.

Installing node dependencies for erpnext
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.65s.
```
Now the most surprising thing is that the App on our remote server is working perfectly and if we use that code then it is getting installed and is working like a Charm!!

This is what is confusing me.

One more thing if we ignore the errors at time of `bench get-app` and install India Compliance the whole UI get jumbled up and looking something like this.
![image](https://user-images.githubusercontent.com/109499572/210570497-e26353da-8684-4891-b328-5e62f58870f6.png)

I am attaching the file here for your reference.

[india_compliance(WorkingOnServer).zip](https://github.com/resilient-tech/india-compliance/files/10344625/india_compliance.WorkingOnServer.zip)

Thank you.

**Comment by sagarvora** [comment]
The version you're using in the attached file is outdated - it's using the older unsupported `develop` branch. Consider using the latest `version-14` branches of Frappe, ERPNext and India Compliance.

If you still need help, consider emailing us at the email address I mentioned in the previous comment.
