### ISSUE TITLE
Multiple Items with Multiple tax rates in one purchase / sales invoice?

### ISSUE THREAD

**Issue by nitin-anantpranali** [resilient-tech/india-compliance#440]
How can we use multiple Items with multiple tax rates in one purchase / sales invoice?

**Comment by sagarvora** [comment]
Since this isn't related to the app's development (bug/feature request), I am closing this issue. If you need help with this, consider emailing us at _hello at indiacompliance dot app_ for paid support or posting on the [community forum](https://discuss.frappe.io/c/erpnext/india-compliance/65).
