### ISSUE TITLE
Error in POS Invoic while saving.

### ISSUE THREAD

**Issue by nitin-anantpranali** [resilient-tech/india-compliance#457]
### Information about bug

Hi,

I an getting following error when I try to make POS Invoice

AttributeError: 'POSInvoice' object has no attribute 'is_reverse_charge'

What could be the cause?

### Version

"erpnext": "14.4.0",
"frappe": "14.13.0",
"hrms": "1.0.0",
"india_compliance": "14.0.2",
"payments": "0.0.1"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Please upgrade your India Compliance installation to the latest stable release. This issue has been [solved](https://github.com/resilient-tech/india-compliance/pull/395) in `v14.0.6`.
