### ISSUE TITLE
error - Company GSTIN is a mandatory field for GST Transactions - 

### ISSUE THREAD

**Issue by hpalrecha** [resilient-tech/india-compliance#461]
While raising Sales or purchase invoice in V14, this error is coming - Company GSTIN is a mandatory field for GST Transactions

**Comment by sagarvora** [comment]
Please ensure that you've set the GSTIN field in the company you're making transactions for.

Also, since this doesn't qualify as a bug / feature request, the [discussion forum](https://discuss.frappe.io/c/erpnext/india-compliance/65) is better suited for such queries.
