### ISSUE TITLE
Not able to book Purchase Invoice for unregistered and local vendor with IGST 

### ISSUE THREAD

**Issue by DipenFrappe** [resilient-tech/india-compliance#463]
### Information about bug

When import purchase is done companies get the IGST input which generally comes in CHA invoice or custom department and these suppliers are unregistered vendors or local vendors but the system doesn't allow booking IGST invoices.

One more use case for booking IGST is for getting input against Script DGFT

### Version

ERPNext Version - 14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Import transactions are required to be separated into 2 parts.

- Import of Goods or Services (without GST)
- Customs Invoice

When importing, GST is required to be paid separately to the customs department and a separate document is received for the same. This cannot be a part of the original purchase as it wasn't charged by the vendor.

Journal Entry for GST payment is recommended for now.
- Customs a/c debit (expense)
- Input a/c debit
- Bank a/c credit

We can work on automating this by having an add-on to Import Purchases (maybe using a dialog).

**Comment by DipenFrappe** [comment]
We are creating separate PI for GST input and custom duty payment and the issue is earlier in this invoice user was able to add IGST manually to take the input which is not happening now because of new validation.
