### ISSUE TITLE
System is not allowing to set separate ledger of RCM Input ledgers

### ISSUE THREAD

**Issue by DipenFrappe** [resilient-tech/india-compliance#464]
### Information about bug

Few customers create and maintain separate ledgers for RCM Inputs and not using the normal Input ledger for RCM. Earlier system was allowing in GST settings and purchase invoices to set separate ledgers for RCM input but now after the update, the IC app is allowing only one ledger for input in the GST setting and purchase invoice and because of this users are getting below validation message.

![image](https://user-images.githubusercontent.com/123350348/213973378-811e5855-7293-436d-ade8-48a856fe6ff3.png)

 

### Version

ERPNext and IC app version - 14

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Why are you maintaining multiple RCM accounts? How is it helping you?

**Comment by vorasmit** [comment]
A similar issue was raised on Frappe Issues.
Resolved this by merging Input RCM with Input accounts.
