### ISSUE TITLE
Automatically Add Taxes and Charges from Item Tax Template == Check Box is false  for "https://kayagar.frappe.cloud/app/accounts-settings/Accounts%20Settings"

### ISSUE THREAD

**Issue by VARDHANA87** [resilient-tech/india-compliance#471]
Automatically Add Taxes and Charges from Item Tax Template == Check Box is false 

<img width="974" alt="image" src="https://user-images.githubusercontent.com/79317458/217474722-c57eb3da-f754-452c-adfa-93f83f910d98.png">

**Comment by sagarvora** [comment]
Please refer to https://github.com/resilient-tech/india-compliance/issues/146 to learn why this was done. Please follow [contribution guidelines](https://github.com/resilient-tech/india-compliance#contributing) when creating issues.

If you have further comments / need clarifications on above issue, please continue the discussion in #146 itself.
