### ISSUE TITLE
Showing state None in some e-wayBill 

### ISSUE THREAD

**Issue by Govind-Jangid** [resilient-tech/india-compliance#472]
### Information about bug

![image](https://user-images.githubusercontent.com/63184660/218153470-3052f8dc-17c6-4f4e-90ea-258d5ebaa39f.png)

### Version

![image](https://user-images.githubusercontent.com/63184660/218153962-0de555bc-1442-4ef3-a46f-6284be608304.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
This has been fixed here: https://github.com/resilient-tech/india-compliance/pull/387

It will be released in a couple of days.
