### ISSUE TITLE
Tax And Charges Template Not Getting Auto Fetched Based Tax Category Selected In Supplier and Customer Master and Address

### ISSUE THREAD

**Issue by DipenFrappe** [resilient-tech/india-compliance#473]
### Information about bug

Tax And Charges Template Not Getting Auto Fetched Based Tax Category Selected In Supplier and Customer Master and Address

1 Tag Tax Category In Sales/Purchase Tax Template
2 Tag Same Tax Category In Customer/supplier
3 In PO/SO after selecting the Customer/supplier tax category and tax template should get auto fetched 
Tax Category coming but Tax Template Not Coming automatically.

### Version

ERPNext and IC app latest v14 version 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
https://github.com/frappe/erpnext/pull/34372
