### ISSUE TITLE
API request made again when details are already fetched

### ISSUE THREAD

**Issue by jalajc** [resilient-tech/india-compliance#474]
### Information about bug

We noticed that while creating customer details and supplier details if the details are fetched, they are fetched again while slight variation or saving.
Because of this unnecessary API credits are used for fetching the same information which is already fetched by API.
Ideally, expected behavior is cache the response of API call (for supplier and customer details) for at least a week, or until a forced refresh is made to avoid unnecessary use of API. 

### Version

Frappe 14
ERPNext 14
India API 14.1.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Agreed.

We plan to do this enhancement to avoid making unnecessary API calls.
