### ISSUE TITLE
"party_details.is_reverse_charge" doesn't exist.

### ISSUE THREAD

**Issue by jugalnet** [resilient-tech/india-compliance#477]
### Information about the bug

https://github.com/resilient-tech/india-compliance/blob/510dab761a91a2f8a0c7332a826afe63ade242e0/india_compliance/gst_india/overrides/transaction.py#L535

`party_details.is_reverse_charge` value is always Flase in the corresponding if statement because `party_details.is_reverse_charge` doesn't exist in the `party_details` object. As a result, manually created tax rules from within erpnext for chosing the correct Purchase Taxes and Charges Template gets overridden by the following statement in the subsequent block of code since the if condition evaluates to true for parties without a GST number.

https://github.com/resilient-tech/india-compliance/blob/510dab761a91a2f8a0c7332a826afe63ade242e0/india_compliance/gst_india/overrides/transaction.py#L543

### Version

ERPNext and IC app version-14 and next

### Steps to reproduce

Set breakpoints at the above mentioned lines, create a purchase invoice with an unregistered supplier, and check the values of the local variables.

### Pending PR

#454 

### Comments

The workaround I'm currently using to have my tax rules for RCM apply is removing the above statement altogether since my deployment is tightly controlled and doesn't require such stringent code validation.

I'm willing to provide a pull request to fix this bug if we can reach a collective consensus on how we should go about fixing it, because I believe that the fix involves an crucial design decision which must be taken after some discussion.

**Comment by jugalgalaxyz** [comment]
#454

**Comment by vorasmit** [comment]
closed with #822
