### ISSUE TITLE
System unable to book PI against register and unregister supplier with Tax IGST

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#497]
**IGST Tax Bug**

While import purchase is done companies get the IGST input which generally comes in CHA invoice or custom department and these suppliers are unregistered / register but the system doesn't allow booking IGST tax PI.

How to booking IGST is for getting input against Script DGFT, Customer don't want book JV for book this charges they want book PI only

Version- ERPNext: v14.15.1 (HEAD)
Frappe Framework: v14.25.1 (HEAD)
India Compliance: v14.1.2 (HEAD)

<img width="743" alt="IGST Issue" src="https://user-images.githubusercontent.com/119041865/223705650-4ebf1e06-c602-491f-bac1-a94f1b983e3d.png">

<img width="644" alt="image" src="https://user-images.githubusercontent.com/119041865/223706178-66ee78a5-ea62-4d0a-b496-300d00946164.png">

**Comment by vorasmit** [comment]
Duplicate: #463
