### ISSUE TITLE
When making PI against Input Tax RCM GL not allow by system

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#498]
### Information about bug

RCM GL Bug

Customer want to maintain separate RCM GL for Input & Output Tax but now system not allowing Input RCM GL, show below error

<img width="880" alt="image" src="https://user-images.githubusercontent.com/119041865/223910738-f90cd1a7-7376-46cb-8a99-5314e78ed57f.png">

And we go on GST Setting and adding RCM GL against Reverse Charge below error show

<img width="815" alt="image" src="https://user-images.githubusercontent.com/119041865/223911392-acd31c9b-f4a2-4dbc-ba46-fb644a5a65f0.png">

 

### Version

Frappe Framework: v14.25.1 (HEAD)
ERPNext: v14.15.1 (HEAD)
India Compliance: v14.1.2 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
What is Output RCM GL used for?
Why is the customer maintaining the same? It's not required to be accounted for as far as I understand (If it's meant for sales RCM).

**Comment by vorasmit** [comment]
Duplicate: #464 

Please continue the comments there.

**Comment by RJMHASKE** [comment]
Customer need to keep RCM receivable and payable amt. in separate GL, RCM Input GL is Debited and RCM Output GL is Credited.

So how we can do this?
