### ISSUE TITLE
Item Tax Template not working when set Tax Category in Supplier & Customer Tax details and Address

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#499]
### Information about bug

Item Tax Template Bug

Item Tax Template not working when set Tax Category in Supplier & Customer Tax details and Address

1. Supplier Tax Category details

<img width="922" alt="image" src="https://user-images.githubusercontent.com/119041865/223914673-ae0fb340-99df-41e5-8ef1-0d452e128307.png">

2. Supplier Address Tax Category details

<img width="810" alt="image" src="https://user-images.githubusercontent.com/119041865/223914864-19a164a8-fe28-45b4-81a8-c4f1b5c9e158.png">

3. Item level Item tax template details

<img width="809" alt="image" src="https://user-images.githubusercontent.com/119041865/223915020-bb2eafda-ae23-43a5-89f0-bbec910de0d8.png">

4. Purchase Tax Template

<img width="860" alt="image" src="https://user-images.githubusercontent.com/119041865/223915152-f44bbb09-2e86-423a-a78f-cb72eca3d014.png">

5. While Creating Purchase order Tax applying but Item Tax template not coming and tax not calculating

<img width="726" alt="image" src="https://user-images.githubusercontent.com/119041865/223915399-deccd689-fcd2-4236-96be-77d570c39df0.png">

6. Item Tax Template showing blank

<img width="818" alt="image" src="https://user-images.githubusercontent.com/119041865/223915568-d85b8197-7f56-47b6-a650-454b4c34b948.png">

7. After save Purchase order tax calculating nill

<img width="825" alt="image" src="https://user-images.githubusercontent.com/119041865/223915829-34b4acf5-3fd5-42ad-90b8-67be4b727e61.png">

### Version

Frappe Framework: v14.25.1 (HEAD)
ERPNext: v14.15.1 (HEAD)
India Compliance: v14.1.2 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
As you are using tax category, you need to have different item tax templates as per tax category, and specify the same in Item (Screenshot 3). It will then auto-populate in transactions.
