### ISSUE TITLE
Sales Invoice List not working

### ISSUE THREAD

**Issue by jecinthamary** [resilient-tech/india-compliance#505]
### Information about bug

**Sales Invoice List view not working**
Its shown console error please refer the below lines,

Uncaught (in promise) TypeError: ic.is_e_invoice_enabled is not a function
 at frappe.listview_settings.<computed>.onload (sales_invoice__list_js:808:12)
 at frappe.views.ListView.setup_view (list_view.js:294:41)

### Version

Frappe Framework: v14.27.0 (version-14)
ERPNext: v14.18.2 (version-14)
India Compliance: v14.2.1 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Closing as duplicate of https://github.com/resilient-tech/india-compliance/issues/203. The fix for this issue has been merged into the `develop` branch, pending release.

**Comment by sagarvora** [comment]
The fix has been release in v14.3.0, please try it out.

**Comment by jecinthamary** [comment]
@sagarvora Thanks for the update.
