### ISSUE TITLE
Autofill party information by entering their GSTIN

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#522]
Hello,

Autofill party information by entering their GSTIN is not working for me.
![image](https://user-images.githubusercontent.com/111174201/225598876-7ee0eb0c-0eaf-4898-8100-ae69e384c3a3.png)
![image](https://user-images.githubusercontent.com/111174201/225598899-3ff7f226-54f6-402a-9037-44ef73208a1f.png)

Thanks

**Comment by vorasmit** [comment]
Most likely sandbox might be enabled in GST Settings. Can you please check this once?

**Comment by precihole** [comment]
Hello Sir,

Yes, it is enabled.
![image](https://user-images.githubusercontent.com/111174201/226091065-9f3296c3-f17a-465a-8a77-be8d0617f5a9.png)

Thanks & Regards,
Midhat Ayesha Shaikh

**Comment by sagarvora** [comment]
In Sandbox mode, only one GSTIN is allowed: **33GSPTN9771G3ZP**. To use all GSTINs, you'll need to disable sandbox mode.

Note: even though API request fails, you should still be able to save the customer.

**Comment by precihole** [comment]
Thanks for your help @sagarvora @vorasmit
