### ISSUE TITLE
Validate HSN/SAC Code in Sales Items and Transactions

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#534]
### Is your feature request related to a problem? Please describe.

We need Validate HSN/SAC Code in Sales Items and Transactions so the Minimum HSN/SAC Code Digits should be 8

### Describe the solution you'd like

<img width="757" alt="image" src="https://user-images.githubusercontent.com/111174201/229056176-c97bcc75-be05-4c3a-b777-8cdb936e2ead.png">
As you have already provided the validation on Minimum HSN/SAC Code Digits but it only have 4 and 6 but we need 8 to as per out company scenario

**Comment by vorasmit** [comment]
Hello,

We may not support this feature as SAC codes have a maximum of 6 digits and also, it's not a requirement as per the law. 
Ideally, a simple customization at your end can add this additional validation.
