### ISSUE TITLE
Issue In Indian Compliance

### ISSUE THREAD

**Issue by SrushtiShah26** [resilient-tech/india-compliance#542]
We are facing issues while purchasing credits in the Indian compliance module in Erpnext. How to solve this issue?

**Issue:** requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.cashfree.com/pg/orders

**Comment by sagarvora** [comment]
Hi @SrushtiShah26,

Apologies for the inconvenience. This issue happens if you ERP instance isn't able to connect with our payments provider for some reason. Please email us on the following email for further resolution:

`hello at indiacompliance dot app`

**Comment by sagarvora** [comment]
Since this doesn't qualify as a bug, I am closing this issue for now. Please note that you can still respond to this issue in it's closed state, but it'd be preferable if you email since this issue concerns the API service rather than the app itself.

Thanks.

**Comment by sagarvora** [comment]
@SrushtiShah26
@riddhisolanki001

Awaiting your email at the following email:
`hello at indiacompliance dot app`

Please also share a traceback of the issue if available (from the browser console).
