### ISSUE TITLE
Audit Trail Reports

### ISSUE THREAD

**Issue by JitendraSAW** [resilient-tech/india-compliance#546]
### Information about bug

Currently, the system generates two different reports that are intended to provide an overview of the Audit Trail. However, I have found that these reports do not provide a clear and comprehensive picture of the Audit Trail. As a result, it becomes challenging for us to review the Audit Trail effectively. Presently in ERPNext we have to refer 2 Reports as below
1. Activity Log
2. Versions History

See the Sample of Versions History and that somewhere Data History Output comes in to the XML Format and does not show in the same column who is the User Name
<img width="947" alt="image" src="https://user-images.githubusercontent.com/80260184/229454830-0c1951f8-5593-4fef-b86a-d052658584f0.png">

And some of the Audit Trial we have to check from the Activity Log which also does not give a very intendend information.
<img width="803" alt="image" src="https://user-images.githubusercontent.com/80260184/229455538-fdfb4dca-4ac3-4ba6-9639-2cbe9c25926c.png">

We need in a Below Type of Screen which can be convered in to the Report of Excel, this is really giving the expected and desired output
![image](https://user-images.githubusercontent.com/80260184/229457484-a5189145-6a9b-4ad1-9cce-017359075fdc.png)
![image](https://user-images.githubusercontent.com/80260184/229459022-98086158-2504-428d-8dfe-90be9af86c36.png)
![image](https://user-images.githubusercontent.com/80260184/229459250-e3168d8f-5ac3-485e-83cc-ea75e3a026af.png)
![image](https://user-images.githubusercontent.com/80260184/229460344-f7638390-77a2-466c-9148-c6b9ec1c155f.png)
![image](https://user-images.githubusercontent.com/80260184/229460649-fdb8d13e-d393-4717-9b60-41ec3f5ed300.png)

Hence such Kind of Screen Design can be done though you may decide on  UI and Reports, but it should capture all the relveant fields and information in 1 Report with User Name, Document Name Changes, Timesstamp, Machine Changes and Old History and New Changes History. Please refer the above screen which I have shared 
   
Though presently you have just provided under the Account Settings Enable Audit Trial but this is not enough as the Auditor will defintely require such type of above reports to ensure the Audit Trial Compliance

Please consider this Request as a Very Critical Priority.

### Version

![image](https://user-images.githubusercontent.com/80260184/229466775-5b2370eb-65a8-444c-913d-06608c947992.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
- Activity Log is not considered to be part of Audit Trail, Version and GL Entry are enough. User name and timestamp of change made is available in the `owner` and `creation` timestamp of the version, visible in the sidebar:
  
  ![image](https://user-images.githubusercontent.com/16315650/229493404-d90e6a00-a478-48c7-afb5-e3d6e88d2b4f.png)

- The report you're looking for is easily achievable by querying on the Version table (Report Builder?). You can filter by User, DocType, Creation Timestamp, etc. I agree that a built-in report that provides this is a good enhancement, but it is by no means critically required. Not if you review the relevant [MCA notification](https://www.mca.gov.in/Ministry/pdf/AccountsAmendmentRules_24032021.pdf). There is a requirement of being able to record edit logs, but there is no imposition on what kind of reports are available to view such logs. Every software implements features differently. Still, you can definitely confirm this with your legal team / CA. We're happy to accept sponsorship for this enhancement if you're interested in that.
