### ISSUE TITLE
Issue in PO after adding India Compliance module

### ISSUE THREAD

**Issue by nakul80** [resilient-tech/india-compliance#555]
### Information about bug

When i tried to enter the details in the GST Settings Accounts Tab, I had to create new accounts for GST input as earlier I was using single account for GST input and output 

After making new accounts following error is there

![image](https://user-images.githubusercontent.com/64956588/229737171-61ba2660-5869-41e3-8978-523c02a2a840.png)

### Version

ERPNext: v14.20.0 (HEAD)
Frappe Framework: v14.30.0 (HEAD)
India Compliance: v14.4.0 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Hi Nakul,

We've seen similar reports before. Please check the following:
- Does the Supplier Address have GST Category and State set?
- Is the Place of Supply set in the transaction (Address tab)?
- Is the company GSTIN showing correctly in the transaction (Address tab)?


---

This is unlikely to be a bug. If it is found to be a bug, we will re-open the issue and add the relevant label. Till then it will remain in closed state, although we can still discuss it.

**Comment by nakul80** [comment]
my transaction is Purchase Order

My supplier address has GST category and state set to Maharashtra
Place of Supply showing same i.e. Maharashtra
Company GSTIN also showing number starting with 27

Actually it should never enter the conditional section as seen here since transaction is not interstate
[https://github.com/resilient-tech/india-compliance/blob/b1e037d214d76189f3f7dfc13470eb01f1e83305/india_compliance/gst_india/overrides/transaction.py#L353:~:text=or%20SGST%20account-,if,),-%23%20Intra%20State%20supplies]

**Comment by sagarvora** [comment]
What is the GST category?

> Place of Supply showing same i.e. Maharashtra

To be very accurate, the place of supply is supposed to be `27-Maharashtra`. Is that not the case?


> Actually it should never enter the conditional section as seen here since transaction is not interstate

If you're comfortable with technical debugging, try printing the following values inside in the `is_inter_state_supply` function to see why it's happening:

```
print(doc.gst_category, doc.place_of_supply[:2], get_source_state_code(doc))
```

If not, consider emailing us for paid support call.

**Comment by nakul80** [comment]
Hi 
Yes showing 27-Maharashtra

My account is hosted by frappe cloud so how can i debug?

**Comment by sagarvora** [comment]
> My account is hosted by frappe cloud so how can i debug?

You can try using System Console. If you need further assistance, please consider emailing us for paid support.

**Comment by nakul80** [comment]
I am not sure how to use System Console. If you could please guide. It seems to be a small issue.

**Comment by nakul80** [comment]
I figured out the issue I think. If try to save the transaction the Place of Supply changes (possibly during validation) to the following
![image](https://user-images.githubusercontent.com/64956588/229801828-745b5c55-fb46-450e-abda-9ba4c1ffbe78.png)

**Comment by sagarvora** [comment]
You probably have **Fetch From** in your custom fields for Place of Supply.

**Comment by nakul80** [comment]
Yes thats right. Thank you Sagar.
