### ISSUE TITLE
Payment Entry Issue in Multi Currency Transactions- Advance payment done in one exchange rate and PI book in diff. exchange rate

### ISSUE THREAD

**Issue by RJMHASKE** [resilient-tech/india-compliance#561]
### Information about bug

Information About Bug

While doing purchase transaction in multi currency with advance payment made with one exchange rate and after material receipt exchange rate changed that time payment entry issue

1. My company base currency is INR and I have made Purchase order in USD with exchange rate- 80 USD.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/119041865/229978775-c3d47795-51f7-48f8-84ad-1ef5384d0484.png">

2. I have made 50% advance payment against this PO to Supplier with exchange rate 80 USD

<img width="832" alt="image" src="https://user-images.githubusercontent.com/119041865/229978920-194cbec5-4f6b-4c1f-8bee-d77283c96d2f.png">

3. Material receipt at our company but exchange rate changed , I have made purchase receipt against this PO with exchange rate- 82 USD

<img width="843" alt="image" src="https://user-images.githubusercontent.com/119041865/229979961-0e5591fd-95e5-4e8a-abea-636a11b55915.png">

4. Chart of A/C Shows correct value for advance payment before material receipt and PI booking

<img width="816" alt="image" src="https://user-images.githubusercontent.com/119041865/229980221-ee8d009d-cea5-433d-bc7c-fd84d3d21603.png">

5. Purchase Invoice booked against purchase receipt with exchange rate 82 USD and advance payment entry link to PI (exchange rate 80 USD for advance payment)

<img width="862" alt="image" src="https://user-images.githubusercontent.com/119041865/229980542-a0d03d5e-3753-4e1c-88c5-fba2b843af44.png">

6. In Chart of A/C Creditor A/c show 487.80 USD/41000.00INR and In Exchange gain & loss - 1000 INR (system auto calculate advance payment exchange gain & Loss amount which is correct ) but USD amount wrong

<img width="797" alt="image" src="https://user-images.githubusercontent.com/119041865/229981173-5af91d25-f9bc-430a-8851-cb8da47e31c7.png">

7. Supplier Ledger & Trial Balance report

<img width="813" alt="image" src="https://user-images.githubusercontent.com/119041865/229981380-2861e79c-4a49-4bcb-89d3-1f9ccc07ed87.png">
<img width="810" alt="image" src="https://user-images.githubusercontent.com/119041865/229981568-dc5a34a3-e5fc-432a-8cc8-33dd31649ae8.png">

8. In Purchase Invoice advance paid 500 USD & Pending amount 487.80 USD

<img width="857" alt="image" src="https://user-images.githubusercontent.com/119041865/229982415-1e0f3c5c-5949-43fe-9242-3709e54b1e22.png">

9. I have making pending amount payment entry against booked PI

<img width="846" alt="image" src="https://user-images.githubusercontent.com/119041865/229982150-b7f39d7f-6a15-49f6-9f7d-bbef1ff0ed67.png">

10. I have manual change pending amount 41000 INR and set 1000 INR in Exchange gain & loss A/c

<img width="562" alt="image" src="https://user-images.githubusercontent.com/119041865/229983619-16dd690b-8419-4c33-b0c6-266ae3e65480.png">

11. Trial Balance & Supplier Ledger show 1000 INR balance

<img width="668" alt="image" src="https://user-images.githubusercontent.com/119041865/229983780-0647b7fb-18d5-4cc1-b032-5a559645c1a0.png">
<img width="673" alt="image" src="https://user-images.githubusercontent.com/119041865/229983842-3ebd2329-89c3-4b19-8c22-a094ad5402eb.png">

12. Chart of A/c GL Creditor USD- Zero and In INR 1000 Pending and Exchange gain & Loss GL - Zero

<img width="786" alt="image" src="https://user-images.githubusercontent.com/119041865/229983971-4965bebb-5e00-4b29-8195-49a6a8460a93.png">

So please request check this issue

### Version

Frappe Framework: v14.29.2 (HEAD)
ERPNext: v14.19.0 (HEAD)
India Compliance: v14.4.0 (HEAD)
Payments: v0.0.1 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
@RJMHASKE This issue has nothing to do with India Compliance. Kindly open in [ERPNext](https://github.com/frappe/erpnext).

**Comment by RJMHASKE** [comment]
Thanks for reply will open in ERPNext github
