### ISSUE TITLE
E-Invoice is giving error when additional discount is applied or -ve sales taxes and charges in Sales Invoice

### ISSUE THREAD

**Issue by sjain17** [resilient-tech/india-compliance#580]
### Information about bug

E-Invoice is giving error when the additional discount is applied on Grand Total with enable discount accounting option or -ve charges are added in sales invoice, then system popups a validation - 

5002 : The field Other Charges must match the regular expression '^\d+.?\d{0,2}$'., 5002 : The field Other Charges must be between 0 and 99999999999999.98.

How to handle additional discounts in e-invoices? 

### Version

ERPNext: v14.12.1 (version-14)
Frappe Framework: v14.22.1 (version-14)
India Compliance: v14.1.1 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sjain17** [comment]
Also, it is not allowing me to apply a discount on NET Total as well which is very strange.

**Comment by vorasmit** [comment]
Can you update the India compliance app and check if this error continues?
Can you please share the integration request log if the error still persists?

- Go to Sales Invoice (where this error occurred)
- Go to connections and linked Integration Request
- Identify the e-Invoice request where this error occurred and share it with us for further inspection.

You may email us the log on api-support@indiacompliance.app if it contains sensitive information.

**Comment by sjain17** [comment]
Yes, I have updated the modules as well - 

ERPNext: v14.20.3 (version-14)
Frappe Framework: v14.31.0 (version-14)
India Compliance: v14.5.2 (version-14)

Still, the error remains the same. Also e-invoice is not getting generated to there is no integration log list.

**Comment by vorasmit** [comment]
Hello,

Thanks for reporting. We will fix this issue.
This was not introduced, as the discount on the net total is automatically adjusted with the item's taxable values.

Generally speaking, you end up paying more output tax if you give a discount like the way you are giving. Is there any specific reason for such a practice?

**Comment by sjain17** [comment]
Also, if check this option "Is Cash or Non Trade Discount" then system asks you to provide the chart of account and it debits the account against some amount. 

GST liability to Govt is neitther decreasing nor increasing but the discount on grand total is something that business is looking for and it was working fine till version 13.

**Comment by vorasmit** [comment]
Hello, can you please share the Sample Invoice JSON or screenshots for us to replicate the issue? 

Have you checked this option ("Is Cash or Non Trade Discount")? Because if you do, this issue could arise. Also, you end up paying more taxes.

**Comment by sjain17** [comment]
Yes, I have checked the "Is Cash or Non Trade Discount" and also updated the Discount Account. 
I have 3 different methods to achieve this -

 1. Added an item in Sales Invoice Item with -ve rate and qty as 1.
 2. Added a row in the taxes child table with on actual, account, and amount as -ve.
 3. Added Additional Discount on Grand Total, with Is Cash or Non Trade Discount=1 and amount = 100 (example).

However, all the above cases failed in the same error msg. 

Also when we talk about paying more taxes is a business requirement. As we want to give a discount on the total invoice but the customer is allowed to take full credit for taxes and we are also paying complete taxes to govt. so ethically it is not wrong at all. 

PS: This requirement arises because I want to return the freight amount to the customer because it was on to pay basis, as a token of appreciation to the customer I don't him to pay the freight. So actually the customer will pay the freight but he gets the discount in the same invoice. Hope this will help you understand it better.

**Comment by sjain17** [comment]
This is still not fixed completely, I am getting errors when adding a -ve sales taxes and charges. The system allowed to submit the invoice but the e-invoice is not generated and threw the same error again.

**Comment by vorasmit** [comment]
Hello,

-ve amount in the items table or other charges doesn't always mean a discount (could be TDS), and we cannot have a functionality assume that.

Currently, any charge other than tax in the taxes table goes as other charges. So your discount is considered as other charges and hence this error.

Also, for the items table, Govt doesn't accept -ve taxable value, and hence it has been converted as +ve and sent.

Considering we already have the functionality to have an additional discount on the invoice, it's best to use it the core way and we plan to support it.

Hope you understand and are satisfied with the current functionality.

For other instances, it's usually not clear or cannot be generalised if its a discount.

**Comment by sjain17** [comment]
Hello Smit, I can understand that the -ve amount is not always a discount but it also it can't be TDS as it is a Sales Invoice.  Also, as per ERPNext standard functionality, it allows us to -ve rate in case of regular invoices (is return=0) 
and sales taxes and charges as well. However, the business required is still to provide other charges as -ve and not as a discount.

Lastly, all three cases I have explained earlier are not discounts but trying to achieve the same functionality.

Thank you for making the additional work for e-invoicing, I used the Additional Discount option after the update and it is working fine.

**Comment by vorasmit** [comment]
Case1: 
If a Sales Invoice Item has a -ve rate, how should it be treated for e-Invoice (as it's not acceptable to govt)? Can it be generalised? 

Case2:
-ve in Other Charges is not a problem as long as it's net positive. However, if it's net -ve, how do you think it should be handled as Govt doesn't accept -ve other charges? Can it be generalised?

We want to support as many logical cases as possible, but it should be compatible with Govt requirements and we should be able to generalise it for all.
