### ISSUE TITLE
Eway Bill is showing wrong transaction type before and after generation

### ISSUE THREAD

**Issue by sjain17** [resilient-tech/india-compliance#589]
### Information about bug

The eway bill json shows transaction type 1 (Regular) for Same Bill to and Ship to address; however, after generating eway bill it shows as transaction type 4 (Combination of 2 and 3). I have checked the address, GSTIN number and GST State as well. 

I have tried generating the eway bill manually and found the issue with India Compliance, on GST Portal with same information it is generating the correct eway bill.

### Version

ERPNext: v14.20.3 (version-14)
Frappe Framework: v14.31.0 (version-14)
Frappe HR: v1.0.0 (develop)
India Compliance: v14.5.2 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
Won't be able to publish the JSON here as it is confidential with GST details of the business.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Please share the relevant logs and examples to replicate the issue. You can remove sensitive information.

**Comment by sjain17** [comment]
{"name":"691550312503","owner":"user@demo.com","creation":"2023-04-12 16:20:28.125267","modified":"2023-04-12 16:20:28.718991","modified_by":"user@demo.com","docstatus":0,"idx":0,"e_waybill_number":"691550312503","created_on":"2023-04-12 16:20:00","reference_doctype":"Sales Invoice","reference_name":"SAL/AHM/00002","is_cancelled":0,"is_latest_data":1,"data":"{\n    \"VehiclListDetails\": [],\n    \"actFromStateCode\": 24,\n    \"actToStateCode\": 24,\n    \"actualDist\": 202,\n    \"cessNonAdvolValue\": 0.0,\n    \"cessValue\": 0.0,\n    \"cgstValue\": 4961.0,\n    \"docDate\": \"12/04/2023\",\n    \"docNo\": \"SAL/AHM/F/00002\",\n    \"docType\": \"INV\",\n    \"ewayBillDate\": \"12/04/2023 04:20:00 PM\",\n    \"ewbNo\": 691550312503,\n    \"extendedTimes\": 0,\n    \"fromAddr1\": \"C/o Dummy Trade Services, 22, Shriji Estate, Near Ashapuri Hotel or Water Tank,\",\n    \"fromAddr2\": \"N.H.NO.8,Aslali By Pass Road. Aslali,\",\n    \"fromGstin\": \"24AAKFA8531G1ZK\",\n    \"fromPincode\": 382427,\n    \"fromPlace\": \"Ahmedabad\",\n    \"fromStateCode\": 24,\n    \"fromTrdName\": \"Ahmedabad Warehouse-Billing\",\n    \"genMode\": \"API\",\n    \"igstValue\": 0.0,\n    \"itemList\": [\n        {\n            \"cessNonAdvol\": 0.0,\n            \"cessRate\": 0.0,\n            \"cgstRate\": 2.5,\n            \"hsnCode\": 31059090,\n            \"igstRate\": 0,\n            \"itemNo\": 1,\n            \"productDesc\": \"AMIPRO-K  1 LTR\",\n            \"productId\": 0,\n            \"productName\": \"\",\n            \"qtyUnit\": \"OTH\",\n            \"quantity\": 8.0,\n            \"sgstRate\": 2.5,\n            \"taxableAmount\": 70640.0\n        },\n        {\n            \"cessNonAdvol\": 0.0,\n            \"cessRate\": 0.0,\n            \"cgstRate\": 2.5,\n            \"hsnCode\": 31059090,\n            \"igstRate\": 0,\n            \"itemNo\": 2,\n            \"productDesc\": \"AMIPRO-K  5 LTR X 2 NOS\",\n            \"productId\": 0,\n            \"productName\": \"\",\n            \"qtyUnit\": \"OTH\",\n            \"quantity\": 9.0,\n            \"sgstRate\": 2.5,\n            \"taxableAmount\": 78570.0\n        },\n        {\n            \"cessNonAdvol\": 0.0,\n            \"cessRate\": 0.0,\n            \"cgstRate\": 6.0,\n            \"hsnCode\": 28402090,\n            \"igstRate\": 0,\n            \"itemNo\": 3,\n            \"productDesc\": \"BONOS  1 LTR\",\n            \"productId\": 0,\n            \"productName\": \"\",\n            \"qtyUnit\": \"OTH\",\n            \"quantity\": 2.0,\n            \"sgstRate\": 6.0,\n            \"taxableAmount\": 13160.0\n        },\n        {\n            \"cessNonAdvol\": 0.0,\n            \"cessRate\": 0.0,\n            \"cgstRate\": 2.5,\n            \"hsnCode\": 31059090,\n            \"igstRate\": 0,\n            \"itemNo\": 4,\n            \"productDesc\": \"AMIPRO-K  1 LTR\",\n            \"productId\": 0,\n            \"productName\": \"\",\n            \"qtyUnit\": \"OTH\",\n            \"quantity\": 2.0,\n            \"sgstRate\": 2.5,\n            \"taxableAmount\": 17660.0\n        }\n    ],\n    \"noValidDays\": 0,\n    \"otherValue\": 0.0,\n    \"rejectStatus\": \"N\",\n    \"sgstValue\": 4961.0,\n    \"status\": \"ACT\",\n    \"subSupplyType\": \"1  \",\n    \"supplyType\": \"O\",\n    \"toAddr1\": \"Nr Bob Station Road\",\n    \"toAddr2\": \"Nr Bob Station Road\",\n    \"toGstin\": \"24AACFK1807H1ZR\",\n    \"toPincode\": 393145,\n    \"toPlace\": \"Rajpipla\",\n    \"toStateCode\": 24,\n    \"toTrdName\": \"AMD00013\",\n    \"totInvValue\": 189952.0,\n    \"totalValue\": 180030.0,\n    \"transactionType\": 4,\n    \"transporterId\": \"24ABCPP1847K1ZK\",\n    \"transporterName\": \"\",\n    \"userGstin\": \"24AAKFA8531G1ZK\",\n    \"validUpto\": \"\",\n    \"vehicleType\": \" \"\n}","doctype":"e-Waybill Log","__last_sync_on":"2023-04-13T13:39:59.619Z"}

**Comment by sjain17** [comment]
Here is a sample Eway which was created for In-state but it shows "transactionType": 4 (Combination of 2 and 3)

**Comment by sjain17** [comment]
Here is another sample -
![Screenshot 2023-04-13 at 7 17 41 PM](https://user-images.githubusercontent.com/30950233/231779339-44ab61b8-7cd6-4354-975a-b0f62d8aefdf.png)
