### ISSUE TITLE
E way bill need for subcontracting order

### ISSUE THREAD

**Issue by Nandhinidevi123** [resilient-tech/india-compliance#590]
### Is your feature request related to a problem? Please describe.

whenever goods go outside for subcontracting works eway bill was needed.

**Comment by vorasmit** [comment]
Did you try creating e-Waybill from Delivery Note. You can generate e-Waybill for subcontracting there.

**Comment by satisharalkar** [comment]
Hi Smith - On Delivery note, there is no option of selecting sub contracting Supplier, so unable to use Delivery note in Subcontracting process. We need manual E-way Bill creation option on stock entry.

Thanks In Advance
Regards,
Satish Aralkar
