### ISSUE TITLE
Automatic e-waybill generation should be configurable.

### ISSUE THREAD

**Issue by AfshanKhan** [resilient-tech/india-compliance#591]
### Is your feature request related to a problem? Please describe.

In the business it is required to generate e-waybill only when the goods are loaded in the truck because that is when all the e-waybill related information is available to feed into the system, this can happens after the submission of sales invoice and can take more than 12 hours as well. There is option to update e-waybill but that doesn't solves our problem because it cannot be updated after 12 hours.

### Describe the solution you'd like

We suggest to make this option configurable as per the need of the user of the system and not force the system to automatically generated e-waybill for all.

### Describe alternatives you've considered

We tried to remove the readonly property of the  Automatically Generate E-waybill checkbox and disable it. Even after being disabled the system is still generating e-waybill and even for the invoices which have total amount of less than 50,000

**Comment by vorasmit** [comment]
>  There is an option to update the e-waybill but that doesn't solve our problem because it cannot be updated after 12 hours.

e-Waybill, can be updated up to 24 hours after generation. However, the validity of the e-Waybill is based on the distance. There are options to extend validity if needed.

> even for the invoices which have the total amount of less than 50,000

This limit is only for users who just want to generate an e-Waybill using the automation feature. Usually, an e-Waybill is automatically generated by the e-Invoice portal if transporter information is sent along with the data, irrespective of the amount of the invoice.

There is nothing wrong with this though.

**A simple workaround:**
This can be achieved with simple customisation at your end.

Don't allow users to update transporter information when an invoice is submitted. e-Waybill, will not be automatically generated in this case.

Update vehicle information only when you wish to generate an e-Waybill.
