### ISSUE TITLE
Search API not working in sandbox mode

### ISSUE THREAD

**Issue by arkayapps** [resilient-tech/india-compliance#595]
API Request Failed: Invalid Data Format on DigitalOCean Cloud server.  When new Customer ADD from GST no. Error Log as below.

{
    "errorCode": "TEC4002",
    "message": "Invalid Data Format",
    "status": 500,
    "success": false
}

**Comment by vorasmit** [comment]
Hello,

Based on my understanding this error should never occur if you are using the correct APIs.
Can you share the Integration Request Log for us to inspect this further?

**Comment by arkayapps** [comment]
Please check the attached screen shoot. 
<img width="1059" alt="Screenshot 2023-04-14 at 7 50 15 PM" src="https://user-images.githubusercontent.com/1407282/232070995-340cee18-ad2e-49ba-88ef-47ca18da7bf0.png">
<img width="1297" alt="Screenshot 2023-04-14 at 7 50 05 PM" src="https://user-images.githubusercontent.com/1407282/232071043-cad6ff51-590f-4086-85fb-efd9b91b8f39.png">
<img width="1296" alt="Screenshot 2023-04-14 at 7 49 58 PM" src="https://user-images.githubusercontent.com/1407282/232071075-fa9b4049-5cc0-42f9-b3ba-d1029f632e2b.png">

**Comment by vorasmit** [comment]
Hello,

We are not able to identify the issue here based on the available information.

We request you try the APIs locally or on another server.

If it works, most likely issue could be with your system configuration or some customisation.
You can reach out to us at hello@indiacompliance.app for paid support if you need any.

Closing this issue now as its an API or Server issue and has nothing to do with app.

**Comment by sagarvora** [comment]
@vorasmit I was able to replicate this for search API in sandbox mode.

**Comment by sagarvora** [comment]
This is a known issue with the upstream provider in sandbox mode. There is no solution as of yet, but we will post an update here when a solution is available.

Email from upstream provider:

![image](https://user-images.githubusercontent.com/16315650/236705416-5cb79f15-581a-45fb-a9be-391713571958.png)

We are considering disabling the feature in sandbox mode if it takes longer to resolve.
