### ISSUE TITLE
Bill of Entry Improvement 

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#599]
### Is your feature request related to a problem? Please describe.

1. Creation of new Fields Bill Of Landing while creating of Bill Of Entry
2. In All Overseas transactions GST Amount would be calculated  Should be rounded off automatically
3. Required a proper Report with the below details. ( Can be Called Import Purchase Register )

PI No | PI Date | Amount | Bill of Entry | Bill Entry Date | Port Code | Assessable Value | Taxable Value | GST Rate | GST Amount | Custom Duty Paybale | Custom Duty Paid Entry No ( JV ) | Landed Cost Expense Account | Amount |

**Comment by vorasmit** [comment]
> In All Overseas transactions GST Amount would be calculated Should be rounded off automatically

Can this be generalized? You have the option to select the actual amount as well.

> Creation of new Fields Bill Of Lading

Seems to be just a custom field with no additional logic or significance. Correct? Currently, users can add them while it's not yet officially available. Thanks for the suggestion.

Additional suggested enhancement:
- [ ] Respect GST roundoff settings in bill of entry

**Comment by dineshpanchal93** [comment]
> > In All Overseas transactions GST Amount would be calculated Should be rounded off automatically
> 
> Can this be generalized? You have the option to select the actual amount as well.
> Yes can be used option to select the actual amount ( In that case user may input the wrong values ).
> > Creation of new Fields Bill Of Lading
> 
> Seems to be just a custom field with no additional logic or significance. Correct? Currently, users can add them while it's not yet officially available. Thanks for the suggestion.
> Yes it's a custom field, its a part of BOE Entry. Its not mandatory but if its available then would be great.
> Additional suggested enhancement:
> 
> * [ ]  Respect GST roundoff settings in the bill of entry

**Comment by dineshpanchal93** [comment]
Can you please update the report it's from the Purchase Invoice Posting date?

because when we check the IGST amount in the Bill of Entry Summery report it shows wrong because some are the bill of entry is being back-dated. too but we have booked the invoice for next month.

Can consider this for the further enhancement
