### ISSUE TITLE
'NoneType' object has no attribute 'split' when attempting to save a quotation

### ISSUE THREAD

**Issue by BaaridunNasr** [resilient-tech/india-compliance#612]
### Information about bug

Getting this error when I attempt to save a quotation.

### Version

{
	"erpnext": "14.22.2",
	"frappe": "14.33.1",
	"hrms": "14.2.2",
	"india_compliance": "14.5.4",
	"payments": "0.0.1"
}

### Relevant log output / Stack trace / Full Error Message.

```shell
### Route

Form/Quotation/new-quotation-1
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 66, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 45, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 83, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1607, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/desk/form/save.py", line 26, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 305, in save
    return self._save(*args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 327, in _save
    return self.insert()
  File "apps/frappe/frappe/model/document.py", line 259, in insert
    self.run_before_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1045, in run_before_save_methods
    self.run_method("validate")
  File "apps/frappe/frappe/model/document.py", line 914, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1264, in composer
    return composed(self, method, *args, **kwargs)
  File "apps/frappe/frappe/model/document.py", line 1248, in runner
    add_to_return_value(self, f(self, method, *args, **kwargs))
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 719, in validate_transaction
    validate_place_of_supply(doc)
  File "apps/india_compliance/india_compliance/gst_india/overrides/transaction.py", line 356, in validate_place_of_supply
    valid_options = doc.meta.get_field("place_of_supply").options.split("\n")
AttributeError: 'NoneType' object has no attribute 'split'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by BaaridunNasr** [comment]
I find the same issue in Purchase Orders as well

**Comment by sagarvora** [comment]
The field `place_of_supply` should be present in both doctypes - Quotation and Purchase Order. Is that not the case for you? Is that because the customisations you exported with **Export Customisations** button in Customize Form are overriding the field being created by the app?

**Comment by sagarvora** [comment]
Since we cannot replicate this as of now, I will keep the issue in Closed state and remove the bug label (as per policy). If it is later found to be a bug, we will revert this action. Note that you can still comment on this issue in Closed state.

**Comment by BaaridunNasr** [comment]
![image](https://user-images.githubusercontent.com/12585952/233336919-b07c99a3-15c6-4cbf-a222-4301754fe8a9.png)

Place of supply is a data field with no options. We have no customization editing this field.

**Comment by BaaridunNasr** [comment]
Im not able to say if there is some customization from other apps that are interfering.

**Comment by sagarvora** [comment]
When we converted the field from `Data` to `Autocomplete`, we had re-triggered the updation of custom fields like we always do:
https://github.com/resilient-tech/india-compliance/pull/504/files#diff-a58db33216a11f1c7c9f7d0f27e10719bd79b190836aa0ed74a505c0decd3699R6

This issue should not happen unless some customisation is interfering. Running the aforementioned patch yourself (using `bench execute` or `bench console`) should fix the issue.

**Comment by sagarvora** [comment]
Ok, I can see from above versions that you don't have a custom app. That's weird. In that case, you may have just skipped running DB migration after updating the app.

**Comment by BaaridunNasr** [comment]
This is directly present on Frappe Cloud, so we do not have control over the bench migrate. Maybe I try to run migrate again?

**Comment by sagarvora** [comment]
> Maybe I try to run migrate again?

Yeah, let us know if this helps.

**Comment by BaaridunNasr** [comment]
Running migrate again did not affect it anyway, nor did running the patch function individually. I had to create the fields manually.
