### ISSUE TITLE
GST Transporter ID

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#620]
### Information about bug

Supplier GST No and Transporter ID should be different.

System Auto Change the Transporter ID as GST No.

Kindly please look into it.

### Version

Frappe Chat: v0.0.1 (main)

ERPNext: v14.22.0 (version-14)

Frappe Framework: v14.33.0 (version-14)

Gatepass: v0.0.1 (main)

Frappe HR: v14.2.2 (version-14)

India Compliance: v14.5.3 (version-14)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Improvisation is possible here.
Thanks for reporting.

Update GST Transporter ID only in the following scenarios should ideally work:

- [ ] where it's not already set
- [ ] where PAN is different in GST Transporter ID

**Comment by dineshpanchal93** [comment]
Yes.


<img width="1331" alt="Screenshot 2023-04-22 at 10 20 50 AM" src="https://user-images.githubusercontent.com/21578167/233763216-97cad74f-8fc6-4b7b-826d-d73586ac14bb.png">
