### ISSUE TITLE
GST Settings Page - Invalid "depends_on" expression

### ISSUE THREAD

**Issue by barathprathosh** [resilient-tech/india-compliance#625]
### Information about bug

After update the India Compliance App into New Version, once open the GST Settings Depends_on Expression error. Is this Error because of update or any other settings i need to enable or configure. before update it's working properly

![Screenshot from 2023-04-23 15-08-09](https://user-images.githubusercontent.com/48587404/233832590-c41b21c1-fedf-4f28-b8d1-386d2e75b520.png)
 

### Version

Ecommerce Integrations: v1.15.4 (main)
ERPNext: v14.22.2 (version-14)
Frappe Framework: v14.33.1 (version-14)
India Compliance: v14.6.0 (version-14)
Payments: v0.0.1 (develop)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Are your JS assets built correctly? Did you run `bench build` after updating?

Can you please share the output of executing following JS code in browser console?

```javascript
console.log(india_compliance, window.india_compliance);
console.log(india_compliance.is_api_enabled, window.india_compliance.is_api_enabled);
```

**Comment by barathprathosh** [comment]
After run bench build, it's working fine.Thank you
