### ISSUE TITLE
einvoice button not available if customer is unregistered

### ISSUE THREAD

**Issue by bhavyajicomputers** [resilient-tech/india-compliance#633]
### Information about bug

not able to create einvoice for unregistered customer

### Version

erpnext": "14.22.2",
"frappe": "14.33.1",
"hrms": "14.2.2",
"india_compliance": "14.5.4"

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
e-Invoice is not applicable for B2C transactions.

**Comment by bhavyajicomputers** [comment]
![image](https://user-images.githubusercontent.com/113116758/235800853-8768fc3b-c86a-4aec-9884-b22b3ea4be2d.png)
Kindly do needful. its applicable for certain companies to create qr code without irn for b2c transactions. and erp should be able to address requirement of all users

**Comment by vorasmit** [comment]
Hi,

Thanks for reaching out with your feature request. Unfortunately, it looks like the feature you're asking for is only applicable to companies with a turnover of more than 500 crores.

Additionally, implementing this feature would mostly require changes to the print format, which is usually custom in most cases. We don't believe we would be able to add much value in that regard, so at this time we don't plan to implement this feature.

We appreciate your understanding and encourage you to continue providing feedback on ways we can improve our product.

Please don't hesitate to reach out to us if you have any further questions or concerns.
