### ISSUE TITLE
Issues in eway bill and e-invoicing 

### ISSUE THREAD

**Issue by sjain17** [resilient-tech/india-compliance#645]
### Information about bug

E-way Bill

The address title is shown in the GSTIN of Supplier and GSTIN of Recipient along with the GST number for example -
Dispatch & Company Address title = Factory Warehouse 
GSTIN of Dispatch & Company Address = 27XXXXXXXXXX1ZG
Customer Address title = ABC Enterprises Factory
GSTIN of Customer Address = 23XXXXXXXXXX1ZS

Currently, In the e-way bill it is as shown below -
GSTIN of Supplier: 27XXXXXXXXXX1ZG-Factory Warehouse 
GSTIN of Recipient: 23XXXXXXXXXX1ZS-ABC Enterprises Factory

However, it should be - 
GSTIN of Supplier: 27XXXXXXXXXX1ZG
GSTIN of Recipient: 23XXXXXXXXXX1ZS

If the Transporter is unregistered then in e-way it shows the supplier ID (I am using supplier naming series and not name) instead of the Supplier Name; and, if it is a registered transporter it shows the supplier name. However, it should always show the supplier name in the transporter.

---------------------------------------------------------------------------------------------------------------------------

E-Invoice 
1. If we remove the address title then the system does not create a sales invoice with an e-invoice.

### Version

ERPNext: v14.22.2 (version-14)
Frappe Framework: v14.33.1 (version-14)
Frappe HR: v1.0.0 (develop)
India Compliance: v14.6.1 (version-14)
Payments: v0.0.1 (develop)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Reference PRs
#642 #615 

We have taken this approach and field address_title was most reliable for Bill to Ship to cases, to identify the tradename where the material is sent (required for both e-Waybill and e-Invoice).

Note:
Even after we fix this, the tradename for the Shipping address and Dispatch address would still be dependent on Address Title. We can just use Customer Name for Billing Address as you have identified.
