### ISSUE TITLE
HSN-wise-summary of Outward Supplies GST-report showing incorrect data for UQC

### ISSUE THREAD

**Issue by innomalous** [resilient-tech/india-compliance#664]
### Information about bug

Hello team,

The HSN-wise Summary of Outward Supplies report under Other GST Reports is reporting incorrect UQC data.

We are using **Kg** for HSN 2309, **Units** for HSN 23091000, and **Nos** for HSN 996812 as the UOMs in our invoices. However, the UQC is reported as OTH and NA in the report. (See screenshot below)

![erpnext hsn screenshot](https://user-images.githubusercontent.com/42608563/236846797-7a0ff3e3-a947-4ad7-9882-b3322b87e464.jpg)

All other data seems correct, just the UQC is reported incorrectly.

### Version

Frappe v14.35.0
ERPNext v14.23.2
India Compliance v14.6.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by innomalous** [comment]
Hi, when can we expect this feature in a stable release? We're currently on India Compliance v14.7.0 on Frappe Cloud.

**Comment by sagarvora** [comment]
Hi,

It will be a part of the next feature release, i.e. v14.8.0. We generally try to do weekly releases, but it's not consistent as of now.
