### ISSUE TITLE
Error while generating e-Invoice

### ISSUE THREAD

**Issue by nilprakash** [resilient-tech/india-compliance#689]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='asp.resilient.tech', port=443): Max retries exceeded with url: /ei/api/invoice (Caused by NewConnectionError(': Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

**Comment by sagarvora** [comment]
Hello, there seems to be an issue with your server's DNS configuration. It's working as expected for us:

![image](https://github.com/resilient-tech/india-compliance/assets/16315650/244d678e-1ccc-4afe-bea2-5066b89c922f)

Consider availing paid support over email.

**Comment by nilprakash** [comment]
Thanks
