### ISSUE TITLE
Purchase Receipt & Date column showing Blank in GST Itemised Purchase Register

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#705]
### Information about bug

Purchase Receipt & Date column showing Blank in GST Itemised Purchase Register
![pr rcpt   date](https://github.com/resilient-tech/india-compliance/assets/11851156/55180965-a655-4512-bd8d-b6d7c2a53eff)

### Version

v14.36.0 (version-14)
v14.24.1 (version-14)
v14.6.2 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Hello,

This report is a simple extension of the Item Wise Purchase Register from ERPNext.
The issue with the Purchase Receipt column will need fixes in ERPNext Item Wise Purchase Register. You may raise this issue in ERPNext.

https://github.com/resilient-tech/india-compliance/blob/develop/india_compliance/gst_india/report/gst_itemised_purchase_register/gst_itemised_purchase_register.py#L5

Closing this here for now.
