### ISSUE TITLE
India Compliance error: No such file or directory: ./assets/india_compliance/js/setup_wizard.js

### ISSUE THREAD

**Issue by khushalmer03** [resilient-tech/india-compliance#706]
### Information about bug

I’m trying to create docker image that has custom-applications with base-image frappe/erpnext:v14.24.2
Dockerfile:

`FROM frappe/erpnext:v14.24.2

WORKDIR /home/frappe/frappe-bench

RUN bench get-app --branch version-14 hrms

RUN bench get-app --branch version-14 payments

RUN bench get-app --branch version-14 https://github.com/resilient-tech/india-compliance.git

`
The image is built successfully but when i use this image in frappe/erpnext-6.0.35 helm chart to deploy erpnext and create new site and install all the applications in it, everything works fine and all apps are installed successfully as well but upon opening the application, I get following error:
FileNotFoundError: [Errno2] No such file or directory: ./assets/india_compliance/js/setup_wizard.js

Now if I don’t include india_compliance in the initial installation and only install erpnext in site, complete the setup and then install india_compliance the error goes away and everything works fine. I believe india_compliance doesn't let the setup_wizard of erpnext  to run?

### Version

Frappe Version: v14.36.1
ERPNext Version: v14.24.2
India Compliance Version: v14.6.2 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
Server Error
FileNotFoundError: [Errno2] No such file or directory: ./assets/india_compliance/js/setup_wizard.js
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Hello, this isn't a bug but an installation related issue. I see you've already created a topic on the discussion forum:
https://discuss.frappe.io/t/india-compliance-error-no-such-file-or-directory-assets-india-compliance-js-setup-wizard-js/105229

That's the right place to get help for such issues.

You can refer to this successful docker installation example:
https://discuss.frappe.io/t/upgrading-to-v14-for-a-dockerized-deployement/93973/2
https://gitlab.com/castlecraft/cepl-erpnext-images

Alternatively, consider emailing us for paid support.

**Comment by khushalmer03** [comment]
Okay, thank you for guidance!
