### ISSUE TITLE
5002 : Application error, issue with application while processing the request.

### ISSUE THREAD

**Issue by Krishna-svsa** [resilient-tech/india-compliance#711]
Getting below error while generating the IRN.

5002 : Application error, issue with application while processing the request. Please try again. If error persists kindly raise a ticket along with request JSON, error details and timestamp of the error occurrence.

<img width="953" alt="image" src="https://github.com/resilient-tech/india-compliance/assets/134470993/aa89906f-0fc4-4887-8f58-00b885f58aa3">

{"name":"ce313e3e60","owner":"krishna@aristo-india.com","creation":"2023-05-24 18:21:52.302827","modified":"2023-05-24 18:21:52.302827","modified_by":"krishna@aristo-india.com","docstatus":0,"idx":0,"request_id":"c6c9b370-fa13-4fb6-9c6e-fb2b0fc7f0ea","integration_request_service":"India Compliance API","is_remote_request":0,"status":"Failed","url":"https://asp.resilient.tech/ei/api/invoice","request_headers":"{\n    \"gstin\": \"29AAHCK3507G1ZJ\",\n    \"password\": \"*****\",\n    \"requestid\": \"67b71a7b31f9\",\n    \"user_name\": \"API_29AAHCK3507G1ZJ\",\n    \"x-api-key\": \"*****\"\n}","data":"{\n    \"BuyerDtls\": {\n        \"Addr1\": \"KAADABEESANAHAALI NO 37/1,\",\n        \"Addr2\": \"PANATHUR POST, REDDY LAYOUT\",\n        \"Gstin\": \"29ADFPG4253M1ZA\",\n        \"LglNm\": \"CRAFTSMAN\",\n        \"Loc\": \"BANGALORE\",\n        \"Pin\": 560103,\n        \"Pos\": \"29\",\n        \"Stcd\": \"29\",\n        \"TrdNm\": \"Craftsman \"\n    },\n    \"DispDtls\": {\n        \"Addr1\": \"Plot No.244, KIADB Bommasandra Indl. Area,\",\n        \"Addr2\": \"Ph 3, Hosur Rd, Bommasandra,\",\n        \"Loc\": \"BANGALORE\",\n        \"Nm\": \"KBROS ARISTO PVT. LTD. BANGALORE\",\n        \"Pin\": 560099,\n        \"Stcd\": \"29\"\n    },\n    \"DocDtls\": {\n        \"Dt\": \"24/05/2023\",\n        \"No\": \"DSDBO2324/00066\",\n        \"Typ\": \"INV\"\n    },\n    \"EwbDtls\": {\n        \"Distance\": 0\n    },\n    \"ItemList\": [\n        {\n            \"AssAmt\": 93770.0,\n            \"BchDtls\": {\n                \"Nm\": \"B174838\"\n            },\n            \"CesAmt\": 0,\n            \"CesNonAdvlAmt\": 0,\n            \"CesRt\": 0,\n            \"CgstAmt\": 8439.3,\n            \"Discount\": 0,\n            \"GstRt\": 18.0,\n            \"HsnCd\": \"76101000\",\n            \"IgstAmt\": 0,\n            \"IsServc\": \"N\",\n            \"PrdDesc\": \"Aristo Nova System - Champagne Glossy\",\n            \"Qty\": 2.0,\n            \"SgstAmt\": 8439.3,\n            \"SlNo\": \"1\",\n            \"TotAmt\": 93770.0,\n            \"TotItemVal\": 110648.6,\n            \"Unit\": \"NOS\",\n            \"UnitPrice\": 46885.0\n        },\n        {\n            \"AssAmt\": 81181.0,\n            \"BchDtls\": {\n                \"Nm\": \"B174838\"\n            },\n            \"CesAmt\": 0,\n            \"CesNonAdvlAmt\": 0,\n            \"CesRt\": 0,\n            \"CgstAmt\": 7306.29,\n            \"Discount\": 0,\n            \"GstRt\": 18.0,\n            \"HsnCd\": \"76101000\",\n            \"IgstAmt\": 0,\n            \"IsServc\": \"N\",\n            \"PrdDesc\": \"Aristo Nova System - Champagne Glossy\",\n            \"Qty\": 2.0,\n            \"SgstAmt\": 7306.29,\n            \"SlNo\": \"2\",\n            \"TotAmt\": 81181.0,\n            \"TotItemVal\": 95793.58,\n            \"Unit\": \"NOS\",\n            \"UnitPrice\": 40590.5\n        },\n        {\n            \"AssAmt\": 93770.0,\n            \"BchDtls\": {\n                \"Nm\": \"B174838\"\n            },\n            \"CesAmt\": 0,\n            \"CesNonAdvlAmt\": 0,\n            \"CesRt\": 0,\n            \"CgstAmt\": 8439.3,\n            \"Discount\": 0,\n            \"GstRt\": 18.0,\n            \"HsnCd\": \"76101000\",\n            \"IgstAmt\": 0,\n            \"IsServc\": \"N\",\n            \"PrdDesc\": \"Aristo Nova System - Champagne Glossy\",\n            \"Qty\": 2.0,\n            \"SgstAmt\": 8439.3,\n            \"SlNo\": \"3\",\n            \"TotAmt\": 93770.0,\n            \"TotItemVal\": 110648.6,\n            \"Unit\": \"NOS\",\n            \"UnitPrice\": 46885.0\n        }\n    ],\n    \"PayDtls\": {\n        \"CrDay\": 0,\n        \"PaidAmt\": 0,\n        \"PaymtDue\": 217936.0\n    },\n    \"SellerDtls\": {\n        \"Addr1\": \"Plot No.244, KIADB Bommasandra Indl. Area,\",\n        \"Addr2\": \"Ph 3, Hosur Rd, Bommasandra,\",\n        \"Gstin\": \"29AAHCK3507G1ZJ\",\n        \"LglNm\": \"KBROS ARISTO PVT. LTD. BANGALORE\",\n        \"Loc\": \"BANGALORE\",\n        \"Pin\": 560099,\n        \"Stcd\": \"29\",\n        \"TrdNm\": \"KBROS ARISTO PVT. LTD. BANGALORE\"\n    },\n    \"ShipDtls\": {\n        \"Addr1\": \"Mr. Shekar Chaturvedi, VILLA- 515, ADARSH PALM RETREAT, Lane 3 N, Phase 3, Adarsh Palm Retreat,\",\n        \"Addr2\": \"Bellandur,\",\n        \"Gstin\": \"URP\",\n        \"LglNm\": \"02-23-KA-320\",\n        \"Loc\": \"Bengaluru\",\n        \"Pin\": 560035,\n        \"Stcd\": \"29\",\n        \"TrdNm\": \"02-23-KA-320\"\n    },\n    \"TranDtls\": {\n        \"RegRev\": \"N\",\n        \"SupTyp\": \"B2B\",\n        \"TaxSch\": \"GST\"\n    },\n    \"ValDtls\": {\n        \"AssVal\": 268721.0,\n        \"CesVal\": 0,\n        \"CgstVal\": 24184.89,\n        \"Discount\": 0,\n        \"IgstVal\": 0,\n        \"OthChrg\": 0.0,\n        \"RndOffAmt\": 0.22,\n        \"SgstVal\": 24184.89,\n        \"TotInvVal\": 317091.0\n    },\n    \"Version\": \"1.1\"\n}","output":"{\n    \"message\": \"5002 : Application error, issue with application while processing the request. Please try again. If error persists kindly raise a ticket along with request JSON, error details and timestamp of the error occurrence.\",\n    \"success\": false\n}","error":"5002 : Application error, issue with application while processing the request. Please try again. If error persists kindly raise a ticket along with request JSON, error details and timestamp of the error occurrence.","reference_doctype":"Sales Invoice","reference_docname":"DSDBO2324/00066","doctype":"Integration Request","__last_sync_on":"2023-05-24T12:52:39.530Z"}

**Comment by ganz007** [comment]
We are also getting this same error! No einvoices are bring generated! Sometimes we get the attached error also.
<img width="1406" alt="Screenshot 2023-05-24 at 6 51 26 PM" src="https://github.com/resilient-tech/india-compliance/assets/121344405/b61ede6b-da1a-4eaf-b3e1-eaa5898d1e59">

**Comment by sagarvora** [comment]
The issue you've mentioned happens because the API service is degraded or down on the Govt's side. In that scenario, neither the GSP (Adaequare) or the ASP (Resilient Tech) can do much about it. Our only recommendation when such an issue arises is to try again after sometime (maybe an hour or so).

**Comment by sagarvora** [comment]
Please consider closing this issue if you're no longer facing it. Thanks.

**Comment by Krishna-svsa** [comment]
Thanks for respoce and suggestions.

**Comment by vorasmit** [comment]
improved UX with #805
