### ISSUE TITLE
Ability to create e-Invoice manually, without e-Waybill

### ISSUE THREAD

**Issue by smbcatalyst** [resilient-tech/india-compliance#712]
### Information about bug

When we create E invoice on Sales invoice, the system is creating e waybill along with e invoice. We want to create only E invoice and not e wabill. Currently, we are cancelling e waybill on Portal on every sales invoice creation in ERPNext. Kindly guide us on the same.

### Version

ERPNext: v14.22.0 (HEAD)

Frappe Framework: v14.33.0 (HEAD)

Frappe Whatsapp: v0.0.2 (HEAD)

Frappe HR: v14.2.2 (HEAD)

India Compliance: v14.5.3 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sagarvora** [comment]
Hello, 

- Please check existing issues. This [issue](https://github.com/resilient-tech/india-compliance/issues/591) has already been [resolved](https://github.com/resilient-tech/india-compliance/pull/605) in v14.6.0 and above. You just need to upgrade and uncheck the option to automatically generate e-Waybill.
- This is not a bug. So the issue will be closed.

**EDIT:**

Only e-Invoice gets generated based on your configuration only if you're auto-generating it. If you're manually generating e-Invoice, e-Waybill will still get generated. Do you want to disable e-Waybill while generating e-Invoice manually or while auto-generating on submit?

**Comment by smbcatalyst** [comment]
We have set the account as per screenshot, stilll generating the e waybill. Yes, we want to disable E waybill when we create E invoice manually. 
![image](https://github.com/resilient-tech/india-compliance/assets/113963271/a8a528a1-58b8-433a-8ea0-ecfcaef75169)

**Comment by sagarvora** [comment]
Ok, I am reopening it as a feature request. Consider sponsoring this feature (email us) if you want it ASAP.

**Comment by smbcatalyst** [comment]
Can you share the estimation to pay?

**Comment by sagarvora** [comment]
Please email us on the following email address for more details:

```
hello [at] indiacompliance.app
```

**Comment by smbcatalyst** [comment]
It is showing invalid email id.
