### ISSUE TITLE
Difference in Taxable amount in GSTR-1 and HSN-WISE summary of Outward Supplies

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#715]
### Information about bug

Difference in Taxable amount in GSTR-1 and HSN-WISE summary of Outward Supplies:
- When I am checking the GSTR-1 report for the April month the taxable amount and taxable amount for the same month in HSN wise Summary of outward supplies are different. 
- The difference amount in both the reports is equal to internal transfer which is done in the organisation for that month.
- We have to remove this difference from the reports.
- Why the internal transfer where there is no GST applied is coming in HSN wise summary of outward supplies report. 

Please let us know the resolution for this issue.

### Version

ERPNext: v14.24.2 (version-14)
Frappe Framework: v14.36.1 (version-14)
India Compliance: v14.4.0 (version-14-dex)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello,

Thanks for reporting this. We would look into this and fix this issue.
We shall update you after this is fixed.

**Comment by vorasmit** [comment]
@asoral 
Just to confirm, you are referring to sales where `billing_address_gstin` and `company_gstin` are the same. Correct?
