### ISSUE TITLE
Use GSTIN to speed up onboarding

### ISSUE THREAD

**Issue by ankush** [resilient-tech/india-compliance#730]
### Describe the solution you'd like

During setup wizard prompt for GSTIN which can be used to populate company name, address and other settings. 

This can be optional. 

### Additional context

We are trying to smoothen onboarding and GST setup is one part of it.

**Comment by sagarvora** [comment]
@ankush To do this properly, we might have to prompt the user to create an India Compliance Account first (except on FC) 😅

**Comment by vorasmit** [comment]
This should still be pursued. Most config in company doctype is automatic except for this. And all GST validations would start with this.

The address can be auto-created if APIs are enabled.

**Comment by ankush** [comment]
@deepeshgarg007 can collaborate if required. He has a clear picture in his head for this :grimacing:
