### ISSUE TITLE
After additional discount the round off is calculating twice in Sales Invoice

### ISSUE THREAD

**Issue by sjain17** [resilient-tech/india-compliance#731]
### Information about bug

After additional discount the round-off is calculated twice in Sales Invoice. If a sales invoice has an additional discount and the amount of Taxes or Net Amount of Item requires rounding then rounding adjustment value is calculating twice.

### Version

ERPNext: v14.24.1 (version-14)
Frappe Framework: v14.36.0 (version-14)
India Compliance: v14.6.2 (version-14)

### Relevant log output / Stack trace / Full Error Message.

```shell
No error, only calculation mistake.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
You may please raise this pull request with appropriate screenshots in ERPNext.
This calculation doesn't form part of the India Complaince app.

If this issue is for a roundoff error in the e-Invoice or e-Waybill only, please share more details and we shall reopen this issue.

**Comment by sjain17** [comment]
Yes, it is an issue in e-invoice as well if we enable rounding off and provide additional discounts as well.
![Screenshot 2023-05-30 at 7 13 12 PM](https://github.com/resilient-tech/india-compliance/assets/30950233/8d39d417-c6d2-40a1-beec-7fb01f915e86)

**Comment by vorasmit** [comment]
I think we already had a detailed discussion in #580 about this. However, your original issue looks different from this screenshot.
