### ISSUE TITLE
HOW CAN WE STOP GST CALCULATION TO BE STOPPED IN SALES INVOICE AT THE TIME INTERNAL TRANSFER

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#745]
### Information about bug

How can we stop GST calculation in sales invoice when we are doing Internal transfer within the same state. We cannot opt for Delivery Note and Purchase Receipt method which is usual method because of some organisation workflows which needs to be followed. 
Please suggest how we can stop GST calculation in the case of internal transfer within the same state.

### Version

ERPNext: v14.26.0 (version-14)
Frappe Framework: v14.37.0 (version-14)
India Compliance: v14.8.0 (version-14-dex)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello,

While using same GSTIN in Billing and Company address ,no tax will be charged.

Hope this helps.
