### ISSUE TITLE
Sales Invoice ( Credit Note ) - ERP | Posting as Debit Note in GST Portal.

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#757]
### Information about bug

<img width="1274" alt="Screenshot 2023-06-08 at 5 53 03 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/4fb75ef3-26f5-4ad0-aac0-b05d4e578841">

<img width="1111" alt="Screenshot 2023-06-08 at 9 40 54 PM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/3cb5350b-40d2-442e-b19a-dd8d9f719eab">

In the GL Account is shows the correct in Credit Side but in GST Portal It Shows to the debit side.

### Version

ERPNext: v14.26.0 (version-14)

Frappe Framework: v14.37.1 (version-14)

Gatepass: v0.0.1 (main)

Frappe HR: v14.4.0 (version-14)

India Compliance: v14.9.0 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dineshpanchal93** [comment]
@sagarvora can you please check?

**Comment by sagarvora** [comment]
This is not a bug. You shouldn't check both **Is Return** and **Is Rate Adjustment Entry**. Please create PR / issue in ERPNext to disallow checking of both options at the same time.

**Comment by sagarvora** [comment]
Reopening. We will add validation for this.

**Comment by dineshpanchal93** [comment]
The purpose of this entry is to raise the Credit to the customer for the rate difference.

as in version v13 - it was worked well 

<img width="570" alt="Screenshot 2023-06-10 at 1 29 46 AM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/682292e1-2dd2-441c-9242-e77013c4093f">

<img width="1100" alt="Screenshot 2023-06-10 at 1 30 06 AM" src="https://github.com/resilient-tech/india-compliance/assets/21578167/cb99b0ed-686d-4d2d-a3fb-234155771b2f">

**Comment by sagarvora** [comment]
You can already create a credit note with zero quantity - without needing **Is Rate Adjustment Entry (Debit Note)** checked. How can something be both a credit note and a debit note?

**Comment by dineshpanchal93** [comment]
Yes. In Frappe documents I have read.

Is Return is for the Item ( If you check only Is Return Item cannot be Zero )

If you want to give a rate adjustment Credit note. then Set the qty Zero and also tick on Rate Adjustment Entry

**Comment by sagarvora** [comment]
Please share the relevant documentation. Currently we haven't observed any restriction preventing us from setting the quantity as zero while making a credit note (with `is_debit_note` unchecked).

**Comment by dineshpanchal93** [comment]
Then how can we give the credit note to the customer for the rate diff.


SI @ 100 INR 

We need to decrease the price with 10 INR ( Qty not affecting anywhere. )

How we can achieve this. v13 its working well.

**Comment by vorasmit** [comment]
This is how I created a credit note with Rs 100 and qty 0.

![image_2023-06-14_08-39-09](https://github.com/resilient-tech/india-compliance/assets/10496564/83307169-5d83-406a-8b80-9d206d10520c)

We shall add validation which will ensure both cannot be checked.

**Comment by dineshpanchal93** [comment]
Ok great Let me try

@vorasmit will update you
