### ISSUE TITLE
validation on country

### ISSUE THREAD

**Issue by precihole** [resilient-tech/india-compliance#788]
### Information about bug

```
def validate_overseas_gst_category(doc):
    if doc.country == "India" and doc.gst_category == "Overseas":
        frappe.throw(
            _("Cannot set GST Category as Overseas for Indian Address"),
            title=_("Invalid GST Category"),
        )

    if doc.country != "India" and doc.gst_category != "Overseas":
        frappe.throw(
            _("GST Category should be set to Overseas for Address outside India"),
            title=_("Invalid GST Category"),
        )
```
If we enter the country in capital letters, it is also being validated. Instead, you can validate it based on the country code, as shown below. This is just a suggestion, or you can also allow capital letters. @sagarvora  @vorasmit 
![image](https://github.com/resilient-tech/india-compliance/assets/111174201/7efd75a8-6e76-42ad-a0f3-c35e1bcc539b)

### Version

ERPNext: v14.27.7 (version-14)

Frappe Framework: v14.39.0 (version-14)

Frappe HR: v14.4.3 (version-14)

India Compliance: v14.10.2 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Hello,

We would prefer to keep this assumption that the country name is correct.
This is a requirement for a lot of things including Regional Overrides.

Even with your suggestion, we are placing some reliance on country_code. Also, it's an additional query for looking for country_code from the country.

Hence it's recommended not to rename the country.
