### ISSUE TITLE
Error In Uploading JSON File on GST Portal

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#794]
### Information about bug

We are facing below error in uploading Json File to GST portal.
![WhatsApp Image 2023-06-23 at 3 16 28 PM](https://github.com/resilient-tech/india-compliance/assets/11851156/dfc0420f-6849-41f2-84cd-9689192530ac)
![WhatsApp Image 2023-06-23 at 3 16 35 PM](https://github.com/resilient-tech/india-compliance/assets/11851156/9c3f2063-7a39-468f-aab4-bba91271ffb6)

### Version

ERPNext: v14.26.0 (version-14)
Frappe Framework: v14.37.0 (version-14)
India Compliance: v14.8.0 (version-14-dex)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Can you share the file that raised this error?

**Comment by asoral** [comment]
[Uploading gstr_1_nil_rated (3).txt…]()

**Comment by asoral** [comment]
@vorasmit 
File Attached.This Is Json File ,I changed Extension For Upload

**Comment by sagarvora** [comment]
> Uploading gstr_1_nil_rated (3).txt…

this isn't a valid link

**Comment by asoral** [comment]
Here is the code which in Json file:
{"version":"GST3.0.4","hash":"hash","gstin":"22AAJCB7280R1Z3","fp":"062023","nil":{"inv":[{"sply_ty":"INTRB2B"},{"sply_ty":"INTRAB2B"},{"sply_ty":"INTRB2C"},{"sply_ty":"INTRAB2C","nil_amt":8836245.2}]}}

GitHub doesn't support the Json file type attachments.

**Comment by asoral** [comment]
Any updates

**Comment by asoral** [comment]
@sagarvora Any Updates?
