### ISSUE TITLE
Pip's dependency error for package "repidfuzz"

### ISSUE THREAD

**Issue by HUMENTH** [resilient-tech/india-compliance#806]
### Information about bug

"repidfuzz" python module version conflict between erpnext and India-compliance app.

### Version

Frappe version - 14.40.1
Erpnext version - 14.28.0
India_compliance version - 14.10.2
Payments version - 0.0.1

### Relevant log output / Stack trace / Full Error Message.

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
erpnext 14.28.0 requires rapidfuzz~=2.15.0, but you have rapidfuzz 2.1.4 which is incompatible.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vinodkumarkolli** [comment]
Hi,

I am also facing the same issue after updating to latest version 14.10.2

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
india-compliance 14.10.2 requires rapidfuzz~=2.1.4, but you have rapidfuzz 2.15.1 which is incompatible.`
