### ISSUE TITLE
gst_hsn_code in field list is ambiguous in GST report

### ISSUE THREAD

**Issue by ishanloya** [resilient-tech/india-compliance#825]
### Information about bug

`pymysql.err.OperationalError: (1052, "Column 'gst_hsn_code' in field list is ambiguous")`

The above error is shown on both GST Itemised Sales Register and GST Itemised Purchase Register reports

### Version

ERPNext: v14.28.1 (version-14)
Frappe Framework: v14.40.1 (version-14)
India Compliance: v14.10.3 (version-14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohsinalimat** [comment]
Are you upgrade from version-13 to version-14 before?

**Comment by ishanloya** [comment]
Yes but that was a while back and the issue seems more recent

**Comment by mohsinalimat** [comment]
Same issue with me.

**Comment by vorasmit** [comment]
Already fixed here: https://github.com/resilient-tech/india-compliance/pull/818. 
Released in v14.10.4.
