### ISSUE TITLE
GST PURCHASE REGISTER

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#843]
### Information about bug

Information about bug
Whenever in customer "IS INTERNAL CUSTOMER" checkbox is ticked those transaction should not be recorded in GST PURCHASE REGSITER Report.
These transaction should not be considered as purchase.

### Version

ERPNext: v14.26.0 (version-14)
Frappe Framework: v14.37.0 (version-14)
India Compliance: v14.8.0 (version-14-dex)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Similar to #755. Duplicate.
