### ISSUE TITLE
GSTR3B json upload showing invalid error

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#850]
### Information about bug

While uploading json file to GST portal offline, showing Invalid json file error.
Please refer screenshot.

![gstr3b1](https://github.com/resilient-tech/india-compliance/assets/11851156/aaa04908-c3c5-48c4-aaf2-e5d5487ef0c4)

### Version

ERPNext: v14.26.0 (HEAD)
Frappe Framework: v14.37.0 (HEAD)
India Compliance: v14.8.0 (version-14-dex)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by asoral** [comment]
Please Resolve ASAP. Thanks

**Comment by asoral** [comment]
Any updates ?

**Comment by ljain112** [comment]
Duplicate #794
