### ISSUE TITLE
Recipient Trade Name is not showing in eway bill print format.

### ISSUE THREAD

**Issue by aa-prashant** [resilient-tech/india-compliance#861]
### Information about bug

Eway bill Print format is showing Customer ID in Recipient GST and Trade Name field.

### Version

Frappe Framework: v14.34.0 (version-14)
ERPNext: v14.22.3 (version-14)
India Compliance: v14.6.1 (version-14)

<img width="697" alt="Screenshot 2023-07-21 at 12 41 23 PM" src="https://github.com/resilient-tech/india-compliance/assets/31651947/78601660-9b94-484a-b27d-7cf850777254">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Fixed long back.
Please upgrade the version.
https://github.com/resilient-tech/india-compliance/pull/642
