### ISSUE TITLE
India compliance disabling option to automatically add tax from item tax settings…!

### ISSUE THREAD

**Issue by NayanGajjar** [resilient-tech/india-compliance#875]
### Information about bug

Why is India Compliance disabling the option to automatically add tax from item tax settings?

![a6569e81420509cac8c913e4a6a9b1788b2fc8b8_2_690x119](https://github.com/resilient-tech/india-compliance/assets/122445476/3c50c726-aa73-46ab-9a62-d408f50d488c)

Regards,
Nayan

### Version

frappe-14.40.3
payments-0.0.1
erpnext -14.30.1
india_compliance- 14.10.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Duplicate: https://discuss.frappe.io/t/india-compliance-disabling-option-to-automatically-add-tax-from-item-tax-settings/107581
