### ISSUE TITLE
Encryption key is invalid! Please check site_config.json

### ISSUE THREAD

**Issue by dineshpanchal93** [resilient-tech/india-compliance#881]
Encryption key is invalid! Please check site_config.json
If you have recently restored the site you may need to copy the site config contaning original Encryption Key.

pewexd@gmail.com

**Comment by sagarvora** [comment]
This issue isn't specific to India Compliance, it is a database restore issue. And the solution is mentioned in your issue description itself.

Please follow [Issue Guidelines](https://github.com/frappe/erpnext/wiki/Issue-Guidelines).

**Comment by dineshpanchal93** [comment]
resolved !!
