### ISSUE TITLE
Issue in GSTR 3B Details filter for Section 5

### ISSUE THREAD

**Issue by smbcatalyst** [resilient-tech/india-compliance#910]
### Information about bug

When we set filter for section 5 in Section field, the system shows server error.

![image](https://github.com/resilient-tech/india-compliance/assets/113963271/9bb05a9c-7173-4fd8-a4f3-dd6223dd49d4)

![image](https://github.com/resilient-tech/india-compliance/assets/113963271/14a436d0-281a-42d2-b959-4e9779d2f3cd)

### Version

ERPNext: v14.32.1 (HEAD)

Frappe Framework: v14.42.0 (HEAD)

Frappe Whatsapp: v0.0.2 (HEAD)

Frappe HR: v14.8.0 (HEAD)

India Compliance: v14.14.1 (HEAD)

Site Planning: v0.0.1 (HEAD

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello,

Thanks for reporting. We will fix this issue.
