### ISSUE TITLE
Export invoices showing up in both 6A as well as 8 (Nil rated) in GSTR1

### ISSUE THREAD

**Issue by nikkothari22** [resilient-tech/india-compliance#956]
### Information about bug

I have a sales invoice which is for export of services. The invoice amount is showing in both 6A as well as Nil rated inter state reports for GSTR1. 

When filing my GSTR1, the amount then shows up twice (after exporting JSON and uploading to GST portal)

Shouldn't the invoice amount only be shown on 6A and not under "Nil rated"? My assumption is that section 8A/B/C/D of GSTR1 is only for nil rated outward supplies that have not been added in the above sections. (https://cleartax.in/s/details-mentioned-return-gstr-1)

Is there a configuration step that I am missing maybe?

### Version

ERPNext: v14.33.2 (HEAD)
Frappe Framework: v14.43.1 (HEAD)
Frappe HR: v14.10.0 (HEAD)
India Compliance: v14.14.4 (HEAD)
Payments: v0.0.1 (HEAD)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Hello, @nikkothari22 ,

Thanks for reporting. We will fix this issue.
