### ISSUE TITLE
Gst3b return File Upload error

### ISSUE THREAD

**Issue by asoral** [resilient-tech/india-compliance#984]
### Information about bug

![image](https://github.com/resilient-tech/india-compliance/assets/11851156/dbfc6477-c071-4619-add1-7c81667be612)

### Version

Frappe version:v14.34.3
ErpNext Version: v14.44.0
India Compliance version:v14.14.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DaizyModi** [comment]
Hi @asoral, 

Did you modified the JSON manually before upload?

**Comment by vorasmit** [comment]
@asoral, Can you share the JSON file that caused this error? Please send it to support@indiacompliance.app. This will enable us to identify the issue.

I am presuming the error could be because of Rounding. Do you see numbers with more than 2 decimal points in your JSON output? Does restricting it to 2 digits and then uploading the file resolve the issue?

**Comment by asoral** [comment]
@vorasmit  I attached  json File Uploaded In txt format
{
 "gstin": "22AAJCB7280R1Z3",
 "inter_sup": {
  "comp_details": [],
  "uin_details": [],
  "unreg_details": []
 },
 "inward_sup": {
  "isup_details": [
   {
    "inter": 0.0,
    "intra": 1111251.84,
    "ty": "GST"
   },
   {
    "inter": 0.0,
    "intra": 0.0,
    "ty": "NONGST"
   }
  ]
 },
 "itc_elg": {
  "itc_avl": [
   {
    "camt": 0.0,
    "csamt": 0.0,
    "iamt": 0.0,
    "samt": 0.0,
    "ty": "IMPG"
   },
   {
    "camt": 0.0,
    "csamt": 0.0,
    "iamt": 0.0,
    "samt": 0.0,
    "ty": "IMPS"
   },
   {
    "camt": 0.0,
    "csamt": 0.0,
    "iamt": 0.0,
    "samt": 0.0,
    "ty": "ISRC"
   },
   {
    "camt": 0.0,
    "csamt": 0.0,
    "iamt": 0.0,
    "samt": 0.0,
    "ty": "ISD"
   },
   {
    "camt": 9639.1,
    "csamt": 0.0,
    "iamt": 84114.4,
    "samt": 9639.1,
    "ty": "OTH"
   }
  ],
  "itc_inelg": [
   {
    "camt": 0.0,
    "csamt": 0.0,
    "iamt": 0.0,
    "samt": 0.0,
    "ty": "RUL"
   },
   {
    "camt": 0.0,
    "csamt": 0.0,
    "iamt": 0.0,
    "samt": 0.0,
    "ty": "OTH"
   }
  ],
  "itc_net": {
   "camt": 9639.1,
   "csamt": 0.0,
   "iamt": 84114.4,
   "samt": 9639.1
  },
  "itc_rev": [
   {
    "camt": 0,
    "csamt": 0,
    "iamt": 0,
    "samt": 0,
    "ty": "RUL"
   },
   {
    "camt": 0,
    "csamt": 0,
    "iamt": 0,
    "samt": 0,
    "ty": "OTH"
   }
  ]
 },
 "ret_period": "072023",
 "sup_details": {
  "isup_rev": {
   "camt": 0,
   "csamt": 0,
   "iamt": 0,
   "samt": 0,
   "txval": 0
  },
  "osup_det": {
   "camt": 185728.38125000085,
   "csamt": 0,
   "iamt": 0,
   "samt": 185728.38125000085,
   "txval": 6143212.439999985
  },
  "osup_nil_exmp": {
   "txval": 9861604.730000002
  },
  "osup_nongst": {
   "txval": 0
  },
  "osup_zero": {
   "csamt": 0,
   "iamt": 0,
   "txval": 0
  }
 }
}
[GST3B.txt](https://github.com/resilient-tech/india-compliance/files/12426319/GST3B.txt)

**Comment by vorasmit** [comment]
Hi, Thank you so much for this.
Can you please try uploading the file I share and check if error still persists?

Change: Remove extra decimal points.
[GST3B.txt](https://github.com/resilient-tech/india-compliance/files/12427827/GST3B.txt)

This will give us clear idea for the fix required.

**Comment by asoral** [comment]
@vorasmit Ok I Will Check

**Comment by asoral** [comment]
@vorasmit Thanks ,it's Working
